import React, { useEffect, useMemo, useState } from 'react'
import { Activity, AlertTriangle, ArrowRight, BarChart3, CalendarDays, CheckCircle2, Download, Gift, Link2, Mail, Megaphone, Plus, Rocket, Sparkles, Target, TicketPercent, TrendingUp, Users } from 'lucide-react'
import type { EventItem } from '../../data/events'
import { getAutomationSummary, getCommunicationSummary, getMarketingCampaigns, getReadyCampaignActivations, getResolvedTracking, type MarketingCampaign } from '../../services/api'

type Props={events:EventItem[];producerName:string;producerId:number|null;eventId:string;setEventId:(v:string)=>void;period:string;setPeriod:(v:string)=>void;notify:(m:string)=>void;onNavigate?:(page:any)=>void}
const money=(c:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(c/100)
const pct=(n:number)=>`${n.toLocaleString('pt-BR',{maximumFractionDigits:1})}%`
const nav=(cb:Props['onNavigate'],notify:Props['notify'],page:string,label:string)=>cb?cb(page):notify(`Abrindo ${label}...`)

export default function MarketingHubOSPage(p:Props){
 const {events,producerName,producerId,eventId,setEventId,period,setPeriod,notify,onNavigate}=p
 const selectedEventId=eventId==='all'?undefined:Number(eventId)
 const [campaigns,setCampaigns]=useState<MarketingCampaign[]>([])
 const [ready,setReady]=useState<any[]>([])
 const [tracking,setTracking]=useState<any[]>([])
 const [automation,setAutomation]=useState<any|null>(null)
 const [communication,setCommunication]=useState<any|null>(null)
 const [loading,setLoading]=useState(true)
 const [warning,setWarning]=useState('')
 useEffect(()=>{let alive=true;setLoading(true);setWarning('');Promise.allSettled([
   getMarketingCampaigns(producerId||undefined,selectedEventId),getReadyCampaignActivations(producerId||undefined,selectedEventId),getResolvedTracking(producerId||undefined,selectedEventId),getAutomationSummary(producerId||undefined),getCommunicationSummary(producerId||undefined)
 ]).then(r=>{if(!alive)return; if(r[0].status==='fulfilled')setCampaigns(r[0].value);if(r[1].status==='fulfilled')setReady(r[1].value);if(r[2].status==='fulfilled')setTracking(r[2].value);if(r[3].status==='fulfilled')setAutomation(r[3].value);if(r[4].status==='fulfilled')setCommunication(r[4].value);const fails=r.filter(x=>x.status==='rejected').length;if(fails)setWarning(`${fails} fonte${fails>1?'s':''} do Hub indisponível${fails>1?'eis':''}. Os demais dados continuam ativos.`);setLoading(false)})
 return()=>{alive=false}},[producerId,selectedEventId,period])
 const k=useMemo(()=>{const active=campaigns.filter(c=>['ativa','active','ativo'].includes(c.status.toLowerCase()));const spent=campaigns.reduce((s,c)=>s+(c.spentCents||0),0);const revenue=campaigns.reduce((s,c)=>s+(c.revenueCents||0),0);const conv=campaigns.reduce((s,c)=>s+(c.conversions||0),0);const clicks=campaigns.reduce((s,c)=>s+(c.clicks||0),0);return{active,spent,revenue,conv,clicks,roas:spent?revenue/spent:0,cpa:conv?spent/conv:0,rate:clicks?conv/clicks*100:0}},[campaigns])
 const providers=tracking.filter(t=>t.mode!=='disabled'&&t.source!=='none')
 const healthParts=[campaigns.length?90:45,k.conv?85:55,automation?.activeFlows?80:50,providers.length?88:40];const health=Math.round(healthParts.reduce((a,b)=>a+b,0)/healthParts.length)
 const alerts=[...(providers.length?[]:[{tone:'bad',title:'Tracking requer configuração',desc:'Nenhum Pixel/Analytics resolvido para o contexto.'}]),...(k.active.length?[]:[{tone:'warn',title:'Nenhuma campanha ativa',desc:'Ative uma campanha para iniciar aquisição.'}]),...(communication&&communication.activeChannels===0?[{tone:'warn',title:'Canais de comunicação inativos',desc:'Configure WhatsApp ou E-mail para relacionamento.'}]:[])]
 const top=[...campaigns].sort((a,b)=>(b.revenueCents||0)-(a.revenueCents||0)).slice(0,5)
 const channelRows=useMemo(()=>{const m=new Map<string,{spent:number,revenue:number,count:number}>();campaigns.forEach(c=>{const x=m.get(c.channel)||{spent:0,revenue:0,count:0};x.spent+=c.spentCents||0;x.revenue+=c.revenueCents||0;x.count++;m.set(c.channel,x)});return [...m.entries()].map(([name,v])=>({name,...v,roas:v.spent?v.revenue/v.spent:0})).sort((a,b)=>b.revenue-a.revenue).slice(0,6)},[campaigns])
 return <section className="growth-page marketing-os-page">
  <div className="marketing-os-head"><div><p className="eyebrow">MARKETING OS · DASHBOARD UNIFICADO</p><h2>Dashboard Marketing</h2><p>Central de comando unificada para aquisição, campanhas, conversão, atribuição e inteligência de vendas.</p></div><div className="marketing-os-actions"><button className="btn primary" onClick={()=>nav(onNavigate,notify,'marketing-create','Nova Campanha')}><Plus size={16}/> Nova Campanha</button><button className="btn secondary" onClick={()=>notify('Exportação do Hub: use os relatórios do Marketing para gerar os dados consolidados.')}><Download size={15}/> Exportar Hub</button></div></div>
  <div className="marketing-os-context"><label><span>Produtora</span><strong>{producerName}</strong></label><label><span>Evento</span><select value={eventId} onChange={e=>setEventId(e.target.value)}><option value="all">Todos os eventos ({events.length})</option>{events.map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select></label><label><span>Período</span><select value={period} onChange={e=>setPeriod(e.target.value)}><option value="7">Últimos 7 dias</option><option value="30">Últimos 30 dias</option><option value="90">Últimos 90 dias</option><option value="year">Ano 2026</option></select></label></div>
  {warning&&<div className="marketing-os-warning"><AlertTriangle size={15}/>{warning}</div>}
  <div className="marketing-os-kpis">
   {[['Investimento',money(k.spent),TrendingUp],['Receita atribuída',money(k.revenue),TicketPercent],['ROAS médio',`${k.roas.toFixed(2)}x`,BarChart3],['CPA médio',money(k.cpa),Activity],['Vendas / conversões',String(k.conv),Users],['Conversão',pct(k.rate),Target]].map(([label,value,I]:any)=><div className="marketing-os-kpi" key={label}><span className="marketing-os-icon"><I size={18}/></span><div><small>{label}</small><strong>{loading?'—':value}</strong><em>{label==='ROAS médio'?`${k.active.length} campanhas ativas`:label==='Conversão'?`${k.clicks.toLocaleString('pt-BR')} cliques`:'Dados do contexto selecionado'}</em></div></div>)}
  </div>
  <div className="marketing-os-row marketing-os-row-main">
   <div className="marketing-os-panel health"><h3>Saúde do Marketing</h3><div className="health-body"><div className="health-ring" style={{'--score':`${health*3.6}deg`} as React.CSSProperties}><strong>{health}<small>/100</small></strong></div><div className="health-bars">{[['Aquisição',healthParts[0]],['Conversão',healthParts[1]],['Retenção',healthParts[2]],['Dados & Tracking',healthParts[3]]].map(([n,v]:any)=><div key={n}><span>{n}<b>{v}%</b></span><i><u style={{width:`${v}%`}}/></i></div>)}</div></div><button onClick={()=>nav(onNavigate,notify,'marketing-funnel-insights','Diagnóstico')}>Ver diagnóstico completo</button></div>
   <div className="marketing-os-panel alerts"><div className="panel-title"><h3>Alertas e Oportunidades</h3><span>{alerts.length}</span></div>{alerts.length?alerts.map((a,i)=><div className="alert-line" key={i}><AlertTriangle size={17}/><div><b>{a.title}</b><small>{a.desc}</small></div></div>):<div className="alert-line ok"><CheckCircle2 size={18}/><div><b>Operação sem alertas críticos</b><small>As fontes disponíveis estão respondendo normalmente.</small></div></div>}<div className="alert-line ok"><CheckCircle2 size={18}/><div><b>{providers.length} integrações de tracking resolvidas</b><small>Meta, GA4, GTM e demais provedores conforme configuração.</small></div></div><button onClick={()=>nav(onNavigate,notify,'marketing-tracking','Pixel & Analytics')}>Ver dados e tracking</button></div>
   <div className="marketing-os-panel activity"><div className="panel-title"><h3>Atividade Operacional</h3><span>Agora</span></div><div className="activity-list"><div><i/><b>{k.active.length} campanhas ativas</b><small>{campaigns.length} campanhas no contexto</small></div><div><i/><b>{ready.filter(x=>x.status==='ativa').length} campanhas prontas ativas</b><small>{ready.length} ativações registradas</small></div><div><i/><b>{automation?.activeFlows||0} automações ativas</b><small>{automation?.executions||0} execuções registradas</small></div><div><i/><b>{communication?.activeChannels||0} canais de comunicação ativos</b><small>{communication?.sent||0} mensagens enviadas</small></div></div></div>
  </div>
  <div className="marketing-os-row marketing-os-row-modules"><div className="marketing-os-panel modules"><div className="panel-title"><div><h3>Módulos de Marketing</h3><small>Planeje, execute, meça e fidelize sem sair do Dashboard.</small></div></div><div className="module-columns">
   <Module title="Planejar" icon={CalendarDays} items={[['Campanhas','marketing-campaigns'],['Campanhas Prontas','marketing-ready-campaigns']]} onNavigate={onNavigate} notify={notify}/>
   <Module title="Executar" icon={Rocket} items={[['Meta Ads','marketing-meta-ads'],['Google Ads','marketing-google-ads'],['TikTok Ads','marketing-tiktok-ads'],['WhatsApp','marketing-whatsapp'],['E-mail Marketing','marketing-email'],['Influenciadores','marketing-influencers']]} onNavigate={onNavigate} notify={notify}/>
   <Module title="Medir" icon={BarChart3} items={[['Central UTM','marketing-utm-central'],['Conversões','marketing-conversions'],['Pixel & Analytics','marketing-tracking'],['ROI e ROAS','marketing-reports']]} onNavigate={onNavigate} notify={notify}/>
   <Module title="Fidelizar" icon={Gift} items={[['Cupons & Descontos','marketing-coupons'],['Cashback','marketing-cashback'],['Afiliados','marketing-affiliates'],['Remarketing','remarketing-hub']]} onNavigate={onNavigate} notify={notify}/>
  </div></div>
  <div className="marketing-os-panel channels"><h3>Canais de Aquisição</h3><small>Performance por receita atribuída</small><div className="channel-list">{channelRows.length?channelRows.map((c,i)=><div key={c.name}><span>{c.name}<b>{c.roas.toFixed(1)}x</b></span><i><u style={{width:`${Math.max(8,100-(i*14))}%`}}/></i></div>):<p className="empty">Sem dados de canal no período.</p>}</div><button onClick={()=>nav(onNavigate,notify,'marketing-channel-performance','Performance por Canal')}>Ver desempenho completo</button></div></div>
  <div className="marketing-os-bottom">
   <div className="marketing-os-panel origin"><h3>Resumo de Aquisição</h3><div className="mini-stats"><span><small>Cliques</small><b>{k.clicks.toLocaleString('pt-BR')}</b></span><span><small>Conversões</small><b>{k.conv.toLocaleString('pt-BR')}</b></span><span><small>CPA</small><b>{money(k.cpa)}</b></span><span><small>Tracking</small><b>{providers.length}</b></span></div><button onClick={()=>nav(onNavigate,notify,'marketing-utm-central','Central UTM')}>Ver atribuição completa</button></div>
   <div className="marketing-os-panel top"><h3>Top Campanhas</h3>{top.length?<div className="top-table">{top.map(c=><div key={c.id}><span><b>{c.name}</b><small>{c.channel}</small></span><span>{money(c.revenueCents||0)}</span><strong>{c.spentCents?`${((c.revenueCents||0)/c.spentCents).toFixed(1)}x`:'—'}</strong></div>)}</div>:<p className="empty">Nenhuma campanha cadastrada.</p>}<button onClick={()=>nav(onNavigate,notify,'marketing-campaigns','Campanhas')}>Ver todas as campanhas</button></div>
   <div className="marketing-os-panel goal"><h3>Meta do Período</h3><p>A meta passa a usar configuração real quando definida no módulo de performance.</p><div className="goal-box"><span>Receita atribuída</span><strong>{money(k.revenue)}</strong><small>ROAS atual: {k.roas.toFixed(2)}x</small></div><button onClick={()=>nav(onNavigate,notify,'marketing-reports','Relatórios')}>Ver metas e projeções</button></div>
   <div className="marketing-os-panel tip"><Sparkles size={24}/><div><h3>Dica de Performance</h3><p>{k.active.length===0?'Ative uma campanha pronta para começar a gerar aquisição mensurável.':k.roas>0&&k.roas<3?'Revise campanhas com ROAS baixo antes de ampliar o orçamento.':'Use Campanhas Prontas e públicos segmentados para acelerar novas ações sem perder rastreabilidade.'}</p><button onClick={()=>nav(onNavigate,notify,'marketing-ready-campaigns','Campanhas Prontas')}>Configurar agora</button></div></div>
  </div>
 </section>
}
function Module({title,icon:Icon,items,onNavigate,notify}:{title:string;icon:any;items:string[][];onNavigate?:Props['onNavigate'];notify:Props['notify']}){return <div className="module-col"><h4><Icon size={18}/>{title}</h4><div>{items.map(([label,page])=><button key={page} onClick={()=>nav(onNavigate,notify,page,label)}><Megaphone size={12}/>{label}</button>)}</div><button className="module-access" onClick={()=>nav(onNavigate,notify,items[0][1],title)}>Acessar <ArrowRight size={12}/></button></div>}
