FROM node:22-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run db:generate:prod
ENV NODE_ENV=production
EXPOSE 3333
CMD ["sh","-c","npm run db:push:prod && npm run start:api"]
