import {
  type MonitoredCampaignDeliveryItem,
  type MonitoredChannelKey,
  type CampaignDeliveryStatus,
  DELIVERY_STATUS_DICTIONARY,
  evaluateCampaignDeliveryStatus
} from '../domain/marketing/campaignDeliveryMonitoring'

const STORAGE_KEY = 'diskingressos:campaign-delivery-telemetry-v3'

// 48 Campanhas detalhadas das 4 plataformas oficiais de mídia paga:
// - 31 Ativas e entregando (Meta 12, Google 8, TikTok 4, Spotify 7)
// - 6 Ativas sem entrega (Meta 2, Google 2, TikTok 1, Spotify 1)
// - 7 Em análise / fila (Meta 2, Google 1, TikTok 3, Spotify 1)
// - 4 Com problemas / rejeitadas (Meta 2, Google 1, TikTok 0, Spotify 1)
const INITIAL_CAMPAIGNS: MonitoredCampaignDeliveryItem[] = [
  // ===================== META ADS (18 campanhas: 12 Entregando, 2 Sem entrega, 2 Análise, 2 Rejeitadas) =====================
  {
    id: 'MON-META-001',
    campaignName: 'Festival Curitiba — Ingressos Oficiais (Feed & Stories)',
    channel: 'META',
    eventName: 'FESTIVAL CURITIBA 2026',
    eventId: 1,
    externalCampaignId: 'act_492019482_camp_9921',
    platformCampaignStatus: 'ACTIVE',
    platformAdSetStatus: 'ACTIVE',
    platformAdStatus: 'ACTIVE',
    platformStatusLabelPtBr: 'Ativa',
    deliveryStatus: 'ACTIVE_DELIVERING',
    deliveryMeta: DELIVERY_STATUS_DICTIONARY.ACTIVE_DELIVERING,
    impressionsLast6h: 14820,
    clicksLast6h: 684,
    spendLast6hCents: 42000,
    lastTelemetryAt: 'há 8 min',
    lastSyncAt: 'há 8 min',
    alerts: [{ level: 'INFO', message: 'Entregando normalmente em Instagram Feed, Reels e Facebook Stories com CTR de 4,6%.' }],
    totalSpentCents: 1240000,
    totalRevenueCents: 6840000,
    totalConversions: 312,
    roas: 5.51,
    startDate: '10/08/2026',
    endDate: '18/09/2026',
    budgetRemainingCents: 610000
  },
  {
    id: 'MON-META-005',
    campaignName: 'Virada de Lote — Urgência & Remarketing Checkout',
    channel: 'META',
    eventName: 'TOQUINHO • 60 Anos de Carreira',
    eventId: 3,
    externalCampaignId: 'act_492019482_camp_9944',
    platformCampaignStatus: 'ACTIVE',
    platformAdSetStatus: 'PAUSED',
    platformAdStatus: 'ACTIVE',
    platformStatusLabelPtBr: 'Ad Set Pausado',
    deliveryStatus: 'ACTIVE_NO_DELIVERY',
    deliveryMeta: DELIVERY_STATUS_DICTIONARY.ACTIVE_NO_DELIVERY,
    impressionsLast6h: 0,
    clicksLast6h: 0,
    spendLast6hCents: 0,
    lastTelemetryAt: 'há 1 dia',
    lastSyncAt: 'há 15 min',
    issueReason: 'Inconsistência de veiculação: a campanha está marcada como Ativa no Meta Ads, mas o Grupo de Anúncios (Ad Set) correspondente foi pausado.',
    alerts: [{ level: 'CRITICAL', message: 'Ad Set pausado no Meta Ads enquanto a campanha está ativa.', suggestion: 'Ative o conjunto de anúncios no Meta Ads Manager.' }],
    totalSpentCents: 560000,
    totalRevenueCents: 3608000,
    totalConversions: 164,
    roas: 6.44,
    startDate: '18/08/2026',
    endDate: '29/08/2026',
    budgetRemainingCents: 290000
  },
  {
    id: 'MON-META-007',
    campaignName: 'Reels Virais — Teaser Lineup & Pista Premium',
    channel: 'META',
    eventName: 'FESTIVAL CURITIBA 2026',
    eventId: 1,
    externalCampaignId: 'act_492019482_camp_9951',
    platformCampaignStatus: 'ACTIVE',
    platformAdSetStatus: 'ACTIVE',
    platformAdStatus: 'ACTIVE',
    platformStatusLabelPtBr: 'Ativa',
    deliveryStatus: 'ACTIVE_DELIVERING',
    deliveryMeta: DELIVERY_STATUS_DICTIONARY.ACTIVE_DELIVERING,
    impressionsLast6h: 11200,
    clicksLast6h: 530,
    spendLast6hCents: 31000,
    lastTelemetryAt: 'há 10 min',
    lastSyncAt: 'há 10 min',
    alerts: [{ level: 'INFO', message: 'Veiculação contínua nos posicionamentos Instagram Reels.' }],
    totalSpentCents: 890000,
    totalRevenueCents: 4980000,
    totalConversions: 215,
    roas: 5.59,
    startDate: '12/08/2026',
    endDate: '22/09/2026',
    budgetRemainingCents: 450000
  },
  {
    id: 'MON-META-008',
    campaignName: 'Instagram Stories — Contagem Regressiva Lote Promocional',
    channel: 'META',
    eventName: 'MARCOS & BELUTTI • Tour 18 Anos',
    eventId: 1,
    externalCampaignId: 'act_492019482_camp_9952',
    platformCampaignStatus: 'ACTIVE',
    platformAdSetStatus: 'ACTIVE',
    platformAdStatus: 'ACTIVE',
    platformStatusLabelPtBr: 'Ativa',
    deliveryStatus: 'ACTIVE_DELIVERING',
    deliveryMeta: DELIVERY_STATUS_DICTIONARY.ACTIVE_DELIVERING,
    impressionsLast6h: 8900,
    clicksLast6h: 410,
    spendLast6hCents: 24000,
    lastTelemetryAt: 'há 12 min',
    lastSyncAt: 'há 12 min',
    alerts: [{ level: 'INFO', message: 'Stories com adesivo de link gerando CTR de 4,2%.' }],
    totalSpentCents: 620000,
    totalRevenueCents: 3410000,
    totalConversions: 155,
    roas: 5.5,
    startDate: '15/08/2026',
    endDate: '20/09/2026',
    budgetRemainingCents: 380000
  },
  {
    id: 'MON-META-009',
    campaignName: 'Público Lookalike Compradores Históricos 1% — Paraná',
    channel: 'META',
    eventName: 'FESTIVAL CURITIBA 2026',
    eventId: 1,
    externalCampaignId: 'act_492019482_camp_9953',
    platformCampaignStatus: 'ACTIVE',
    platformAdSetStatus: 'ACTIVE',
    platformAdStatus: 'ACTIVE',
    platformStatusLabelPtBr: 'Ativa',
    deliveryStatus: 'ACTIVE_DELIVERING',
    deliveryMeta: DELIVERY_STATUS_DICTIONARY.ACTIVE_DELIVERING,
    impressionsLast6h: 9600,
    clicksLast6h: 460,
    spendLast6hCents: 28000,
    lastTelemetryAt: 'há 15 min',
    lastSyncAt: 'há 15 min',
    alerts: [{ level: 'INFO', message: 'Segmentação LAL 1% com conversão estável de 4,8%.' }],
    totalSpentCents: 740000,
    totalRevenueCents: 4120000,
    totalConversions: 180,
    roas: 5.56,
    startDate: '14/08/2026',
    endDate: '24/09/2026',
    budgetRemainingCents: 520000
  },
  {
    id: 'MON-META-010',
    campaignName: 'Carrossel Lineup Atrações — Instagram Feed',
    channel: 'META',
    eventName: 'FESTIVAL CURITIBA 2026',
    eventId: 1,
    externalCampaignId: 'act_492019482_camp_9954',
    platformCampaignStatus: 'ACTIVE',
    platformAdSetStatus: 'ACTIVE',
    platformAdStatus: 'ACTIVE',
    platformStatusLabelPtBr: 'Ativa',
    deliveryStatus: 'ACTIVE_DELIVERING',
    deliveryMeta: DELIVERY_STATUS_DICTIONARY.ACTIVE_DELIVERING,
    impressionsLast6h: 7800,
    clicksLast6h: 380,
    spendLast6hCents: 21000,
    lastTelemetryAt: 'há 20 min',
    lastSyncAt: 'há 20 min',
    alerts: [{ level: 'INFO', message: 'Engajamento acima da média no carrossel de 6 cards.' }],
    totalSpentCents: 580000,
    totalRevenueCents: 3190000,
    totalConversions: 142,
    roas: 5.5,
    startDate: '16/08/2026',
    endDate: '22/09/2026',
    budgetRemainingCents: 320000
  },
  {
    id: 'MON-META-011',
    campaignName: 'Remarketing Abandonadores de Carrinho (3 Dias)',
    channel: 'META',
    eventName: 'MATEUS ASATO • World Tour 2026',
    eventId: 5,
    externalCampaignId: 'act_492019482_camp_9955',
    platformCampaignStatus: 'ACTIVE',
    platformAdSetStatus: 'ACTIVE',
    platformAdStatus: 'ACTIVE',
    platformStatusLabelPtBr: 'Ativa',
    deliveryStatus: 'ACTIVE_DELIVERING',
    deliveryMeta: DELIVERY_STATUS_DICTIONARY.ACTIVE_DELIVERING,
    impressionsLast6h: 4200,
    clicksLast6h: 210,
    spendLast6hCents: 16000,
    lastTelemetryAt: 'há 14 min',
    lastSyncAt: 'há 14 min',
    alerts: [{ level: 'INFO', message: 'Público quente de carrinho com ROAS de 7.8x.' }],
    totalSpentCents: 390000,
    totalRevenueCents: 3042000,
    totalConversions: 135,
    roas: 7.8,
    startDate: '18/08/2026',
    endDate: '25/09/2026',
    budgetRemainingCents: 280000
  },
  {
    id: 'MON-META-012',
    campaignName: 'Campanha de Alcance Geográfico — Região Metropolitana de Curitiba',
    channel: 'META',
    eventName: 'TOQUINHO • 60 Anos de Carreira',
    eventId: 3,
    externalCampaignId: 'act_492019482_camp_9956',
    platformCampaignStatus: 'ACTIVE',
    platformAdSetStatus: 'ACTIVE',
    platformAdStatus: 'ACTIVE',
    platformStatusLabelPtBr: 'Ativa',
    deliveryStatus: 'ACTIVE_DELIVERING',
    deliveryMeta: DELIVERY_STATUS_DICTIONARY.ACTIVE_DELIVERING,
    impressionsLast6h: 6500,
    clicksLast6h: 290,
    spendLast6hCents: 19000,
    lastTelemetryAt: 'há 22 min',
    lastSyncAt: 'há 22 min',
    alerts: [{ level: 'INFO', message: 'Frequência média de 1,3 impressões por usuário único.' }],
    totalSpentCents: 480000,
    totalRevenueCents: 2640000,
    totalConversions: 118,
    roas: 5.5,
    startDate: '15/08/2026',
    endDate: '28/09/2026',
    budgetRemainingCents: 310000
  },
  {
    id: 'MON-META-013',
    campaignName: 'Facebook Feed & Marketplace — Venda Rápida de Ingressos',
    channel: 'META',
    eventName: 'ED MOTTA • Manual Prático 30 Anos',
    eventId: 2,
    externalCampaignId: 'act_492019482_camp_9957',
    platformCampaignStatus: 'ACTIVE',
    platformAdSetStatus: 'ACTIVE',
    platformAdStatus: 'ACTIVE',
    platformStatusLabelPtBr: 'Ativa',
    deliveryStatus: 'ACTIVE_DELIVERING',
    deliveryMeta: DELIVERY_STATUS_DICTIONARY.ACTIVE_DELIVERING,
    impressionsLast6h: 5300,
    clicksLast6h: 240,
    spendLast6hCents: 15000,
    lastTelemetryAt: 'há 18 min',
    lastSyncAt: 'há 18 min',
    alerts: [{ level: 'INFO', message: 'Veiculação padrão no ecossistema Facebook.' }],
    totalSpentCents: 410000,
    totalRevenueCents: 2296000,
    totalConversions: 104,
    roas: 5.6,
    startDate: '12/08/2026',
    endDate: '26/09/2026',
    budgetRemainingCents: 290000
  },
  {
    id: 'MON-META-014',
    campaignName: 'Instagram Stories VIP — Camarote Open Bar & Mesas',
    channel: 'META',
    eventName: 'FESTIVAL CURITIBA 2026',
    eventId: 1,
    externalCampaignId: 'act_492019482_camp_9958',
    platformCampaignStatus: 'ACTIVE',
    platformAdSetStatus: 'ACTIVE',
    platformAdStatus: 'ACTIVE',
    platformStatusLabelPtBr: 'Ativa',
    deliveryStatus: 'ACTIVE_DELIVERING',
    deliveryMeta: DELIVERY_STATUS_DICTIONARY.ACTIVE_DELIVERING,
    impressionsLast6h: 4900,
    clicksLast6h: 220,
    spendLast6hCents: 18000,
    lastTelemetryAt: 'há 25 min',
    lastSyncAt: 'há 25 min',
    alerts: [{ level: 'INFO', message: 'Ticket médio elevado em ingressos de camarote.' }],
    totalSpentCents: 520000,
    totalRevenueCents: 3640000,
    totalConversions: 88,
    roas: 7.0,
    startDate: '14/08/2026',
    endDate: '24/09/2026',
    budgetRemainingCents: 380000
  },
  {
    id: 'MON-META-015',
    campaignName: 'Campanha de Engajamento — Compartilhe e Ganhe Copo Oficial',
    channel: 'META',
    eventName: 'FESTIVAL CURITIBA 2026',
    eventId: 1,
    externalCampaignId: 'act_492019482_camp_9959',
    platformCampaignStatus: 'ACTIVE',
    platformAdSetStatus: 'ACTIVE',
    platformAdStatus: 'ACTIVE',
    platformStatusLabelPtBr: 'Ativa',
    deliveryStatus: 'ACTIVE_DELIVERING',
    deliveryMeta: DELIVERY_STATUS_DICTIONARY.ACTIVE_DELIVERING,
    impressionsLast6h: 6800,
    clicksLast6h: 310,
    spendLast6hCents: 17000,
    lastTelemetryAt: 'há 30 min',
    lastSyncAt: 'há 30 min',
    alerts: [{ level: 'INFO', message: 'Viralidade orgânica impulsionada por comentários.' }],
    totalSpentCents: 380000,
    totalRevenueCents: 1976000,
    totalConversions: 92,
    roas: 5.2,
    startDate: '16/08/2026',
    endDate: '20/09/2026',
    budgetRemainingCents: 210000
  },
  {
    id: 'MON-META-016',
    campaignName: 'Vídeo Depoimentos — Edição Anterior & Experiência',
    channel: 'META',
    eventName: 'FESTIVAL CURITIBA 2026',
    eventId: 1,
    externalCampaignId: 'act_492019482_camp_9960',
    platformCampaignStatus: 'ACTIVE',
    platformAdSetStatus: 'ACTIVE',
    platformAdStatus: 'ACTIVE',
    platformStatusLabelPtBr: 'Ativa',
    deliveryStatus: 'ACTIVE_DELIVERING',
    deliveryMeta: DELIVERY_STATUS_DICTIONARY.ACTIVE_DELIVERING,
    impressionsLast6h: 5100,
    clicksLast6h: 230,
    spendLast6hCents: 14000,
    lastTelemetryAt: 'há 35 min',
    lastSyncAt: 'há 35 min',
    alerts: [{ level: 'INFO', message: 'Retenção de vídeo de 68% até 15s.' }],
    totalSpentCents: 340000,
    totalRevenueCents: 1870000,
    totalConversions: 84,
    roas: 5.5,
    startDate: '15/08/2026',
    endDate: '21/09/2026',
    budgetRemainingCents: 260000
  },
  {
    id: 'MON-META-018',
    campaignName: 'Público Lookalike 2% — Região Sul sem Impressões',
    channel: 'META',
    eventName: 'FESTIVAL CURITIBA 2026',
    eventId: 1,
    externalCampaignId: 'act_492019482_camp_9962',
    platformCampaignStatus: 'ACTIVE',
    platformAdSetStatus: 'ACTIVE',
    platformAdStatus: 'ACTIVE',
    platformStatusLabelPtBr: 'Ativa',
    deliveryStatus: 'ACTIVE_NO_DELIVERY',
    deliveryMeta: DELIVERY_STATUS_DICTIONARY.ACTIVE_NO_DELIVERY,
    impressionsLast6h: 0,
    clicksLast6h: 0,
    spendLast6hCents: 0,
    lastTelemetryAt: 'há 18h',
    lastSyncAt: 'há 18 min',
    issueReason: 'Lance máximo manual por resultado definido abaixo da média atual do leilão em Curitiba.',
    alerts: [{ level: 'WARNING', message: 'Lance abaixo da concorrência no Meta Ads.', suggestion: 'Altere a estratégia para Menor Custo ou aumente o limite de lance.' }],
    totalSpentCents: 120000,
    totalRevenueCents: 660000,
    totalConversions: 30,
    roas: 5.5,
    startDate: '10/08/2026',
    endDate: '18/09/2026',
    budgetRemainingCents: 380000
  },
  {
    id: 'MON-META-019',
    campaignName: 'Anúncio Novo — Virada de Lote Stories (Vídeo 9:16)',
    channel: 'META',
    eventName: 'FESTIVAL CURITIBA 2026',
    eventId: 1,
    externalCampaignId: 'act_492019482_camp_9963',
    platformCampaignStatus: 'ACTIVE',
    platformAdSetStatus: 'ACTIVE',
    platformAdStatus: 'PENDING_REVIEW',
    platformStatusLabelPtBr: 'Em análise',
    deliveryStatus: 'PENDING_REVIEW',
    deliveryMeta: DELIVERY_STATUS_DICTIONARY.PENDING_REVIEW,
    impressionsLast6h: 0,
    clicksLast6h: 0,
    spendLast6hCents: 0,
    lastTelemetryAt: 'Nunca entregou',
    lastSyncAt: 'há 25 min',
    issueReason: 'Criativo submetido há 40 minutos aguardando revisão da IA de moderação do Meta Ads.',
    alerts: [{ level: 'INFO', message: 'Anúncio na fila de moderação do Meta Ads.' }],
    totalSpentCents: 0,
    totalRevenueCents: 0,
    totalConversions: 0,
    roas: 0,
    startDate: '11/09/2026',
    endDate: '20/09/2026',
    budgetRemainingCents: 300000
  },
  {
    id: 'MON-META-020',
    campaignName: 'Criativo Carrossel Artistas Convidados — Feed',
    channel: 'META',
    eventName: 'TOQUINHO • 60 Anos de Carreira',
    eventId: 3,
    externalCampaignId: 'act_492019482_camp_9964',
    platformCampaignStatus: 'ACTIVE',
    platformAdSetStatus: 'ACTIVE',
    platformAdStatus: 'PENDING_REVIEW',
    platformStatusLabelPtBr: 'Em análise',
    deliveryStatus: 'PENDING_REVIEW',
    deliveryMeta: DELIVERY_STATUS_DICTIONARY.PENDING_REVIEW,
    impressionsLast6h: 0,
    clicksLast6h: 0,
    spendLast6hCents: 0,
    lastTelemetryAt: 'Nunca entregou',
    lastSyncAt: 'há 30 min',
    issueReason: 'Carrossel em análise padrão pelo time de moderação de publicidade.',
    alerts: [{ level: 'INFO', message: 'Aguardando validação algorítmica.' }],
    totalSpentCents: 0,
    totalRevenueCents: 0,
    totalConversions: 0,
    roas: 0,
    startDate: '11/09/2026',
    endDate: '28/09/2026',
    budgetRemainingCents: 250000
  },
  {
    id: 'MON-META-021',
    campaignName: 'Banner Promocional — Desconto Estudante 50%',
    channel: 'META',
    eventName: 'FESTIVAL CURITIBA 2026',
    eventId: 1,
    externalCampaignId: 'act_492019482_camp_9965',
    platformCampaignStatus: 'ACTIVE',
    platformAdSetStatus: 'ACTIVE',
    platformAdStatus: 'DISAPPROVED',
    platformStatusLabelPtBr: 'Anúncio Reprovado',
    deliveryStatus: 'REJECTED',
    deliveryMeta: DELIVERY_STATUS_DICTIONARY.REJECTED,
    impressionsLast6h: 0,
    clicksLast6h: 0,
    spendLast6hCents: 0,
    lastTelemetryAt: 'Nunca entregou',
    lastSyncAt: 'há 45 min',
    issueReason: 'Anúncio reprovado por alegação de promessa enganosa no criativo (Palavras como "Desconto Impossível").',
    alerts: [{ level: 'CRITICAL', message: 'Anúncio reprovado pela política comercial do Meta Ads.', suggestion: 'Edite o texto do criativo e envie para reanálise.' }],
    totalSpentCents: 0,
    totalRevenueCents: 0,
    totalConversions: 0,
    roas: 0,
    startDate: '10/09/2026',
    endDate: '18/09/2026',
    budgetRemainingCents: 150000
  },
  {
    id: 'MON-META-022',
    campaignName: 'Vídeo Teaser com Marca de Água Não Autorizada',
    channel: 'META',
    eventName: 'MARCOS & BELUTTI • Tour 18 Anos',
    eventId: 1,
    externalCampaignId: 'act_492019482_camp_9966',
    platformCampaignStatus: 'ACTIVE',
    platformAdSetStatus: 'ACTIVE',
    platformAdStatus: 'DISAPPROVED',
    platformStatusLabelPtBr: 'Anúncio Reprovado',
    deliveryStatus: 'REJECTED',
    deliveryMeta: DELIVERY_STATUS_DICTIONARY.REJECTED,
    impressionsLast6h: 0,
    clicksLast6h: 0,
    spendLast6hCents: 0,
    lastTelemetryAt: 'Nunca entregou',
    lastSyncAt: 'há 50 min',
    issueReason: 'Direitos de imagem ou logotipo de patrocinador sinalizado pelo sistema de direitos autorais do Meta.',
    alerts: [{ level: 'CRITICAL', message: 'Violação de direitos de marca sinalizada.', suggestion: 'Remova logotipos de terceiros ou adicione comprovação de permissão.' }],
    totalSpentCents: 0,
    totalRevenueCents: 0,
    totalConversions: 0,
    roas: 0,
    startDate: '09/09/2026',
    endDate: '19/09/2026',
    budgetRemainingCents: 200000
  },

  // ===================== GOOGLE ADS (12 campanhas: 8 Entregando, 2 Sem entrega, 1 Análise, 1 Rejeitada) =====================
  {
    id: 'MON-GOOGLE-002',
    campaignName: 'Pesquisa Ingressos — Rede de Pesquisa & Discovery',
    channel: 'GOOGLE',
    eventName: 'MATEUS ASATO • World Tour 2026',
    eventId: 5,
    externalCampaignId: 'gads_88294710_camp_334',
    platformCampaignStatus: 'ENABLED',
    platformAdSetStatus: 'ENABLED',
    platformAdStatus: 'ELIGIBLE',
    platformStatusLabelPtBr: 'Ativa',
    deliveryStatus: 'ACTIVE_NO_DELIVERY',
    deliveryMeta: DELIVERY_STATUS_DICTIONARY.ACTIVE_NO_DELIVERY,
    impressionsLast6h: 0,
    clicksLast6h: 0,
    spendLast6hCents: 0,
    lastTelemetryAt: 'há 18h',
    lastSyncAt: 'há 12 min',
    issueReason: 'Sem impressões nas últimas 6 horas. O lance de CPC pode estar abaixo do mínimo do leilão ou orçamento diário esgotado.',
    alerts: [{ level: 'WARNING', message: 'Campanha ativa no Google Ads, mas sem impressões nas últimas 6 horas.', suggestion: 'Ajuste a estratégia de lances (Target CPA).' }],
    totalSpentCents: 310000,
    totalRevenueCents: 1716000,
    totalConversions: 78,
    roas: 5.53,
    startDate: '12/08/2026',
    endDate: '15/09/2026',
    budgetRemainingCents: 210000
  },
  {
    id: 'MON-GOOGLE-006',
    campaignName: 'Google Display — Banners Retargeting Visitantes',
    channel: 'GOOGLE',
    eventName: 'ED MOTTA • Manual Prático 30 Anos',
    eventId: 2,
    externalCampaignId: 'gads_88294710_camp_778',
    platformCampaignStatus: 'ENABLED',
    platformAdSetStatus: 'ENABLED',
    platformAdStatus: 'DISAPPROVED',
    platformStatusLabelPtBr: 'Criativo Reprovado',
    deliveryStatus: 'REJECTED',
    deliveryMeta: DELIVERY_STATUS_DICTIONARY.REJECTED,
    impressionsLast6h: 0,
    clicksLast6h: 0,
    spendLast6hCents: 0,
    lastTelemetryAt: 'Nunca entregou',
    lastSyncAt: 'há 32 min',
    issueReason: 'O banner 300x250 foi reprovado pela política de publicidade do Google Ads devido à presença de texto em proporção excessiva sobre a arte.',
    alerts: [{ level: 'CRITICAL', message: 'Anúncio reprovado na moderação do Google Ads.', suggestion: 'Substitua a imagem por versão com menor proporção de texto.' }],
    totalSpentCents: 0,
    totalRevenueCents: 0,
    totalConversions: 0,
    roas: 0,
    startDate: '15/08/2026',
    endDate: '29/08/2026',
    budgetRemainingCents: 140000
  },
  {
    id: 'MON-GOOGLE-023',
    campaignName: 'Google Search Institucional — "Festival Curitiba Ingressos"',
    channel: 'GOOGLE',
    eventName: 'FESTIVAL CURITIBA 2026',
    eventId: 1,
    externalCampaignId: 'gads_88294710_camp_801',
    platformCampaignStatus: 'ENABLED',
    platformAdSetStatus: 'ENABLED',
    platformAdStatus: 'ELIGIBLE',
    platformStatusLabelPtBr: 'Ativa',
    deliveryStatus: 'ACTIVE_DELIVERING',
    deliveryMeta: DELIVERY_STATUS_DICTIONARY.ACTIVE_DELIVERING,
    impressionsLast6h: 9400,
    clicksLast6h: 720,
    spendLast6hCents: 41000,
    lastTelemetryAt: 'há 6 min',
    lastSyncAt: 'há 6 min',
    alerts: [{ level: 'INFO', message: 'Índice de qualidade 9/10 nas palavras-chave principais.' }],
    totalSpentCents: 980000,
    totalRevenueCents: 6860000,
    totalConversions: 310,
    roas: 7.0,
    startDate: '08/08/2026',
    endDate: '25/09/2026',
    budgetRemainingCents: 620000
  },
  {
    id: 'MON-GOOGLE-024',
    campaignName: 'Google Performance Max (PMax) — Aquisição Multicanal',
    channel: 'GOOGLE',
    eventName: 'FESTIVAL CURITIBA 2026',
    eventId: 1,
    externalCampaignId: 'gads_88294710_camp_802',
    platformCampaignStatus: 'ENABLED',
    platformAdSetStatus: 'ENABLED',
    platformAdStatus: 'ELIGIBLE',
    platformStatusLabelPtBr: 'Ativa',
    deliveryStatus: 'ACTIVE_DELIVERING',
    deliveryMeta: DELIVERY_STATUS_DICTIONARY.ACTIVE_DELIVERING,
    impressionsLast6h: 12500,
    clicksLast6h: 580,
    spendLast6hCents: 37000,
    lastTelemetryAt: 'há 9 min',
    lastSyncAt: 'há 9 min',
    alerts: [{ level: 'INFO', message: 'Veiculação equilibrada entre YouTube, Gmail e Search.' }],
    totalSpentCents: 850000,
    totalRevenueCents: 5100000,
    totalConversions: 240,
    roas: 6.0,
    startDate: '10/08/2026',
    endDate: '26/09/2026',
    budgetRemainingCents: 540000
  },
  {
    id: 'MON-GOOGLE-025',
    campaignName: 'YouTube Ads — Clipe Oficial e Teaser 15s In-Stream',
    channel: 'GOOGLE',
    eventName: 'FESTIVAL CURITIBA 2026',
    eventId: 1,
    externalCampaignId: 'gads_88294710_camp_803',
    platformCampaignStatus: 'ENABLED',
    platformAdSetStatus: 'ENABLED',
    platformAdStatus: 'ELIGIBLE',
    platformStatusLabelPtBr: 'Ativa',
    deliveryStatus: 'ACTIVE_DELIVERING',
    deliveryMeta: DELIVERY_STATUS_DICTIONARY.ACTIVE_DELIVERING,
    impressionsLast6h: 15400,
    clicksLast6h: 390,
    spendLast6hCents: 29000,
    lastTelemetryAt: 'há 11 min',
    lastSyncAt: 'há 11 min',
    alerts: [{ level: 'INFO', message: 'Visualizações de vídeo completas acima de 72%.' }],
    totalSpentCents: 710000,
    totalRevenueCents: 3905000,
    totalConversions: 175,
    roas: 5.5,
    startDate: '14/08/2026',
    endDate: '24/09/2026',
    budgetRemainingCents: 430000
  },
  {
    id: 'MON-GOOGLE-026',
    campaignName: 'Google Search — Palavras de Concorrência & Festivais PR',
    channel: 'GOOGLE',
    eventName: 'FESTIVAL CURITIBA 2026',
    eventId: 1,
    externalCampaignId: 'gads_88294710_camp_804',
    platformCampaignStatus: 'ENABLED',
    platformAdSetStatus: 'ENABLED',
    platformAdStatus: 'ELIGIBLE',
    platformStatusLabelPtBr: 'Ativa',
    deliveryStatus: 'ACTIVE_DELIVERING',
    deliveryMeta: DELIVERY_STATUS_DICTIONARY.ACTIVE_DELIVERING,
    impressionsLast6h: 6200,
    clicksLast6h: 310,
    spendLast6hCents: 22000,
    lastTelemetryAt: 'há 16 min',
    lastSyncAt: 'há 16 min',
    alerts: [{ level: 'INFO', message: 'Captura de tráfego qualificado de termos genéricos.' }],
    totalSpentCents: 490000,
    totalRevenueCents: 2695000,
    totalConversions: 120,
    roas: 5.5,
    startDate: '15/08/2026',
    endDate: '22/09/2026',
    budgetRemainingCents: 310000
  },
  {
    id: 'MON-GOOGLE-027',
    campaignName: 'Google Display — Banners Responsivos Redes Afiliadas',
    channel: 'GOOGLE',
    eventName: 'MARCOS & BELUTTI • Tour 18 Anos',
    eventId: 1,
    externalCampaignId: 'gads_88294710_camp_805',
    platformCampaignStatus: 'ENABLED',
    platformAdSetStatus: 'ENABLED',
    platformAdStatus: 'ELIGIBLE',
    platformStatusLabelPtBr: 'Ativa',
    deliveryStatus: 'ACTIVE_DELIVERING',
    deliveryMeta: DELIVERY_STATUS_DICTIONARY.ACTIVE_DELIVERING,
    impressionsLast6h: 8100,
    clicksLast6h: 260,
    spendLast6hCents: 18000,
    lastTelemetryAt: 'há 19 min',
    lastSyncAt: 'há 19 min',
    alerts: [{ level: 'INFO', message: 'Alta cobertura em portais de notícias de Curitiba.' }],
    totalSpentCents: 430000,
    totalRevenueCents: 2365000,
    totalConversions: 110,
    roas: 5.5,
    startDate: '12/08/2026',
    endDate: '21/09/2026',
    budgetRemainingCents: 290000
  },
  {
    id: 'MON-GOOGLE-028',
    campaignName: 'Google Search — Show Toquinho Teatro Positivo Ingressos',
    channel: 'GOOGLE',
    eventName: 'TOQUINHO • 60 Anos de Carreira',
    eventId: 3,
    externalCampaignId: 'gads_88294710_camp_806',
    platformCampaignStatus: 'ENABLED',
    platformAdSetStatus: 'ENABLED',
    platformAdStatus: 'ELIGIBLE',
    platformStatusLabelPtBr: 'Ativa',
    deliveryStatus: 'ACTIVE_DELIVERING',
    deliveryMeta: DELIVERY_STATUS_DICTIONARY.ACTIVE_DELIVERING,
    impressionsLast6h: 4700,
    clicksLast6h: 320,
    spendLast6hCents: 21000,
    lastTelemetryAt: 'há 14 min',
    lastSyncAt: 'há 14 min',
    alerts: [{ level: 'INFO', message: 'Primeira posição no Google para o nome do artista.' }],
    totalSpentCents: 520000,
    totalRevenueCents: 3640000,
    totalConversions: 140,
    roas: 7.0,
    startDate: '14/08/2026',
    endDate: '29/09/2026',
    budgetRemainingCents: 340000
  },
  {
    id: 'MON-GOOGLE-029',
    campaignName: 'YouTube Shorts Ads — Solos Marcantes Mateus Asato',
    channel: 'GOOGLE',
    eventName: 'MATEUS ASATO • World Tour 2026',
    eventId: 5,
    externalCampaignId: 'gads_88294710_camp_807',
    platformCampaignStatus: 'ENABLED',
    platformAdSetStatus: 'ENABLED',
    platformAdStatus: 'ELIGIBLE',
    platformStatusLabelPtBr: 'Ativa',
    deliveryStatus: 'ACTIVE_DELIVERING',
    deliveryMeta: DELIVERY_STATUS_DICTIONARY.ACTIVE_DELIVERING,
    impressionsLast6h: 7400,
    clicksLast6h: 290,
    spendLast6hCents: 19000,
    lastTelemetryAt: 'há 21 min',
    lastSyncAt: 'há 21 min',
    alerts: [{ level: 'INFO', message: 'Engajamento elevado de público nichado em música.' }],
    totalSpentCents: 390000,
    totalRevenueCents: 2145000,
    totalConversions: 95,
    roas: 5.5,
    startDate: '16/08/2026',
    endDate: '27/09/2026',
    budgetRemainingCents: 280000
  },
  {
    id: 'MON-GOOGLE-030',
    campaignName: 'Google Discovery Ads — Carrossel Mobile DiskIngressos',
    channel: 'GOOGLE',
    eventName: 'ED MOTTA • Manual Prático 30 Anos',
    eventId: 2,
    externalCampaignId: 'gads_88294710_camp_808',
    platformCampaignStatus: 'ENABLED',
    platformAdSetStatus: 'ENABLED',
    platformAdStatus: 'ELIGIBLE',
    platformStatusLabelPtBr: 'Ativa',
    deliveryStatus: 'ACTIVE_DELIVERING',
    deliveryMeta: DELIVERY_STATUS_DICTIONARY.ACTIVE_DELIVERING,
    impressionsLast6h: 5800,
    clicksLast6h: 210,
    spendLast6hCents: 15000,
    lastTelemetryAt: 'há 26 min',
    lastSyncAt: 'há 26 min',
    alerts: [{ level: 'INFO', message: 'Exibição fluida no feed Discover do Google Android.' }],
    totalSpentCents: 360000,
    totalRevenueCents: 1980000,
    totalConversions: 88,
    roas: 5.5,
    startDate: '15/08/2026',
    endDate: '25/09/2026',
    budgetRemainingCents: 240000
  },
  {
    id: 'MON-GOOGLE-031',
    campaignName: 'Google Search Remarketing — Visitantes Sem Compra 7D',
    channel: 'GOOGLE',
    eventName: 'FESTIVAL CURITIBA 2026',
    eventId: 1,
    externalCampaignId: 'gads_88294710_camp_809',
    platformCampaignStatus: 'ENABLED',
    platformAdSetStatus: 'ENABLED',
    platformAdStatus: 'ELIGIBLE',
    platformStatusLabelPtBr: 'Ativa',
    deliveryStatus: 'ACTIVE_NO_DELIVERY',
    deliveryMeta: DELIVERY_STATUS_DICTIONARY.ACTIVE_NO_DELIVERY,
    impressionsLast6h: 0,
    clicksLast6h: 0,
    spendLast6hCents: 0,
    lastTelemetryAt: 'há 12h',
    lastSyncAt: 'há 22 min',
    issueReason: 'Tamanho de lista de público RLSA com menos de 1.000 usuários ativos nos últimos 7 dias.',
    alerts: [{ level: 'WARNING', message: 'Lista RLSA abaixo do limite mínimo do Google Search.', suggestion: 'Amplie a janela da lista para 30 ou 60 dias.' }],
    totalSpentCents: 85000,
    totalRevenueCents: 425000,
    totalConversions: 20,
    roas: 5.0,
    startDate: '12/08/2026',
    endDate: '20/09/2026',
    budgetRemainingCents: 190000
  },
  {
    id: 'MON-GOOGLE-032',
    campaignName: 'Google PMax Novo Vídeo 16:9 — Formato Paisagem YouTube',
    channel: 'GOOGLE',
    eventName: 'FESTIVAL CURITIBA 2026',
    eventId: 1,
    externalCampaignId: 'gads_88294710_camp_810',
    platformCampaignStatus: 'ENABLED',
    platformAdSetStatus: 'ENABLED',
    platformAdStatus: 'UNDER_REVIEW',
    platformStatusLabelPtBr: 'Em análise',
    deliveryStatus: 'PENDING_REVIEW',
    deliveryMeta: DELIVERY_STATUS_DICTIONARY.PENDING_REVIEW,
    impressionsLast6h: 0,
    clicksLast6h: 0,
    spendLast6hCents: 0,
    lastTelemetryAt: 'Nunca entregou',
    lastSyncAt: 'há 35 min',
    issueReason: 'Vídeo na fila de moderação de políticas de anunciante do Google Ads.',
    alerts: [{ level: 'INFO', message: 'Em análise de conformidade do Google.' }],
    totalSpentCents: 0,
    totalRevenueCents: 0,
    totalConversions: 0,
    roas: 0,
    startDate: '11/09/2026',
    endDate: '25/09/2026',
    budgetRemainingCents: 300000
  },

  // ===================== TIKTOK ADS (8 campanhas: 4 Entregando, 1 Sem entrega, 3 Análise, 0 Rejeitadas) =====================
  {
    id: 'MON-TIKTOK-003',
    campaignName: 'Viral Lineup — Spark Ads & Vídeos Curtos',
    channel: 'TIKTOK',
    eventName: 'FESTIVAL CURITIBA 2026',
    eventId: 1,
    externalCampaignId: 'tt_adv_582910_camp_118',
    platformCampaignStatus: 'OPERATION_STATUS_ENABLE',
    platformAdSetStatus: 'AUDIT_STATUS_PENDING',
    platformAdStatus: 'AUDIT_STATUS_PENDING',
    platformStatusLabelPtBr: 'Em análise',
    deliveryStatus: 'PENDING_REVIEW',
    deliveryMeta: DELIVERY_STATUS_DICTIONARY.PENDING_REVIEW,
    impressionsLast6h: 0,
    clicksLast6h: 0,
    spendLast6hCents: 0,
    lastTelemetryAt: 'Nunca entregou',
    lastSyncAt: 'há 20 min',
    issueReason: 'O criativo em vídeo foi submetido e está na fila de revisão automatizada e humana do TikTok Ads.',
    alerts: [{ level: 'INFO', message: 'Campanha aguardando aprovação dos moderadores do TikTok Ads.' }],
    totalSpentCents: 0,
    totalRevenueCents: 0,
    totalConversions: 0,
    roas: 0,
    startDate: '11/09/2026',
    endDate: '25/09/2026',
    budgetRemainingCents: 250000
  },
  {
    id: 'MON-TIKTOK-033',
    campaignName: 'TikTok Feed Ads — Tendências de Dança & Música Festival',
    channel: 'TIKTOK',
    eventName: 'FESTIVAL CURITIBA 2026',
    eventId: 1,
    externalCampaignId: 'tt_adv_582910_camp_120',
    platformCampaignStatus: 'OPERATION_STATUS_ENABLE',
    platformAdSetStatus: 'AUDIT_STATUS_APPROVED',
    platformAdStatus: 'AUDIT_STATUS_APPROVED',
    platformStatusLabelPtBr: 'Ativa',
    deliveryStatus: 'ACTIVE_DELIVERING',
    deliveryMeta: DELIVERY_STATUS_DICTIONARY.ACTIVE_DELIVERING,
    impressionsLast6h: 18200,
    clicksLast6h: 840,
    spendLast6hCents: 34000,
    lastTelemetryAt: 'há 7 min',
    lastSyncAt: 'há 7 min',
    alerts: [{ level: 'INFO', message: 'Alto engajamento com taxa de clique de 4,6% no feed For You.' }],
    totalSpentCents: 680000,
    totalRevenueCents: 3740000,
    totalConversions: 180,
    roas: 5.5,
    startDate: '10/08/2026',
    endDate: '22/09/2026',
    budgetRemainingCents: 410000
  },
  {
    id: 'MON-TIKTOK-034',
    campaignName: 'TikTok Spark Ads — Post Patrocinado com Influenciadora VIP',
    channel: 'TIKTOK',
    eventName: 'FESTIVAL CURITIBA 2026',
    eventId: 1,
    externalCampaignId: 'tt_adv_582910_camp_121',
    platformCampaignStatus: 'OPERATION_STATUS_ENABLE',
    platformAdSetStatus: 'AUDIT_STATUS_APPROVED',
    platformAdStatus: 'AUDIT_STATUS_APPROVED',
    platformStatusLabelPtBr: 'Ativa',
    deliveryStatus: 'ACTIVE_DELIVERING',
    deliveryMeta: DELIVERY_STATUS_DICTIONARY.ACTIVE_DELIVERING,
    impressionsLast6h: 14600,
    clicksLast6h: 620,
    spendLast6hCents: 28000,
    lastTelemetryAt: 'há 10 min',
    lastSyncAt: 'há 10 min',
    alerts: [{ level: 'INFO', message: 'Spark Ad com autorização de código ativo.' }],
    totalSpentCents: 540000,
    totalRevenueCents: 3240000,
    totalConversions: 150,
    roas: 6.0,
    startDate: '12/08/2026',
    endDate: '24/09/2026',
    budgetRemainingCents: 350000
  },
  {
    id: 'MON-TIKTOK-035',
    campaignName: 'TikTok Reach — Jovens 18-24 Anos Região Curitiba',
    channel: 'TIKTOK',
    eventName: 'FESTIVAL CURITIBA 2026',
    eventId: 1,
    externalCampaignId: 'tt_adv_582910_camp_122',
    platformCampaignStatus: 'OPERATION_STATUS_ENABLE',
    platformAdSetStatus: 'AUDIT_STATUS_APPROVED',
    platformAdStatus: 'AUDIT_STATUS_APPROVED',
    platformStatusLabelPtBr: 'Ativa',
    deliveryStatus: 'ACTIVE_DELIVERING',
    deliveryMeta: DELIVERY_STATUS_DICTIONARY.ACTIVE_DELIVERING,
    impressionsLast6h: 16100,
    clicksLast6h: 590,
    spendLast6hCents: 27000,
    lastTelemetryAt: 'há 15 min',
    lastSyncAt: 'há 15 min',
    alerts: [{ level: 'INFO', message: 'CPM competitivo de R$ 1,67.' }],
    totalSpentCents: 490000,
    totalRevenueCents: 2695000,
    totalConversions: 125,
    roas: 5.5,
    startDate: '14/08/2026',
    endDate: '23/09/2026',
    budgetRemainingCents: 310000
  },
  {
    id: 'MON-TIKTOK-036',
    campaignName: 'TikTok Vídeo Dueto — Desafio Musical Artistas',
    channel: 'TIKTOK',
    eventName: 'MARCOS & BELUTTI • Tour 18 Anos',
    eventId: 1,
    externalCampaignId: 'tt_adv_582910_camp_123',
    platformCampaignStatus: 'OPERATION_STATUS_ENABLE',
    platformAdSetStatus: 'AUDIT_STATUS_APPROVED',
    platformAdStatus: 'AUDIT_STATUS_APPROVED',
    platformStatusLabelPtBr: 'Ativa',
    deliveryStatus: 'ACTIVE_DELIVERING',
    deliveryMeta: DELIVERY_STATUS_DICTIONARY.ACTIVE_DELIVERING,
    impressionsLast6h: 11400,
    clicksLast6h: 480,
    spendLast6hCents: 21000,
    lastTelemetryAt: 'há 18 min',
    lastSyncAt: 'há 18 min',
    alerts: [{ level: 'INFO', message: 'Geração contínua de conteúdos gerados por usuários (UGC).' }],
    totalSpentCents: 410000,
    totalRevenueCents: 2255000,
    totalConversions: 105,
    roas: 5.5,
    startDate: '16/08/2026',
    endDate: '22/09/2026',
    budgetRemainingCents: 270000
  },
  {
    id: 'MON-TIKTOK-037',
    campaignName: 'TikTok Tráfego Direto — Saldo Pré-Pago Esgotado',
    channel: 'TIKTOK',
    eventName: 'FESTIVAL CURITIBA 2026',
    eventId: 1,
    externalCampaignId: 'tt_adv_582910_camp_124',
    platformCampaignStatus: 'OPERATION_STATUS_ENABLE',
    platformAdSetStatus: 'AUDIT_STATUS_APPROVED',
    platformAdStatus: 'AUDIT_STATUS_APPROVED',
    platformStatusLabelPtBr: 'Ativa',
    deliveryStatus: 'ACTIVE_NO_DELIVERY',
    deliveryMeta: DELIVERY_STATUS_DICTIONARY.ACTIVE_NO_DELIVERY,
    impressionsLast6h: 0,
    clicksLast6h: 0,
    spendLast6hCents: 0,
    lastTelemetryAt: 'há 10h',
    lastSyncAt: 'há 24 min',
    issueReason: 'O saldo da conta de anúncios TikTok Ads atingiu R$ 0,00 e a veiculação foi pausada pelo gateway.',
    alerts: [{ level: 'WARNING', message: 'Saldo da conta de anúncios esgotado.', suggestion: 'Adicione créditos à conta do TikTok Ads Business Manager.' }],
    totalSpentCents: 240000,
    totalRevenueCents: 1200000,
    totalConversions: 55,
    roas: 5.0,
    startDate: '10/08/2026',
    endDate: '18/09/2026',
    budgetRemainingCents: 0
  },
  {
    id: 'MON-TIKTOK-038',
    campaignName: 'Novo Spot Vertical 9:16 — Chamada Artistas em Moderação',
    channel: 'TIKTOK',
    eventName: 'FESTIVAL CURITIBA 2026',
    eventId: 1,
    externalCampaignId: 'tt_adv_582910_camp_125',
    platformCampaignStatus: 'OPERATION_STATUS_ENABLE',
    platformAdSetStatus: 'AUDIT_STATUS_PENDING',
    platformAdStatus: 'AUDIT_STATUS_PENDING',
    platformStatusLabelPtBr: 'Em análise',
    deliveryStatus: 'PENDING_REVIEW',
    deliveryMeta: DELIVERY_STATUS_DICTIONARY.PENDING_REVIEW,
    impressionsLast6h: 0,
    clicksLast6h: 0,
    spendLast6hCents: 0,
    lastTelemetryAt: 'Nunca entregou',
    lastSyncAt: 'há 28 min',
    issueReason: 'Submetido há 25 minutos; processo de checagem automatizada de áudio e imagem em andamento.',
    alerts: [{ level: 'INFO', message: 'Aguardando validação algorítmica do TikTok Ads.' }],
    totalSpentCents: 0,
    totalRevenueCents: 0,
    totalConversions: 0,
    roas: 0,
    startDate: '11/09/2026',
    endDate: '24/09/2026',
    budgetRemainingCents: 280000
  },
  {
    id: 'MON-TIKTOK-039',
    campaignName: 'Anúncio Específico — Últimos Camarotes Frontstage',
    channel: 'TIKTOK',
    eventName: 'FESTIVAL CURITIBA 2026',
    eventId: 1,
    externalCampaignId: 'tt_adv_582910_camp_126',
    platformCampaignStatus: 'OPERATION_STATUS_ENABLE',
    platformAdSetStatus: 'AUDIT_STATUS_PENDING',
    platformAdStatus: 'AUDIT_STATUS_PENDING',
    platformStatusLabelPtBr: 'Em análise',
    deliveryStatus: 'PENDING_REVIEW',
    deliveryMeta: DELIVERY_STATUS_DICTIONARY.PENDING_REVIEW,
    impressionsLast6h: 0,
    clicksLast6h: 0,
    spendLast6hCents: 0,
    lastTelemetryAt: 'Nunca entregou',
    lastSyncAt: 'há 32 min',
    issueReason: 'Criativo na esteira de aprovação.',
    alerts: [{ level: 'INFO', message: 'Fila de aprovação do TikTok.' }],
    totalSpentCents: 0,
    totalRevenueCents: 0,
    totalConversions: 0,
    roas: 0,
    startDate: '11/09/2026',
    endDate: '21/09/2026',
    budgetRemainingCents: 200000
  },

  // ===================== SPOTIFY ADS (10 campanhas: 7 Entregando, 1 Sem entrega, 1 Análise, 1 Rejeitada) =====================
  {
    id: 'MON-SPOTIFY-004',
    campaignName: 'Áudio Oficial Spotify — Marcos & Belutti 18 Anos',
    channel: 'SPOTIFY',
    eventName: 'MARCOS & BELUTTI • Tour 18 Anos',
    eventId: 1,
    externalCampaignId: 'sp_camp_892019482',
    platformCampaignStatus: 'ACTIVE',
    platformAdSetStatus: 'ACTIVE',
    platformAdStatus: 'APPROVED',
    platformStatusLabelPtBr: 'Ativa',
    deliveryStatus: 'ACTIVE_DELIVERING',
    deliveryMeta: DELIVERY_STATUS_DICTIONARY.ACTIVE_DELIVERING,
    impressionsLast6h: 8450,
    clicksLast6h: 312,
    spendLast6hCents: 26000,
    lastTelemetryAt: 'há 5 min',
    lastSyncAt: 'há 5 min',
    alerts: [{ level: 'INFO', message: 'Veiculação ativa no Spotify Free (Mobile e Desktop) com companion banner 640x640 sincronizado.' }],
    totalSpentCents: 340000,
    totalRevenueCents: 2180000,
    totalConversions: 94,
    roas: 6.41,
    startDate: '15/08/2026',
    endDate: '18/09/2026',
    budgetRemainingCents: 410000
  },
  {
    id: 'MON-SPOTIFY-040',
    campaignName: 'Spot de Áudio 30s — Festival Curitiba Lineup Sertanejo & Pop',
    channel: 'SPOTIFY',
    eventName: 'FESTIVAL CURITIBA 2026',
    eventId: 1,
    externalCampaignId: 'sp_camp_892019483',
    platformCampaignStatus: 'ACTIVE',
    platformAdSetStatus: 'ACTIVE',
    platformAdStatus: 'APPROVED',
    platformStatusLabelPtBr: 'Ativa',
    deliveryStatus: 'ACTIVE_DELIVERING',
    deliveryMeta: DELIVERY_STATUS_DICTIONARY.ACTIVE_DELIVERING,
    impressionsLast6h: 10200,
    clicksLast6h: 420,
    spendLast6hCents: 32000,
    lastTelemetryAt: 'há 8 min',
    lastSyncAt: 'há 8 min',
    alerts: [{ level: 'INFO', message: 'Spot de 30s com áudio masterizado e companion banner 640x640 ativo.' }],
    totalSpentCents: 580000,
    totalRevenueCents: 3480000,
    totalConversions: 160,
    roas: 6.0,
    startDate: '10/08/2026',
    endDate: '25/09/2026',
    budgetRemainingCents: 480000
  },
  {
    id: 'MON-SPOTIFY-041',
    campaignName: 'Segmentação Playlists MPB & Clássicos — Toquinho 60 Anos',
    channel: 'SPOTIFY',
    eventName: 'TOQUINHO • 60 Anos de Carreira',
    eventId: 3,
    externalCampaignId: 'sp_camp_892019484',
    platformCampaignStatus: 'ACTIVE',
    platformAdSetStatus: 'ACTIVE',
    platformAdStatus: 'APPROVED',
    platformStatusLabelPtBr: 'Ativa',
    deliveryStatus: 'ACTIVE_DELIVERING',
    deliveryMeta: DELIVERY_STATUS_DICTIONARY.ACTIVE_DELIVERING,
    impressionsLast6h: 6800,
    clicksLast6h: 290,
    spendLast6hCents: 21000,
    lastTelemetryAt: 'há 11 min',
    lastSyncAt: 'há 11 min',
    alerts: [{ level: 'INFO', message: 'Ouvintes de MPB e Bossa Nova em Curitiba com CTR de 4,3%.' }],
    totalSpentCents: 390000,
    totalRevenueCents: 2535000,
    totalConversions: 110,
    roas: 6.5,
    startDate: '14/08/2026',
    endDate: '28/09/2026',
    budgetRemainingCents: 320000
  },
  {
    id: 'MON-SPOTIFY-042',
    campaignName: 'Segmentação Artistas Similares Ed Motta — Soul & R&B Brasil',
    channel: 'SPOTIFY',
    eventName: 'ED MOTTA • Manual Prático 30 Anos',
    eventId: 2,
    externalCampaignId: 'sp_camp_892019485',
    platformCampaignStatus: 'ACTIVE',
    platformAdSetStatus: 'ACTIVE',
    platformAdStatus: 'APPROVED',
    platformStatusLabelPtBr: 'Ativa',
    deliveryStatus: 'ACTIVE_DELIVERING',
    deliveryMeta: DELIVERY_STATUS_DICTIONARY.ACTIVE_DELIVERING,
    impressionsLast6h: 5900,
    clicksLast6h: 240,
    spendLast6hCents: 18000,
    lastTelemetryAt: 'há 13 min',
    lastSyncAt: 'há 13 min',
    alerts: [{ level: 'INFO', message: 'Frequência de 1,2 exposições por ouvinte.' }],
    totalSpentCents: 340000,
    totalRevenueCents: 2040000,
    totalConversions: 92,
    roas: 6.0,
    startDate: '15/08/2026',
    endDate: '24/09/2026',
    budgetRemainingCents: 280000
  },
  {
    id: 'MON-SPOTIFY-043',
    campaignName: 'Segmentação Guitarristas & Instrumental — Mateus Asato World Tour',
    channel: 'SPOTIFY',
    eventName: 'MATEUS ASATO • World Tour 2026',
    eventId: 5,
    externalCampaignId: 'sp_camp_892019486',
    platformCampaignStatus: 'ACTIVE',
    platformAdSetStatus: 'ACTIVE',
    platformAdStatus: 'APPROVED',
    platformStatusLabelPtBr: 'Ativa',
    deliveryStatus: 'ACTIVE_DELIVERING',
    deliveryMeta: DELIVERY_STATUS_DICTIONARY.ACTIVE_DELIVERING,
    impressionsLast6h: 5200,
    clicksLast6h: 260,
    spendLast6hCents: 17000,
    lastTelemetryAt: 'há 16 min',
    lastSyncAt: 'há 16 min',
    alerts: [{ level: 'INFO', message: 'Taxa de conversão de cliques em compra de 18%.' }],
    totalSpentCents: 310000,
    totalRevenueCents: 2170000,
    totalConversions: 88,
    roas: 7.0,
    startDate: '16/08/2026',
    endDate: '27/09/2026',
    budgetRemainingCents: 260000
  },
  {
    id: 'MON-SPOTIFY-044',
    campaignName: 'Spotify Overlay Banner — Desktop & Web Player DiskIngressos',
    channel: 'SPOTIFY',
    eventName: 'FESTIVAL CURITIBA 2026',
    eventId: 1,
    externalCampaignId: 'sp_camp_892019487',
    platformCampaignStatus: 'ACTIVE',
    platformAdSetStatus: 'ACTIVE',
    platformAdStatus: 'APPROVED',
    platformStatusLabelPtBr: 'Ativa',
    deliveryStatus: 'ACTIVE_DELIVERING',
    deliveryMeta: DELIVERY_STATUS_DICTIONARY.ACTIVE_DELIVERING,
    impressionsLast6h: 7900,
    clicksLast6h: 310,
    spendLast6hCents: 22000,
    lastTelemetryAt: 'há 19 min',
    lastSyncAt: 'há 19 min',
    alerts: [{ level: 'INFO', message: 'Banner de rodapé com alta taxa de visibilidade no desktop.' }],
    totalSpentCents: 420000,
    totalRevenueCents: 2520000,
    totalConversions: 115,
    roas: 6.0,
    startDate: '12/08/2026',
    endDate: '22/09/2026',
    budgetRemainingCents: 340000
  },
  {
    id: 'MON-SPOTIFY-045',
    campaignName: 'Spotify Video Takeover — Vídeo Vertical com Áudio Ativo',
    channel: 'SPOTIFY',
    eventName: 'FESTIVAL CURITIBA 2026',
    eventId: 1,
    externalCampaignId: 'sp_camp_892019488',
    platformCampaignStatus: 'ACTIVE',
    platformAdSetStatus: 'ACTIVE',
    platformAdStatus: 'APPROVED',
    platformStatusLabelPtBr: 'Ativa',
    deliveryStatus: 'ACTIVE_DELIVERING',
    deliveryMeta: DELIVERY_STATUS_DICTIONARY.ACTIVE_DELIVERING,
    impressionsLast6h: 8800,
    clicksLast6h: 380,
    spendLast6hCents: 25000,
    lastTelemetryAt: 'há 22 min',
    lastSyncAt: 'há 22 min',
    alerts: [{ level: 'INFO', message: 'Exibição exclusiva durante navegação ativa no app.' }],
    totalSpentCents: 460000,
    totalRevenueCents: 2990000,
    totalConversions: 130,
    roas: 6.5,
    startDate: '14/08/2026',
    endDate: '24/09/2026',
    budgetRemainingCents: 380000
  },
  {
    id: 'MON-SPOTIFY-046',
    campaignName: 'Spotify Áudio Fim de Noite — Playlists Acústicas',
    channel: 'SPOTIFY',
    eventName: 'FESTIVAL CURITIBA 2026',
    eventId: 1,
    externalCampaignId: 'sp_camp_892019489',
    platformCampaignStatus: 'ACTIVE',
    platformAdSetStatus: 'ACTIVE',
    platformAdStatus: 'APPROVED',
    platformStatusLabelPtBr: 'Ativa',
    deliveryStatus: 'ACTIVE_NO_DELIVERY',
    deliveryMeta: DELIVERY_STATUS_DICTIONARY.ACTIVE_NO_DELIVERY,
    impressionsLast6h: 0,
    clicksLast6h: 0,
    spendLast6hCents: 0,
    lastTelemetryAt: 'há 14h',
    lastSyncAt: 'há 27 min',
    issueReason: 'Horário de veiculação programado (Dayparting) restrito apenas para madrugada (00h às 05h).',
    alerts: [{ level: 'INFO', message: 'Fora da janela horária programada de veiculação.' }],
    totalSpentCents: 110000,
    totalRevenueCents: 550000,
    totalConversions: 25,
    roas: 5.0,
    startDate: '15/08/2026',
    endDate: '20/09/2026',
    budgetRemainingCents: 210000
  },
  {
    id: 'MON-SPOTIFY-047',
    campaignName: 'Novo Spot 30s — Gravação em Estúdio com Voz Oficial',
    channel: 'SPOTIFY',
    eventName: 'FESTIVAL CURITIBA 2026',
    eventId: 1,
    externalCampaignId: 'sp_camp_892019490',
    platformCampaignStatus: 'ACTIVE',
    platformAdSetStatus: 'ACTIVE',
    platformAdStatus: 'PENDING_REVIEW',
    platformStatusLabelPtBr: 'Em análise',
    deliveryStatus: 'PENDING_REVIEW',
    deliveryMeta: DELIVERY_STATUS_DICTIONARY.PENDING_REVIEW,
    impressionsLast6h: 0,
    clicksLast6h: 0,
    spendLast6hCents: 0,
    lastTelemetryAt: 'Nunca entregou',
    lastSyncAt: 'há 30 min',
    issueReason: 'Arquivo de áudio na fila de normalização sonora (-14 LUFS) do Spotify Ads Studio.',
    alerts: [{ level: 'INFO', message: 'Aguardando checagem técnica de áudio do Spotify.' }],
    totalSpentCents: 0,
    totalRevenueCents: 0,
    totalConversions: 0,
    roas: 0,
    startDate: '11/09/2026',
    endDate: '25/09/2026',
    budgetRemainingCents: 350000
  },
  {
    id: 'MON-SPOTIFY-048',
    campaignName: 'Companion Banner 640x640 com Resolução Inválida',
    channel: 'SPOTIFY',
    eventName: 'FESTIVAL CURITIBA 2026',
    eventId: 1,
    externalCampaignId: 'sp_camp_892019491',
    platformCampaignStatus: 'ACTIVE',
    platformAdSetStatus: 'ACTIVE',
    platformAdStatus: 'DISAPPROVED',
    platformStatusLabelPtBr: 'Anúncio Reprovado',
    deliveryStatus: 'REJECTED',
    deliveryMeta: DELIVERY_STATUS_DICTIONARY.REJECTED,
    impressionsLast6h: 0,
    clicksLast6h: 0,
    spendLast6hCents: 0,
    lastTelemetryAt: 'Nunca entregou',
    lastSyncAt: 'há 40 min',
    issueReason: 'O banner complementar enviado tinha proporção 800x600 ao invés do padrão exato 640x640 pixels exigido pela API v3 do Spotify.',
    alerts: [{ level: 'CRITICAL', message: 'Criativo recusado por formato inválido (exige 640x640).', suggestion: 'Substitua o arquivo por imagem quadrada de 640x640 pixels.' }],
    totalSpentCents: 0,
    totalRevenueCents: 0,
    totalConversions: 0,
    roas: 0,
    startDate: '10/09/2026',
    endDate: '19/09/2026',
    budgetRemainingCents: 200000
  }
]

export class CampaignDeliveryService {
  private static loadState(): MonitoredCampaignDeliveryItem[] {
    try {
      const stored = sessionStorage.getItem(STORAGE_KEY)
      if (stored) {
        return JSON.parse(stored)
      }
    } catch {
      // ignore
    }
    return INITIAL_CAMPAIGNS
  }

  private static saveState(items: MonitoredCampaignDeliveryItem[]): void {
    try {
      sessionStorage.setItem(STORAGE_KEY, JSON.stringify(items))
    } catch {
      // ignore
    }
  }

  public static getMonitoredCampaigns(filter?: {
    channel?: MonitoredChannelKey | 'ALL'
    deliveryStatus?: CampaignDeliveryStatus | 'ALL'
    eventId?: number | null
  }): MonitoredCampaignDeliveryItem[] {
    const items = this.loadState()
    return items.filter(c => {
      if (filter?.channel && filter.channel !== 'ALL' && c.channel !== filter.channel) {
        return false
      }
      if (filter?.deliveryStatus && filter.deliveryStatus !== 'ALL' && c.deliveryStatus !== filter.deliveryStatus) {
        return false
      }
      if (filter?.eventId && c.eventId && c.eventId !== filter.eventId) {
        return false
      }
      return true
    })
  }

  public static getSummaryKpis(eventId?: number | null) {
    const items = this.getMonitoredCampaigns({ eventId })
    const delivering = items.filter(c => c.deliveryStatus === 'ACTIVE_DELIVERING').length
    const noDelivery = items.filter(c => c.deliveryStatus === 'ACTIVE_NO_DELIVERY').length
    const inReview = items.filter(c => c.deliveryStatus === 'PENDING_REVIEW').length
    const rejected = items.filter(c => c.deliveryStatus === 'REJECTED').length
    const paused = items.filter(c => c.deliveryStatus === 'PAUSED').length
    const totalImpressions6h = items.reduce((sum, c) => sum + c.impressionsLast6h, 0)
    const totalSpend6hCents = items.reduce((sum, c) => sum + c.spendLast6hCents, 0)
    const totalClicks6h = items.reduce((sum, c) => sum + c.clicksLast6h, 0)

    return {
      totalCampaigns: items.length,
      deliveringCount: delivering,
      noDeliveryCount: noDelivery,
      inReviewCount: inReview,
      rejectedCount: rejected,
      pausedCount: paused,
      totalImpressions6h,
      totalSpend6hCents,
      totalClicks6h
    }
  }

  public static async syncAllCampaigns(): Promise<MonitoredCampaignDeliveryItem[]> {
    // Simula sincronização com APIs oficiais (Meta Graph, Google Ads API, TikTok MKT, Spotify Ads API)
    await new Promise(r => setTimeout(r, 450))
    const current = this.loadState()

    const updated = current.map(item => {
      let newImpressions = item.impressionsLast6h
      let newSpend = item.spendLast6hCents
      let newClicks = item.clicksLast6h

      if (item.deliveryStatus === 'ACTIVE_DELIVERING') {
        const deltaImp = Math.floor(Math.random() * 80) + 20
        newImpressions += deltaImp
        newClicks += Math.max(1, Math.floor(deltaImp * 0.045))
        newSpend += Math.floor(deltaImp * 3.2)
      }

      const evaluation = evaluateCampaignDeliveryStatus({
        channel: item.channel,
        platformCampaignStatus: item.platformCampaignStatus,
        platformAdSetStatus: item.platformAdSetStatus,
        platformAdStatus: item.platformAdStatus,
        impressionsLast6h: newImpressions,
        clicksLast6h: newClicks,
        spendLast6hCents: newSpend,
        startDate: item.startDate,
        endDate: item.endDate
      })

      return {
        ...item,
        impressionsLast6h: newImpressions,
        clicksLast6h: newClicks,
        spendLast6hCents: newSpend,
        deliveryStatus: evaluation.deliveryStatus,
        deliveryMeta: DELIVERY_STATUS_DICTIONARY[evaluation.deliveryStatus],
        platformStatusLabelPtBr: evaluation.platformStatusLabelPtBr,
        issueReason: evaluation.issueReason || item.issueReason,
        alerts: evaluation.alerts.length ? evaluation.alerts : item.alerts,
        lastTelemetryAt: 'há menos de 1 min',
        lastSyncAt: 'agora mesmo'
      }
    })

    this.saveState(updated)
    return updated
  }

  public static async syncSingleCampaign(campaignId: string): Promise<MonitoredCampaignDeliveryItem | null> {
    await new Promise(r => setTimeout(r, 300))
    const current = this.loadState()
    const target = current.find(c => c.id === campaignId)
    if (!target) return null

    let newImpressions = target.impressionsLast6h
    let newSpend = target.spendLast6hCents
    let newClicks = target.clicksLast6h

    if (target.deliveryStatus === 'ACTIVE_DELIVERING') {
      newImpressions += 45
      newClicks += 2
      newSpend += 150
    }

    const evaluation = evaluateCampaignDeliveryStatus({
      channel: target.channel,
      platformCampaignStatus: target.platformCampaignStatus,
      platformAdSetStatus: target.platformAdSetStatus,
      platformAdStatus: target.platformAdStatus,
      impressionsLast6h: newImpressions,
      clicksLast6h: newClicks,
      spendLast6hCents: newSpend
    })

    const updatedItem: MonitoredCampaignDeliveryItem = {
      ...target,
      impressionsLast6h: newImpressions,
      clicksLast6h: newClicks,
      spendLast6hCents: newSpend,
      deliveryStatus: evaluation.deliveryStatus,
      deliveryMeta: DELIVERY_STATUS_DICTIONARY[evaluation.deliveryStatus],
      platformStatusLabelPtBr: evaluation.platformStatusLabelPtBr,
      issueReason: evaluation.issueReason,
      alerts: evaluation.alerts,
      lastTelemetryAt: 'há menos de 1 min',
      lastSyncAt: 'agora mesmo'
    }

    const updatedList = current.map(c => (c.id === campaignId ? updatedItem : c))
    this.saveState(updatedList)
    return updatedItem
  }
}
