import { Router } from 'express'
import { z } from 'zod'
import { prisma } from '../prisma.js'
import { audit } from '../audit.js'
import { requireAuth, type AuthRequest } from '../middleware/auth.js'
import { requestedProducerId, writeProducerId } from '../tenant.js'
export const checkinsRouter=Router();checkinsRouter.use(requireAuth)
const input=z.object({eventId:z.number().int().positive(),participantId:z.number().int().positive().optional(),ticketId:z.number().int().positive().optional(),gate:z.string().optional(),method:z.string().optional(),operatorName:z.string().optional(),producerId:z.number().int().positive().optional()}).refine(v=>v.participantId||v.ticketId,{message:'Informe participante ou ingresso.'})
checkinsRouter.get('/',async(req:AuthRequest,res)=>{const producerId=requestedProducerId(req),eventId=req.query.eventId?Number(req.query.eventId):undefined;res.json(await prisma.checkIn.findMany({where:{...(producerId?{producerId}:{}),...(eventId?{eventId}:{})},include:{participant:{select:{id:true,name:true}},ticket:{select:{id:true,code:true}},event:{select:{id:true,title:true}}},orderBy:{checkedAt:'desc'}}))})
checkinsRouter.post('/',async(req:AuthRequest,res)=>{const p=input.parse(req.body),producerId=writeProducerId(req,p.producerId);if(!producerId)return res.status(400).json({message:'Produtora obrigatória.'});const event=await prisma.event.findUnique({where:{id:p.eventId}});if(!event||event.producerId!==producerId)return res.status(403).json({message:'Evento fora do escopo da produtora.'});if(p.ticketId){const ticket=await prisma.ticket.findUnique({where:{id:p.ticketId}});if(!ticket||ticket.producerId!==producerId||ticket.eventId!==p.eventId)return res.status(400).json({message:'Ingresso inválido.'});const used=await prisma.checkIn.findFirst({where:{ticketId:p.ticketId,status:'presente'}});if(used)return res.status(409).json({message:'Ingresso já utilizado.'})}const created=await prisma.checkIn.create({data:{...p,producerId} as any});await audit(req,req.auth!.id,producerId,'checkin','event',String(p.eventId));res.status(201).json(created)})
