import { Router } from 'express'
import { z } from 'zod'
import { prisma } from '../prisma.js'
import { requireAuth, type AuthRequest } from '../middleware/auth.js'
import { tenantProducerId, tenantWhere } from '../tenant.js'
export const communicationRouter=Router(); communicationRouter.use(requireAuth)
communicationRouter.get('/summary',async(req:AuthRequest,res)=>{const where=tenantWhere(req.user!,req.query.producerId);const [channels,executions,consents]=await Promise.all([prisma.communicationChannel.findMany({where}),prisma.automationExecution.findMany({where,take:500}),prisma.contactConsent.findMany({where})]);res.json({channels:channels.length,activeChannels:channels.filter(x=>x.status==='ativo').length,queued:executions.filter(x=>x.status==='agendado').length,sent:executions.filter(x=>x.status==='enviado').length,failed:executions.filter(x=>x.status==='falhou').length,optOuts:consents.filter(x=>x.status==='optout').length})})
communicationRouter.get('/channels',async(req:AuthRequest,res)=>{const where=tenantWhere(req.user!,req.query.producerId);res.json(await prisma.communicationChannel.findMany({where,orderBy:{type:'asc'}}))})
communicationRouter.patch('/channels/:id',async(req:AuthRequest,res)=>{const id=Number(req.params.id),where=tenantWhere(req.user!,req.body.producerId);const exists=await prisma.communicationChannel.findFirst({where:{id,...where}});if(!exists)return res.status(404).json({message:'Canal não encontrado.'});const schema=z.object({status:z.enum(['ativo','inativo','pendente']).optional(),provider:z.string().optional(),sender:z.string().optional()});const parsed=schema.safeParse(req.body);if(!parsed.success)return res.status(400).json({message:'Dados inválidos.'});res.json(await prisma.communicationChannel.update({where:{id},data:parsed.data}))})
communicationRouter.get('/queue',async(req:AuthRequest,res)=>{const where=tenantWhere(req.user!,req.query.producerId);res.json(await prisma.automationExecution.findMany({where,include:{flow:{select:{name:true,trigger:true}}},orderBy:{scheduledAt:'desc'},take:100}))})
communicationRouter.get('/consents',async(req:AuthRequest,res)=>{const where=tenantWhere(req.user!,req.query.producerId);res.json(await prisma.contactConsent.findMany({where,orderBy:{updatedAt:'desc'},take:200}))})
communicationRouter.post('/consents',async(req:AuthRequest,res)=>{const schema=z.object({contact:z.string().min(3),channel:z.enum(['whatsapp','email','sms']),status:z.enum(['optin','optout']),source:z.string().default('sistema')});const parsed=schema.safeParse(req.body);if(!parsed.success)return res.status(400).json({message:'Dados inválidos.'});const producerId=tenantProducerId(req.user!,req.body.producerId);if(!producerId)return res.status(400).json({message:'Selecione uma produtora.'});const key={producerId_contact_channel:{producerId,contact:parsed.data.contact,channel:parsed.data.channel}} as any;res.json(await prisma.contactConsent.upsert({where:key,create:{...parsed.data,producerId},update:{status:parsed.data.status,source:parsed.data.source}}))})
