import { Router } from 'express'
import { z } from 'zod'
import { requireAuth, type AuthRequest } from '../middleware/auth.js'
import { requestedProducerId, ownsProducer } from '../tenant.js'
import { prisma } from '../prisma.js'
import { dispatchUniversalConversion } from '../services/conversionEngine.js'

export const conversionsRouter=Router();conversionsRouter.use(requireAuth)
const schema=z.object({eventId:z.string().min(8),eventName:z.enum(['page_view','view_content','add_to_cart','begin_checkout','add_payment_info','purchase','lead','sign_up']),producerId:z.number().int().positive().optional(),eventEntityId:z.number().int().positive().optional().nullable(),orderId:z.number().int().positive().optional().nullable(),valueCents:z.number().int().nonnegative().optional(),currency:z.string().length(3).optional(),email:z.string().email().optional().nullable(),phone:z.string().optional().nullable(),externalId:z.string().optional().nullable(),attribution:z.record(z.string(),z.unknown()).optional(),metadata:z.record(z.string(),z.unknown()).optional()})
conversionsRouter.post('/dispatch',async(req:AuthRequest,res)=>{const body=schema.parse(req.body);const producerId=body.producerId||requestedProducerId(req);if(!producerId||!ownsProducer(req,producerId))return res.status(403).json({message:'Produtora fora do escopo.'});if(body.eventEntityId){const ev=await prisma.event.findUnique({where:{id:body.eventEntityId}});if(!ev||ev.producerId!==producerId)return res.status(403).json({message:'Evento fora do escopo.'})}const result=await dispatchUniversalConversion({...body,producerId} as any);res.status(result.deduplicated?200:201).json(result)})
conversionsRouter.get('/summary',async(req:AuthRequest,res)=>{const producerId=requestedProducerId(req);if(!producerId)return res.json({events:0,dispatches:0,ok:0,error:0,dryRun:0,queued:0});const [events,dispatches,ok,error,dryRun,queued]=await Promise.all([prisma.marketingConversionEvent.count({where:{producerId}}),prisma.marketingConversionDispatch.count({where:{conversionEvent:{producerId}}}),prisma.marketingConversionDispatch.count({where:{conversionEvent:{producerId},status:'ok'}}),prisma.marketingConversionDispatch.count({where:{conversionEvent:{producerId},status:'erro'}}),prisma.marketingConversionDispatch.count({where:{conversionEvent:{producerId},status:'dry_run'}}),prisma.marketingConversionDispatch.count({where:{conversionEvent:{producerId},status:'queued'}})]);res.json({events,dispatches,ok,error,dryRun,queued})})
