import { Router } from 'express'
import { z } from 'zod'
import crypto from 'node:crypto'
import { prisma } from '../prisma.js'
import { audit } from '../audit.js'
import { requireAuth, type AuthRequest } from '../middleware/auth.js'
import { requestedProducerId, writeProducerId } from '../tenant.js'

export const financeAccountingRouter=Router()

// Webhook preparado para Autentique/outros provedores. Configure SIGNATURE_WEBHOOK_SECRET.
financeAccountingRouter.post('/signatures/webhook',async(req,res)=>{
 const configured=process.env.SIGNATURE_WEBHOOK_SECRET
 if(configured && req.header('x-disk-signature-secret')!==configured) return res.status(401).json({message:'Webhook não autorizado.'})
 const payload=req.body||{}
 const providerDocumentId=String(payload.document_id||payload.documentId||payload.data?.document?.id||'')
 if(!providerDocumentId) return res.status(400).json({message:'document_id ausente.'})
 const status=String(payload.status||payload.data?.document?.status||'atualizado').toLowerCase()
 const request=await prisma.signatureRequest.findFirst({where:{providerDocumentId}})
 if(!request) return res.status(202).json({ok:true,ignored:true})
 const completed=['signed','completed','assinado'].includes(status)
 await prisma.signatureRequest.update({where:{id:request.id},data:{status:completed?'assinado':status,webhookStatus:status,completedAt:completed?new Date():undefined,signedFileUrl:payload.signed_file_url||payload.signedFileUrl||undefined}})
 res.json({ok:true})
})

financeAccountingRouter.use(requireAuth)
const cents=(v:number)=>Math.round(v)
const eventFilter=(req:AuthRequest)=>req.query.eventId?Number(req.query.eventId):undefined

financeAccountingRouter.get('/summary',async(req:AuthRequest,res)=>{
 const producerId=requestedProducerId(req),eventId=eventFilter(req)
 const scope={...(producerId?{producerId}:{}),...(eventId?{eventId}:{})}
 const [orders,tx,rec,obligations,borderos,signatures,costCenters,entries]=await Promise.all([
  prisma.order.findMany({where:scope,select:{grossCents:true,netCents:true,status:true}}),
  prisma.financialTransaction.findMany({where:scope,select:{type:true,amountCents:true,status:true,category:true}}),
  prisma.reconciliationItem.findMany({where:scope,select:{expectedCents:true,receivedCents:true,differenceCents:true,status:true}}),
  prisma.financialObligation.findMany({where:scope,select:{kind:true,amountCents:true,status:true}}),
  prisma.borderoDocument.count({where:scope}),
  prisma.signatureRequest.count({where:scope}),
  prisma.costCenter.count({where:scope}),
  prisma.accountingEntry.count({where:scope}),
 ])
 const revenue=orders.filter(o=>o.status!=='cancelado').reduce((a,o)=>a+o.grossCents,0)
 const netRevenue=orders.filter(o=>o.status!=='cancelado').reduce((a,o)=>a+o.netCents,0)
 const expenses=tx.filter(t=>t.type==='saida'&&t.category!=='repasse').reduce((a,t)=>a+t.amountCents,0)+obligations.filter(o=>o.kind==='pagar'&&o.status==='pago').reduce((a,o)=>a+o.amountCents,0)
 const reconciled=rec.filter(r=>['conciliado','conciliado-manual'].includes(r.status)).reduce((a,r)=>a+r.receivedCents,0)
 const pending=rec.filter(r=>['pendente','parcial','divergente'].includes(r.status)).reduce((a,r)=>a+Math.abs(r.differenceCents||r.expectedCents-r.receivedCents),0)
 res.json({revenueCents:revenue,netRevenueCents:netRevenue,expensesCents:expenses,resultCents:netRevenue-expenses,reconciledCents:reconciled,pendingCents:pending,divergences:rec.filter(r=>r.status==='divergente').length,payablesCents:obligations.filter(o=>o.kind==='pagar'&&o.status!=='pago').reduce((a,o)=>a+o.amountCents,0),receivablesCents:obligations.filter(o=>o.kind==='receber'&&o.status!=='pago').reduce((a,o)=>a+o.amountCents,0),borderos,signatures,costCenters,entries})
})

financeAccountingRouter.post('/bootstrap',async(req:AuthRequest,res)=>{
 const body=z.object({producerId:z.number().int().positive().optional(),eventId:z.number().int().positive().optional()}).parse(req.body||{})
 const producerId=writeProducerId(req,body.producerId); if(!producerId)return res.status(400).json({message:'Produtora obrigatória.'})
 const defaultAccounts=[
  ['1.1.01','Caixa e Bancos','devedora','ativo'],['1.1.02','Valores a Receber','devedora','ativo'],['2.1.01','Repasses a Pagar','credora','passivo'],
  ['3.1.01','Receita de Ingressos','credora','receita'],['3.1.02','Taxa de Serviço','credora','receita'],['4.1.01','Taxas de Adquirência','devedora','despesa'],
  ['4.1.02','Marketing','devedora','despesa'],['4.1.03','Operação do Evento','devedora','custo'],['4.1.04','Estrutura','devedora','custo'],['4.1.05','Comissões','devedora','despesa']
 ] as const
 const defaultCenters=[['MKT','Marketing'],['OPE','Operação'],['EST','Estrutura'],['COM','Comercial'],['ADM','Administrativo']] as const
 for(const [code,name,nature,accountType] of defaultAccounts) await prisma.chartAccount.upsert({where:{producerId_code:{producerId,code}},update:{name,nature,accountType},create:{producerId,code,name,nature,accountType}})
 for(const [code,name] of defaultCenters) await prisma.costCenter.upsert({where:{producerId_code:{producerId,code}},update:{name,eventId:body.eventId},create:{producerId,eventId:body.eventId,code,name}})
 await audit(req,req.auth!.id,producerId,'create','finance-bootstrap',String(body.eventId||''),'Plano de contas e centros padrão')
 res.json({ok:true})
})

financeAccountingRouter.get('/cost-centers',async(req:AuthRequest,res)=>{const producerId=requestedProducerId(req),eventId=eventFilter(req);res.json(await prisma.costCenter.findMany({where:{...(producerId?{producerId}:{}),...(eventId?{OR:[{eventId},{eventId:null}]}:{})},include:{event:{select:{id:true,title:true}},_count:{select:{entries:true,obligations:true,budgets:true}}},orderBy:{code:'asc'}}))})
financeAccountingRouter.post('/cost-centers',async(req:AuthRequest,res)=>{const p=z.object({code:z.string().min(1),name:z.string().min(2),description:z.string().optional(),type:z.string().default('operacional'),eventId:z.number().int().positive().optional(),parentId:z.number().int().positive().optional(),producerId:z.number().int().positive().optional()}).parse(req.body),producerId=writeProducerId(req,p.producerId);if(!producerId)return res.status(400).json({message:'Produtora obrigatória.'});const row=await prisma.costCenter.create({data:{producerId,code:p.code,name:p.name,description:p.description,type:p.type,eventId:p.eventId,parentId:p.parentId}});await audit(req,req.auth!.id,producerId,'create','cost-center',String(row.id),row.name);res.status(201).json(row)})
financeAccountingRouter.patch('/cost-centers/:id',async(req:AuthRequest,res)=>{const id=Number(req.params.id),producerId=requestedProducerId(req);const current=await prisma.costCenter.findFirst({where:{id,...(producerId?{producerId}:{})}});if(!current)return res.status(404).json({message:'Centro não encontrado.'});const p=z.object({name:z.string().min(2).optional(),description:z.string().nullable().optional(),status:z.string().optional(),type:z.string().optional(),eventId:z.number().int().positive().nullable().optional(),parentId:z.number().int().positive().nullable().optional()}).parse(req.body);const row=await prisma.costCenter.update({where:{id},data:p});await audit(req,req.auth!.id,current.producerId,'update','cost-center',String(id),JSON.stringify(p));res.json(row)})

financeAccountingRouter.get('/chart-accounts',async(req:AuthRequest,res)=>{const producerId=requestedProducerId(req);res.json(await prisma.chartAccount.findMany({where:producerId?{producerId}:undefined,orderBy:{code:'asc'}}))})
financeAccountingRouter.post('/chart-accounts',async(req:AuthRequest,res)=>{const p=z.object({code:z.string().min(1),name:z.string().min(2),nature:z.string().min(2),accountType:z.string().min(2),level:z.number().int().min(1).default(1),parentCode:z.string().optional(),producerId:z.number().int().positive().optional()}).parse(req.body),producerId=writeProducerId(req,p.producerId);if(!producerId)return res.status(400).json({message:'Produtora obrigatória.'});const row=await prisma.chartAccount.create({data:{...p,producerId}});await audit(req,req.auth!.id,producerId,'create','chart-account',String(row.id),row.code);res.status(201).json(row)})

financeAccountingRouter.get('/entries',async(req:AuthRequest,res)=>{const producerId=requestedProducerId(req),eventId=eventFilter(req);res.json(await prisma.accountingEntry.findMany({where:{...(producerId?{producerId}:{}),...(eventId?{eventId}:{})},include:{event:{select:{id:true,title:true}},costCenter:true,chartAccount:true},orderBy:{entryDate:'desc'},take:500}))})
financeAccountingRouter.post('/entries',async(req:AuthRequest,res)=>{const p=z.object({description:z.string().min(2),competence:z.string().min(4),debitCents:z.number().int().min(0).default(0),creditCents:z.number().int().min(0).default(0),source:z.string().default('manual'),documentRef:z.string().optional(),notes:z.string().optional(),eventId:z.number().int().positive().optional(),costCenterId:z.number().int().positive().optional(),chartAccountId:z.number().int().positive().optional(),producerId:z.number().int().positive().optional()}).parse(req.body),producerId=writeProducerId(req,p.producerId);if(!producerId)return res.status(400).json({message:'Produtora obrigatória.'});const row=await prisma.accountingEntry.create({data:{...p,producerId,code:`LC-${Date.now()}`}});await audit(req,req.auth!.id,producerId,'create','accounting-entry',String(row.id),row.description);res.status(201).json(row)})

financeAccountingRouter.get('/reconciliations',async(req:AuthRequest,res)=>{const producerId=requestedProducerId(req),eventId=eventFilter(req),status=typeof req.query.status==='string'?req.query.status:undefined;res.json(await prisma.reconciliationItem.findMany({where:{...(producerId?{producerId}:{}),...(eventId?{eventId}:{}),...(status?{status}:{})},include:{event:{select:{id:true,title:true}}},orderBy:{occurredAt:'desc'},take:500}))})
financeAccountingRouter.post('/reconciliations',async(req:AuthRequest,res)=>{const p=z.object({sourceType:z.string().min(2),sourceRef:z.string().optional(),externalRef:z.string().optional(),expectedCents:z.number().int(),receivedCents:z.number().int().default(0),reason:z.string().optional(),eventId:z.number().int().positive().optional(),producerId:z.number().int().positive().optional()}).parse(req.body),producerId=writeProducerId(req,p.producerId);if(!producerId)return res.status(400).json({message:'Produtora obrigatória.'});const diff=p.expectedCents-p.receivedCents,status=diff===0?'conciliado':p.receivedCents===0?'pendente':'divergente';const row=await prisma.reconciliationItem.create({data:{...p,producerId,code:`CONC-${Date.now()}`,differenceCents:diff,status,reconciledAt:diff===0?new Date():undefined,reconciledBy:diff===0?req.auth!.name:undefined}});res.status(201).json(row)})
financeAccountingRouter.patch('/reconciliations/:id/reconcile',async(req:AuthRequest,res)=>{const id=Number(req.params.id),producerId=requestedProducerId(req),p=z.object({receivedCents:z.number().int().optional(),reason:z.string().optional(),force:z.boolean().default(false)}).parse(req.body||{});const current=await prisma.reconciliationItem.findFirst({where:{id,...(producerId?{producerId}:{})}});if(!current)return res.status(404).json({message:'Conciliação não encontrada.'});const received=p.receivedCents??current.receivedCents,diff=current.expectedCents-received,status=p.force||diff===0?'conciliado-manual':'divergente';const row=await prisma.reconciliationItem.update({where:{id},data:{receivedCents:received,differenceCents:diff,status,reason:p.reason,reconciledAt:['conciliado-manual','conciliado'].includes(status)?new Date():null,reconciledBy:req.auth!.name}});await audit(req,req.auth!.id,current.producerId,'update','reconciliation',String(id),status);res.json(row)})
financeAccountingRouter.post('/reconciliations/auto',async(req:AuthRequest,res)=>{const p=z.object({eventId:z.number().int().positive().optional(),producerId:z.number().int().positive().optional()}).parse(req.body||{}),producerId=writeProducerId(req,p.producerId);if(!producerId)return res.status(400).json({message:'Produtora obrigatória.'});const orders=await prisma.order.findMany({where:{producerId,...(p.eventId?{eventId:p.eventId}:{}),status:{not:'cancelado'}}});let created=0;for(const o of orders){const sourceRef=o.code;const exists=await prisma.reconciliationItem.findFirst({where:{producerId,sourceType:'pedido',sourceRef}});if(exists)continue;await prisma.reconciliationItem.create({data:{code:`CONC-${o.id}-${Date.now()}`,sourceType:'pedido',sourceRef,externalRef:`ORDER-${o.id}`,expectedCents:o.netCents,receivedCents:o.netCents,differenceCents:0,status:'conciliado',reconciledAt:new Date(),reconciledBy:'motor-automatico',producerId,eventId:o.eventId}});created++}res.json({created})})

financeAccountingRouter.get('/obligations',async(req:AuthRequest,res)=>{const producerId=requestedProducerId(req),eventId=eventFilter(req),kind=typeof req.query.kind==='string'?req.query.kind:undefined;res.json(await prisma.financialObligation.findMany({where:{...(producerId?{producerId}:{}),...(eventId?{eventId}:{}),...(kind?{kind}:{})},include:{event:{select:{id:true,title:true}},costCenter:true,chartAccount:true},orderBy:{dueDate:'asc'}}))})
financeAccountingRouter.post('/obligations',async(req:AuthRequest,res)=>{const p=z.object({kind:z.enum(['pagar','receber']),category:z.string().min(2),description:z.string().min(2),amountCents:z.number().int().positive(),dueDate:z.string(),counterparty:z.string().optional(),documentRef:z.string().optional(),eventId:z.number().int().positive().optional(),costCenterId:z.number().int().positive().optional(),chartAccountId:z.number().int().positive().optional(),producerId:z.number().int().positive().optional()}).parse(req.body),producerId=writeProducerId(req,p.producerId);if(!producerId)return res.status(400).json({message:'Produtora obrigatória.'});const {dueDate,...rest}=p;const row=await prisma.financialObligation.create({data:{...rest,producerId,code:`OBR-${Date.now()}`,dueDate:new Date(dueDate)}});res.status(201).json(row)})
financeAccountingRouter.patch('/obligations/:id/pay',async(req:AuthRequest,res)=>{const id=Number(req.params.id),producerId=requestedProducerId(req);const current=await prisma.financialObligation.findFirst({where:{id,...(producerId?{producerId}:{})}});if(!current)return res.status(404).json({message:'Lançamento não encontrado.'});const row=await prisma.financialObligation.update({where:{id},data:{status:'pago',paidAt:new Date()}});await prisma.financialTransaction.create({data:{code:`FIN-OBR-${id}-${Date.now()}`,type:current.kind==='pagar'?'saida':'entrada',category:current.category,description:current.description,amountCents:current.amountCents,status:'liquidado',producerId:current.producerId,eventId:current.eventId}});res.json(row)})

financeAccountingRouter.get('/budgets',async(req:AuthRequest,res)=>{const producerId=requestedProducerId(req),eventId=eventFilter(req);res.json(await prisma.budgetLine.findMany({where:{...(producerId?{producerId}:{}),...(eventId?{eventId}:{})},include:{costCenter:true,event:{select:{id:true,title:true}}},orderBy:{competence:'desc'}}))})
financeAccountingRouter.post('/budgets',async(req:AuthRequest,res)=>{const p=z.object({competence:z.string(),category:z.string(),plannedCents:z.number().int().min(0),realizedCents:z.number().int().min(0).default(0),notes:z.string().optional(),eventId:z.number().int().positive().optional(),costCenterId:z.number().int().positive().optional(),producerId:z.number().int().positive().optional()}).parse(req.body),producerId=writeProducerId(req,p.producerId);if(!producerId)return res.status(400).json({message:'Produtora obrigatória.'});res.status(201).json(await prisma.budgetLine.create({data:{...p,producerId}}))})

async function buildBorderoSnapshot(producerId:number,eventId:number){
 const [event,orders,tickets,lots,tx,payouts,rec,obligations]=await Promise.all([
  prisma.event.findFirst({where:{id:eventId,producerId},select:{id:true,code:true,title:true,venue:true,city:true,date:true,producer:{select:{name:true,document:true}}}}),
  prisma.order.findMany({where:{producerId,eventId},select:{id:true,code:true,buyerName:true,channel:true,paymentMethod:true,status:true,quantity:true,grossCents:true,feeCents:true,netCents:true,createdAt:true}}),
  prisma.ticket.findMany({where:{producerId,eventId},select:{status:true,type:true,priceCents:true,lotId:true}}),
  prisma.lot.findMany({where:{producerId,eventId},select:{id:true,name:true,sector:true,priceCents:true,capacity:true,sold:true,status:true}}),
  prisma.financialTransaction.findMany({where:{producerId,eventId},select:{type:true,category:true,description:true,amountCents:true,status:true,occurredAt:true}}),
  prisma.payout.findMany({where:{producerId,transactions:{some:{eventId}}},select:{code:true,amountCents:true,status:true,requestedAt:true,paidAt:true}}),
  prisma.reconciliationItem.findMany({where:{producerId,eventId},select:{sourceType:true,expectedCents:true,receivedCents:true,differenceCents:true,status:true}}),
  prisma.financialObligation.findMany({where:{producerId,eventId},select:{kind:true,category:true,amountCents:true,status:true}})
 ])
 if(!event) throw new Error('Evento não encontrado.')
 const paidOrders=orders.filter(o=>!['cancelado','estornado'].includes(o.status))
 const gross=paidOrders.reduce((a,o)=>a+o.grossCents,0),fees=paidOrders.reduce((a,o)=>a+o.feeCents,0),net=paidOrders.reduce((a,o)=>a+o.netCents,0)
 const expenses=tx.filter(t=>t.type==='saida'&&t.category!=='repasse').reduce((a,t)=>a+t.amountCents,0)+obligations.filter(o=>o.kind==='pagar'&&o.status==='pago').reduce((a,o)=>a+o.amountCents,0)
 const byPayment=Object.entries(paidOrders.reduce((a:any,o)=>{a[o.paymentMethod]=(a[o.paymentMethod]||0)+o.grossCents;return a},{})).map(([paymentMethod,amountCents])=>({paymentMethod,amountCents}))
 const byChannel=Object.entries(paidOrders.reduce((a:any,o)=>{a[o.channel]=(a[o.channel]||0)+o.grossCents;return a},{})).map(([channel,amountCents])=>({channel,amountCents}))
 return {event,summary:{orders:orders.length,sales:paidOrders.length,tickets:tickets.length,courtesies:tickets.filter(t=>t.type==='cortesia').length,cancelledOrders:orders.filter(o=>['cancelado','estornado'].includes(o.status)).length,grossCents:gross,feesCents:fees,netCents:net,expensesCents:expenses,resultCents:net-expenses,avgTicketCents:paidOrders.length?Math.round(gross/paidOrders.length):0,reconciliationRate:rec.length?Math.round(rec.filter(r=>['conciliado','conciliado-manual'].includes(r.status)).length/rec.length*10000)/100:0,divergenceCents:rec.reduce((a,r)=>a+Math.abs(r.differenceCents),0)},lots,orders,tickets,transactions:tx,payouts,reconciliations:rec,obligations,byPayment,byChannel}
}

financeAccountingRouter.get('/borderos',async(req:AuthRequest,res)=>{const producerId=requestedProducerId(req),eventId=eventFilter(req);res.json(await prisma.borderoDocument.findMany({where:{...(producerId?{producerId}:{}),...(eventId?{eventId}:{})},include:{event:{select:{id:true,title:true,code:true}},signatureRequests:{include:{signers:true}}},orderBy:{generatedAt:'desc'}}))})
financeAccountingRouter.post('/borderos/generate',async(req:AuthRequest,res)=>{const p=z.object({eventId:z.number().int().positive(),reportType:z.enum(['resumido','completo','detalhado','lote','setor','canal','pagamento','pdv','cortesias','cancelamentos','taxas','repasses','comissoes','conciliacao']).default('completo'),producerId:z.number().int().positive().optional()}).parse(req.body),producerId=writeProducerId(req,p.producerId);if(!producerId)return res.status(400).json({message:'Produtora obrigatória.'});try{const snapshot=await buildBorderoSnapshot(producerId,p.eventId);const previous=await prisma.borderoDocument.findFirst({where:{producerId,eventId:p.eventId,reportType:p.reportType},orderBy:{version:'desc'}});const row=await prisma.borderoDocument.create({data:{code:`BORD-${snapshot.event.code}-${p.reportType.toUpperCase()}-V${(previous?.version||0)+1}-${Date.now()}`,title:`Borderô ${p.reportType} — ${snapshot.event.title}`,reportType:p.reportType,version:(previous?.version||0)+1,summaryJson:JSON.stringify(snapshot.summary),snapshotJson:JSON.stringify(snapshot),producerId,eventId:p.eventId}});await audit(req,req.auth!.id,producerId,'create','bordero',String(row.id),row.code);res.status(201).json({...row,summary:snapshot.summary})}catch(e:any){res.status(400).json({message:e.message})}})
financeAccountingRouter.get('/borderos/:id/detail',async(req:AuthRequest,res)=>{const id=Number(req.params.id),producerId=requestedProducerId(req);const row=await prisma.borderoDocument.findFirst({where:{id,...(producerId?{producerId}:{})},include:{event:true,signatureRequests:{include:{signers:true}}}});if(!row)return res.status(404).json({message:'Borderô não encontrado.'});res.json({...row,summary:JSON.parse(row.summaryJson||'{}'),snapshot:JSON.parse(row.snapshotJson||'{}')})})
financeAccountingRouter.patch('/borderos/:id/approve',async(req:AuthRequest,res)=>{const id=Number(req.params.id),producerId=requestedProducerId(req);const current=await prisma.borderoDocument.findFirst({where:{id,...(producerId?{producerId}:{})}});if(!current)return res.status(404).json({message:'Borderô não encontrado.'});const row=await prisma.borderoDocument.update({where:{id},data:{status:'aprovado',approvedAt:new Date(),approvedBy:req.auth!.name}});await audit(req,req.auth!.id,current.producerId,'approve','bordero',String(id),row.code);res.json(row)})

financeAccountingRouter.post('/signatures',async(req:AuthRequest,res)=>{const p=z.object({borderoId:z.number().int().positive().optional(),eventId:z.number().int().positive().optional(),provider:z.enum(['autentique','clicksign','docusign','interno']).default('autentique'),subject:z.string().min(2),message:z.string().optional(),signingOrder:z.boolean().default(false),signers:z.array(z.object({name:z.string().min(2),email:z.string().email(),role:z.string().optional()})).min(1),producerId:z.number().int().positive().optional()}).parse(req.body),producerId=writeProducerId(req,p.producerId);if(!producerId)return res.status(400).json({message:'Produtora obrigatória.'});const providerDocumentId=`pending-${p.provider}-${Date.now()}`;const row=await prisma.signatureRequest.create({data:{code:`ASS-${Date.now()}`,provider:p.provider,providerDocumentId,status:p.provider==='interno'?'aguardando':'pronto-integracao',subject:p.subject,message:p.message,signingOrder:p.signingOrder,producerId,eventId:p.eventId,borderoId:p.borderoId,signers:{create:p.signers.map((s,i)=>({...s,orderIndex:i+1,producerId}))}},include:{signers:true}});await audit(req,req.auth!.id,producerId,'create','signature-request',String(row.id),`${p.provider}: ${p.subject}`);res.status(201).json(row)})
financeAccountingRouter.get('/signatures',async(req:AuthRequest,res)=>{const producerId=requestedProducerId(req),eventId=eventFilter(req);res.json(await prisma.signatureRequest.findMany({where:{...(producerId?{producerId}:{}),...(eventId?{eventId}:{})},include:{signers:true,bordero:{select:{id:true,code:true,title:true}}},orderBy:{createdAt:'desc'}}))})
financeAccountingRouter.patch('/signatures/:id/status',async(req:AuthRequest,res)=>{const id=Number(req.params.id),producerId=requestedProducerId(req),p=z.object({status:z.string(),providerDocumentId:z.string().optional(),documentUrl:z.string().optional(),signedFileUrl:z.string().optional()}).parse(req.body);const current=await prisma.signatureRequest.findFirst({where:{id,...(producerId?{producerId}:{})}});if(!current)return res.status(404).json({message:'Solicitação não encontrada.'});const completed=['assinado','completed','signed'].includes(p.status);const hash=completed?crypto.createHash('sha256').update(`${current.code}:${Date.now()}`).digest('hex'):undefined;res.json(await prisma.signatureRequest.update({where:{id},data:{...p,hash,completedAt:completed?new Date():undefined,sentAt:['enviado','aguardando','pronto-integracao'].includes(p.status)?new Date():undefined}}))})
financeAccountingRouter.patch('/signatures/:requestId/signers/:signerId',async(req:AuthRequest,res)=>{const requestId=Number(req.params.requestId),signerId=Number(req.params.signerId),producerId=requestedProducerId(req),p=z.object({status:z.string()}).parse(req.body);const request=await prisma.signatureRequest.findFirst({where:{id:requestId,...(producerId?{producerId}:{})}});if(!request)return res.status(404).json({message:'Solicitação não encontrada.'});const signer=await prisma.signatureSigner.update({where:{id:signerId},data:{status:p.status,signedAt:p.status==='assinado'?new Date():null}});const remaining=await prisma.signatureSigner.count({where:{signatureRequestId:requestId,status:{not:'assinado'}}});if(remaining===0)await prisma.signatureRequest.update({where:{id:requestId},data:{status:'assinado',completedAt:new Date(),hash:crypto.createHash('sha256').update(`${request.code}:${Date.now()}`).digest('hex')}});res.json(signer)})

financeAccountingRouter.get('/dre',async(req:AuthRequest,res)=>{const producerId=requestedProducerId(req),eventId=eventFilter(req);if(!producerId)return res.json({rows:[]});const [orders,tx,obligations]=await Promise.all([prisma.order.findMany({where:{producerId,...(eventId?{eventId}:{}),status:{not:'cancelado'}}}),prisma.financialTransaction.findMany({where:{producerId,...(eventId?{eventId}:{})}}),prisma.financialObligation.findMany({where:{producerId,...(eventId?{eventId}:{}),status:'pago'}})]);const gross=orders.reduce((a,o)=>a+o.grossCents,0),fees=orders.reduce((a,o)=>a+o.feeCents,0),net=orders.reduce((a,o)=>a+o.netCents,0);const costs=tx.filter(t=>t.type==='saida'&&t.category!=='repasse').reduce((a,t)=>a+t.amountCents,0)+obligations.filter(o=>o.kind==='pagar').reduce((a,o)=>a+o.amountCents,0);res.json({grossRevenueCents:gross,deductionsCents:gross-net,netRevenueCents:net,operatingCostsCents:costs,operatingResultCents:net-costs,marginPercent:net?Math.round((net-costs)/net*10000)/100:0,feeCents:fees})})

financeAccountingRouter.get('/closings',async(req:AuthRequest,res)=>{const producerId=requestedProducerId(req),eventId=eventFilter(req);res.json(await prisma.financialClosing.findMany({where:{...(producerId?{producerId}:{}),...(eventId?{eventId}:{})},include:{event:{select:{id:true,title:true,code:true}}},orderBy:{competence:'desc'}}))})
financeAccountingRouter.post('/closings',async(req:AuthRequest,res)=>{const p=z.object({competence:z.string().min(4),eventId:z.number().int().positive().optional(),notes:z.string().optional(),producerId:z.number().int().positive().optional()}).parse(req.body),producerId=writeProducerId(req,p.producerId);if(!producerId)return res.status(400).json({message:'Produtora obrigatória.'});const openDiv=await prisma.reconciliationItem.count({where:{producerId,...(p.eventId?{eventId:p.eventId}:{}),status:'divergente'}});const checklist={sales:true,receivables:openDiv===0,payouts:true,fees:openDiv===0,costCenters:true,dre:true,bordero:false,signatures:false};const existing=await prisma.financialClosing.findFirst({where:{producerId,eventId:p.eventId??null,competence:p.competence}});const row=existing?await prisma.financialClosing.update({where:{id:existing.id},data:{notes:p.notes,checklistJson:JSON.stringify(checklist)}}):await prisma.financialClosing.create({data:{producerId,eventId:p.eventId,competence:p.competence,notes:p.notes,checklistJson:JSON.stringify(checklist)}});res.status(201).json({...row,checklist})})
financeAccountingRouter.patch('/closings/:id/close',async(req:AuthRequest,res)=>{const id=Number(req.params.id),producerId=requestedProducerId(req);const current=await prisma.financialClosing.findFirst({where:{id,...(producerId?{producerId}:{})}});if(!current)return res.status(404).json({message:'Fechamento não encontrado.'});const divergences=await prisma.reconciliationItem.count({where:{producerId:current.producerId,...(current.eventId?{eventId:current.eventId}:{}),status:'divergente'}});if(divergences>0)return res.status(400).json({message:`Existem ${divergences} divergências abertas. Concilie antes do fechamento.`});const bordero= current.eventId?await prisma.borderoDocument.findFirst({where:{producerId:current.producerId,eventId:current.eventId,status:{in:['aprovado','assinado']}},orderBy:{version:'desc'}}):null;if(current.eventId&&!bordero)return res.status(400).json({message:'Gere e aprove ao menos um borderô antes de fechar o evento.'});const row=await prisma.financialClosing.update({where:{id},data:{status:'fechado',closedAt:new Date(),closedBy:req.auth!.name,checklistJson:JSON.stringify({sales:true,receivables:true,payouts:true,fees:true,costCenters:true,dre:true,bordero:true,signatures:true})}});await audit(req,req.auth!.id,current.producerId,'close','financial-closing',String(id),current.competence);res.json(row)})
