import { Router } from 'express'
import { z } from 'zod'
import { prisma } from '../prisma.js'
import { audit } from '../audit.js'
import { requireAuth, type AuthRequest } from '../middleware/auth.js'
import { requestedProducerId, writeProducerId } from '../tenant.js'
export const financeOperationsRouter=Router();financeOperationsRouter.use(requireAuth)
financeOperationsRouter.get('/transactions',async(req:AuthRequest,res)=>{const producerId=requestedProducerId(req),eventId=req.query.eventId?Number(req.query.eventId):undefined,type=typeof req.query.type==='string'?req.query.type:undefined;res.json(await prisma.financialTransaction.findMany({where:{...(producerId?{producerId}:{}),...(eventId?{eventId}:{}),...(type?{type}:{})},include:{event:{select:{id:true,title:true}},order:{select:{id:true,code:true}},payout:{select:{id:true,code:true}}},orderBy:{occurredAt:'desc'}}))})
financeOperationsRouter.get('/balance',async(req:AuthRequest,res)=>{const producerId=requestedProducerId(req);const rows=await prisma.financialTransaction.findMany({where:{...(producerId?{producerId}:{}),status:'liquidado'},select:{type:true,amountCents:true}});const entries=rows.filter(r=>r.type==='entrada').reduce((a,r)=>a+r.amountCents,0),exits=rows.filter(r=>r.type==='saida').reduce((a,r)=>a+r.amountCents,0);res.json({entriesCents:entries,exitsCents:exits,balanceCents:entries-exits})})
financeOperationsRouter.get('/payouts',async(req:AuthRequest,res)=>{const producerId=requestedProducerId(req);res.json(await prisma.payout.findMany({where:producerId?{producerId}:undefined,include:{producer:{select:{name:true}}},orderBy:{requestedAt:'desc'}}))})
financeOperationsRouter.post('/payouts',async(req:AuthRequest,res)=>{const p=z.object({amountCents:z.number().int().positive(),bankAccount:z.string().min(3).optional(),notes:z.string().optional(),producerId:z.number().int().positive().optional()}).parse(req.body),producerId=writeProducerId(req,p.producerId);if(!producerId)return res.status(400).json({message:'Produtora obrigatória.'});const balanceRows=await prisma.financialTransaction.findMany({where:{producerId,status:'liquidado'},select:{type:true,amountCents:true}}),balance=balanceRows.reduce((a,r)=>a+(r.type==='entrada'?r.amountCents:-r.amountCents),0);if(p.amountCents>balance)return res.status(400).json({message:'Saldo insuficiente para o repasse.'});const code=`REP-${Date.now()}`;const payout=await prisma.$transaction(async tx=>{const created=await tx.payout.create({data:{code,amountCents:p.amountCents,bankAccount:p.bankAccount,notes:p.notes,producerId}});await tx.financialTransaction.create({data:{code:`FIN-${code}`,type:'saida',category:'repasse',description:`Solicitação de repasse ${code}`,amountCents:p.amountCents,status:'pendente',producerId,payoutId:created.id}});return created});await audit(req,req.auth!.id,producerId,'create','payout',String(payout.id),`R$ ${(p.amountCents/100).toFixed(2)}`);res.status(201).json(payout)})
