import { Router } from 'express'
import { z } from 'zod'
import { prisma } from '../prisma.js'
import { audit } from '../audit.js'
import { requireAuth, type AuthRequest } from '../middleware/auth.js'
import { ownsProducer, requestedProducerId, writeProducerId } from '../tenant.js'

export const ordersRouter=Router(); ordersRouter.use(requireAuth)
const input=z.object({code:z.string().min(3),buyerName:z.string().min(2),buyerEmail:z.string().email(),buyerDocument:z.string().optional(),channel:z.string().optional(),paymentMethod:z.string().min(2),status:z.string().optional(),quantity:z.number().int().positive(),grossCents:z.number().int().nonnegative(),feeCents:z.number().int().nonnegative().optional(),netCents:z.number().int().nonnegative(),eventId:z.number().int().positive(),producerId:z.number().int().positive().optional(),lotId:z.number().int().positive().optional(),attributionSessionKey:z.string().min(8).optional()})
ordersRouter.get('/',async(req:AuthRequest,res)=>{const producerId=requestedProducerId(req),eventId=req.query.eventId?Number(req.query.eventId):undefined,status=typeof req.query.status==='string'?req.query.status:undefined;res.json(await prisma.order.findMany({where:{...(producerId?{producerId}:{}),...(eventId?{eventId}:{}),...(status?{status}:{})},include:{event:{select:{id:true,title:true}},tickets:true,posTransaction:true},orderBy:{createdAt:'desc'}}))})
ordersRouter.post('/',async(req:AuthRequest,res)=>{const p=input.parse(req.body),producerId=writeProducerId(req,p.producerId);if(!producerId)return res.status(400).json({message:'Produtora obrigatória.'});const event=await prisma.event.findUnique({where:{id:p.eventId}});if(!event||event.producerId!==producerId)return res.status(403).json({message:'Evento fora do escopo da produtora.'});if(p.lotId){const lot=await prisma.lot.findUnique({where:{id:p.lotId}});if(!lot||lot.eventId!==p.eventId||lot.producerId!==producerId)return res.status(400).json({message:'Lote inválido.'})}
 const created=await prisma.$transaction(async tx=>{const attribution=p.attributionSessionKey?await tx.trackingAttribution.findUnique({where:{sessionKey:p.attributionSessionKey}}):null;if(attribution&&(attribution.eventId!==p.eventId||attribution.producerId!==producerId||attribution.expiresAt<new Date()))throw new Error('Sessão UTM inválida para esta venda.');const order=await tx.order.create({data:{code:p.code,buyerName:p.buyerName,buyerEmail:p.buyerEmail,buyerDocument:p.buyerDocument,channel:p.channel,paymentMethod:p.paymentMethod,status:p.status,quantity:p.quantity,grossCents:p.grossCents,feeCents:p.feeCents,netCents:p.netCents,eventId:p.eventId,producerId}});for(let i=0;i<p.quantity;i++)await tx.ticket.create({data:{code:`${p.code}-T${i+1}`,priceCents:Math.floor(p.grossCents/p.quantity),producerId,eventId:p.eventId,orderId:order.id,lotId:p.lotId}});if(p.lotId)await tx.lot.update({where:{id:p.lotId},data:{sold:{increment:p.quantity}}});await tx.event.update({where:{id:p.eventId},data:{sales:{increment:p.quantity},totalCents:{increment:p.grossCents}}});await tx.financialTransaction.create({data:{code:`FIN-${p.code}`,type:'entrada',category:'venda',description:`Venda ${p.code}`,amountCents:p.netCents,status:p.status==='pago'?'liquidado':'pendente',producerId,eventId:p.eventId,orderId:order.id}});if(attribution){await tx.trackingAttribution.update({where:{id:attribution.id},data:{status:'converted',orderId:order.id,customerName:p.buyerName,customerEmail:p.buyerEmail,cartValueCents:p.grossCents,lastActivityAt:new Date(),convertedAt:new Date()}});await tx.trackingJourneyAction.create({data:{action:'finalized',orderCode:p.code,customerName:p.buyerName,customerEmail:p.buyerEmail,ticketSummary:`${p.quantity} ingresso(s)`,amountCents:p.grossCents,trackingLinkId:attribution.trackingLinkId,producerId,eventId:p.eventId}});await tx.trackingLink.update({where:{id:attribution.trackingLinkId},data:{conversions:{increment:1}}})}return order});await audit(req,req.auth!.id,producerId,'create','order',String(created.id));res.status(201).json(created)})
ordersRouter.patch('/:id/status',async(req:AuthRequest,res)=>{const id=Number(req.params.id),body=z.object({status:z.string().min(2)}).parse(req.body),existing=await prisma.order.findUnique({where:{id}});if(!existing)return res.status(404).json({message:'Venda não encontrada.'});if(!ownsProducer(req,existing.producerId))return res.status(403).json({message:'Acesso negado.'});const updated=await prisma.order.update({where:{id},data:{status:body.status}});await audit(req,req.auth!.id,existing.producerId,'status','order',String(id),body.status);res.json(updated)})
