import { Router } from 'express'
import { z } from 'zod'
import { prisma } from '../prisma.js'
import { audit } from '../audit.js'
import { requireAuth, type AuthRequest } from '../middleware/auth.js'
import { ownsProducer, requestedProducerId, writeProducerId } from '../tenant.js'
export const posRouter=Router();posRouter.use(requireAuth)
const terminalInput=z.object({code:z.string().min(2),name:z.string().min(2),status:z.string().optional(),operatorName:z.string().optional(),batteryPercent:z.number().int().min(0).max(100).optional(),eventId:z.number().int().positive().optional(),producerId:z.number().int().positive().optional()})
posRouter.get('/terminals',async(req:AuthRequest,res)=>{const producerId=requestedProducerId(req);res.json(await prisma.posTerminal.findMany({where:producerId?{producerId}:undefined,include:{event:{select:{id:true,title:true}},_count:{select:{transactions:true}}},orderBy:{id:'desc'}}))})
posRouter.post('/terminals',async(req:AuthRequest,res)=>{const p=terminalInput.parse(req.body),producerId=writeProducerId(req,p.producerId);if(!producerId)return res.status(400).json({message:'Produtora obrigatória.'});if(p.eventId){const event=await prisma.event.findUnique({where:{id:p.eventId}});if(!event||event.producerId!==producerId)return res.status(400).json({message:'Evento inválido.'})}const created=await prisma.posTerminal.create({data:{...p,producerId,lastSyncAt:new Date()}});await audit(req,req.auth!.id,producerId,'create','pos-terminal',String(created.id));res.status(201).json(created)})
posRouter.patch('/terminals/:id/status',async(req:AuthRequest,res)=>{const id=Number(req.params.id),{status}=z.object({status:z.string().min(2)}).parse(req.body),existing=await prisma.posTerminal.findUnique({where:{id}});if(!existing)return res.status(404).json({message:'Terminal não encontrado.'});if(!ownsProducer(req,existing.producerId))return res.status(403).json({message:'Acesso negado.'});const updated=await prisma.posTerminal.update({where:{id},data:{status,lastSyncAt:new Date()}});res.json(updated)})
posRouter.get('/transactions',async(req:AuthRequest,res)=>{const producerId=requestedProducerId(req),eventId=req.query.eventId?Number(req.query.eventId):undefined;res.json(await prisma.posTransaction.findMany({where:{...(producerId?{producerId}:{}),...(eventId?{eventId}:{})},include:{terminal:{select:{code:true,name:true}},event:{select:{id:true,title:true}},order:true},orderBy:{createdAt:'desc'}}))})

posRouter.post('/transactions',async(req:AuthRequest,res)=>{const p=z.object({code:z.string().min(3),amountCents:z.number().int().positive(),paymentMethod:z.string().min(2),status:z.string().optional(),eventId:z.number().int().positive(),terminalId:z.number().int().positive(),orderId:z.number().int().positive().optional(),producerId:z.number().int().positive().optional()}).parse(req.body),producerId=writeProducerId(req,p.producerId);if(!producerId)return res.status(400).json({message:'Produtora obrigatória.'});const [event,terminal]=await Promise.all([prisma.event.findUnique({where:{id:p.eventId}}),prisma.posTerminal.findUnique({where:{id:p.terminalId}})]);if(!event||event.producerId!==producerId||!terminal||terminal.producerId!==producerId)return res.status(400).json({message:'Evento ou terminal fora do escopo.'});const created=await prisma.$transaction(async tx=>{const row=await tx.posTransaction.create({data:{code:p.code,amountCents:p.amountCents,paymentMethod:p.paymentMethod,status:p.status,producerId,eventId:p.eventId,terminalId:p.terminalId,orderId:p.orderId}});if((p.status||'aprovada')==='aprovada')await tx.financialTransaction.create({data:{code:`FIN-${p.code}`,type:'entrada',category:'venda-pos',description:`Venda POS ${p.code}`,amountCents:p.amountCents,status:'liquidado',producerId,eventId:p.eventId,orderId:p.orderId}});return row});await audit(req,req.auth!.id,producerId,'create','pos-transaction',String(created.id));res.status(201).json(created)})
