export interface Producer {
  id: string;
  name: string;
  legalName: string;
  cnpj: string;
  logoInitial: string;
  activeEventsCount: number;
  totalEventsCount: number;
  verified: boolean;
  avatarColor: string;
}

export type NavigationPage = 
  | 'dashboard'
  | 'produtora'
  | 'status-faciais'
  | 'eventos'
  | 'nucleo-operacional'
  | 'dashboard-evento'
  | 'novo-evento'
  | 'editar-evento'
  | 'lotes'
  | 'participantes'
  | 'categorias-setores'
  | 'cupons'
  | 'cortesias'
  // Hub Financeiro & Modules
  | 'financeiro'
  | 'fin-hub'
  | 'fin-saldo'
  | 'fin-repasses'
  | 'fin-antecipacoes'
  | 'fin-extrato'
  | 'fin-despesas'
  | 'fin-contas'
  | 'fin-bordero'
  | 'fin-negociacoes'
  | 'fin-advanced'
  | 'fin-split'
  | 'fin-inteligencia'
  | 'fin-conciliacao'
  | 'fin-spread'
  | 'saldo'
  | 'vendas'
  | 'recebimentos'
  | 'repasses'
  | 'conciliacao'
  | 'fluxo-caixa'
  | 'extrato'
  // POS
  | 'terminais-pos'
  | 'pos-terminals'
  | 'pos-sales'
  | 'pos-closing'
  // Marketing (Fase 11)
  | 'marketing'
  | 'mkt-hub'
  | 'mkt-dashboard'
  | 'mkt-campaigns'
  | 'mkt-new-campaign'
  | 'mkt-automations'
  | 'mkt-whatsapp'
  | 'mkt-email'
  | 'mkt-coupons'
  | 'mkt-links'
  | 'mkt-affiliates'
  | 'mkt-analytics'
  | 'mkt-reports'
  | 'campanhas'
  | 'pixel-meta'
  | 'google-analytics'
  // Remarketing (Fase 11)
  | 'remarketing'
  | 'rmk-hub'
  | 'rmk-dashboard'
  | 'rmk-carts'
  | 'rmk-audiences'
  | 'rmk-segments'
  | 'rmk-flows'
  | 'rmk-whatsapp'
  | 'rmk-email'
  | 'rmk-payments'
  | 'rmk-inactive'
  | 'rmk-postevent'
  | 'rmk-automation'
  | 'rmk-reports'
  | 'mkt-abandoned'
  // Atendimento & Outros
  | 'atendimento'
  | 'mensagens'
  // Administração & Governança (Fase 8)
  | 'administracao'
  | 'admin-hub'
  | 'gerenciar-usuarios'
  | 'admin-users'
  | 'admin-producers'
  | 'admin-permissions'
  | 'logs-auditoria'
  | 'admin-audit'
  | 'admin-security'
  | 'gerenciar-acessos'
  | 'clube-beneficios';
