import { useEffect, useMemo, useState } from 'react'
import {
  WalletCards, Boxes, BookOpenCheck, Scale, FileText, Landmark, ReceiptText, BarChart3, FileSignature,
  LockKeyhole, Download, Plus, RefreshCw, CheckCircle2, AlertTriangle, Clock3, X, Sparkles, Search,
  CircleDollarSign, TrendingDown, TrendingUp, BadgeDollarSign, FileSpreadsheet, ShieldCheck
} from 'lucide-react'
import type { EventItem } from '../data/events'
import {
  getFinanceAccountingSummary, bootstrapFinanceAccounting, getCostCenters, createCostCenter, getChartAccounts,
  createChartAccount, getAccountingEntries, createAccountingEntry, getReconciliations, createReconciliation,
  reconcileItem, autoReconcile, getFinancialObligations, createFinancialObligation, payFinancialObligation,
  getBudgets, createBudgetLine, getBorderos, generateBordero, approveBordero, getSignatureRequests,
  createSignatureRequest, updateSignerStatus, getDreSummary, getFinancialClosings, createFinancialClosing,
  closeFinancialClosing, type FinanceAccountingSummary, type CostCenter, type ChartAccount, type AccountingEntry,
  type ReconciliationItem, type FinancialObligation, type BudgetLine, type BorderoDocument, type SignatureRequest,
  type DreSummary, type FinancialClosing
} from '../services/api'

type Tab='dashboard'|'cost-centers'|'accounts'|'entries'|'reconciliation'|'obligations'|'dre'|'borderos'|'signatures'|'closing'|'reports'
type Props={events:EventItem[];producerId:number|null;initialTab?:Tab;notify:(m:string)=>void;onBack?:()=>void}
const money=(c=0)=>(c/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
const tabs:Array<[Tab,string,any]>=[
 ['dashboard','Dashboard',WalletCards],['cost-centers','Centros de Custos',Boxes],['accounts','Plano de Contas',BookOpenCheck],
 ['entries','Lançamentos',FileText],['reconciliation','Conciliação',Scale],['obligations','Pagar & Receber',Landmark],
 ['dre','DRE & Orçamento',BarChart3],['borderos','Central de Borderôs',ReceiptText],['signatures','Documentos & Assinaturas',FileSignature],
 ['closing','Fechamento',LockKeyhole],['reports','Relatórios',FileSpreadsheet]
]
const reportTypes=['resumido','completo','detalhado','lote','setor','canal','pagamento','pdv','cortesias','cancelamentos','taxas','repasses','comissoes','conciliacao']

export default function FinanceAccountingHubPage({events,producerId,initialTab='dashboard',notify,onBack}:Props){
 const [tab,setTab]=useState<Tab>(initialTab),[eventId,setEventId]=useState<number|undefined>(events[0]?.id),[loading,setLoading]=useState(false),[q,setQ]=useState('')
 const [summary,setSummary]=useState<FinanceAccountingSummary|null>(null),[centers,setCenters]=useState<CostCenter[]>([]),[accounts,setAccounts]=useState<ChartAccount[]>([]),[entries,setEntries]=useState<AccountingEntry[]>([]),[recs,setRecs]=useState<ReconciliationItem[]>([]),[obligations,setObligations]=useState<FinancialObligation[]>([]),[budgets,setBudgets]=useState<BudgetLine[]>([]),[borderos,setBorderos]=useState<BorderoDocument[]>([]),[signatures,setSignatures]=useState<SignatureRequest[]>([]),[dre,setDre]=useState<DreSummary|null>(null),[closings,setClosings]=useState<FinancialClosing[]>([])
 const [modal,setModal]=useState<null|'center'|'account'|'entry'|'rec'|'obligation'|'budget'|'bordero'|'signature'|'closing'>(null)
 const event=events.find(e=>e.id===eventId)
 async function load(){setLoading(true);try{const [s,c,a,e,r,o,b,bo,si,d,cl]=await Promise.all([getFinanceAccountingSummary(producerId||undefined,eventId),getCostCenters(producerId||undefined,eventId),getChartAccounts(producerId||undefined),getAccountingEntries(producerId||undefined,eventId),getReconciliations(producerId||undefined,eventId),getFinancialObligations(producerId||undefined,eventId),getBudgets(producerId||undefined,eventId),getBorderos(producerId||undefined,eventId),getSignatureRequests(producerId||undefined,eventId),getDreSummary(producerId||undefined,eventId),getFinancialClosings(producerId||undefined,eventId)]);setSummary(s);setCenters(c);setAccounts(a);setEntries(e);setRecs(r);setObligations(o);setBudgets(b);setBorderos(bo);setSignatures(si);setDre(d);setClosings(cl)}catch(err:any){notify(err.message||'Erro ao carregar Financeiro Contábil.')}finally{setLoading(false)}}
 useEffect(()=>{load()},[eventId,producerId])
 const filtered=(rows:any[])=>!q?rows:rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q.toLowerCase()))
 const doBootstrap=async()=>{try{await bootstrapFinanceAccounting({producerId:producerId||undefined,eventId});notify('Plano de contas e centros padrão preparados.');await load()}catch(e:any){notify(e.message)}}
 const exportCsv=(name:string,rows:any[])=>{if(!rows.length)return notify('Não há dados para exportar.');const keys=Object.keys(rows[0]).filter(k=>typeof rows[0][k]!=='object');const esc=(v:any)=>`"${String(v??'').replaceAll('"','""')}"`;const csv=[keys.join(';'),...rows.map(r=>keys.map(k=>esc(r[k])).join(';'))].join('\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${name}-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url)}
 return <section className="fa-page">
  <div className="fa-header"><div>{onBack&&<button className="fa-back" onClick={onBack}>← Hub Financeiro</button>}<p className="eyebrow">FASE 18.4 · ERP FINANCEIRO & CONTÁBIL</p><h2>Hub Financeiro Contábil Completo</h2><p>Centro de custos, conciliação, plano de contas, DRE, borderôs, documentos, assinatura digital e fechamento.</p></div><div className="fa-header-actions"><select value={eventId||''} onChange={e=>setEventId(e.target.value?Number(e.target.value):undefined)}><option value="">Todos os eventos</option>{events.map(e=><option value={e.id} key={e.id}>{e.code} · {e.title}</option>)}</select><button className="secondary-btn" onClick={doBootstrap}><Sparkles size={15}/>Preparar estrutura</button><button className="secondary-btn" onClick={load}><RefreshCw size={15}/>Atualizar</button></div></div>
  <div className="fa-tabs">{tabs.map(([key,label,Icon])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}><Icon size={16}/>{label}</button>)}</div>
  <div className="fa-toolbar"><div className="fa-search"><Search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Pesquisar na área atual..."/></div><span>{event?`Evento: ${event.title}`:'Visão consolidada'}</span>{loading&&<small>Atualizando...</small>}</div>
  {tab==='dashboard'&&<Dashboard summary={summary} dre={dre} recs={recs} obligations={obligations} borderos={borderos} signatures={signatures}/>} 
  {tab==='cost-centers'&&<Panel title="Centro de Custos" subtitle="Estrutura hierárquica por evento, operação e departamento." action={<button className="primary-btn" onClick={()=>setModal('center')}><Plus size={15}/>Novo centro</button>}><Table headers={['Código','Centro','Tipo','Evento','Movimentos','Status']} rows={filtered(centers).map(c=>[c.code,c.name,c.type,c.event?.title||'Global',String((c._count?.entries||0)+(c._count?.obligations||0)),<Status value={c.status}/>])}/></Panel>}
  {tab==='accounts'&&<Panel title="Plano de Contas" subtitle="Contas sintéticas/analíticas para receitas, despesas, custos, ativo e passivo." action={<button className="primary-btn" onClick={()=>setModal('account')}><Plus size={15}/>Nova conta</button>}><Table headers={['Código','Conta','Natureza','Tipo','Nível','Status']} rows={filtered(accounts).map(a=>[a.code,a.name,a.nature,a.accountType,String(a.level),<Status value={a.status}/>])}/></Panel>}
  {tab==='entries'&&<Panel title="Lançamentos Contábeis" subtitle="Débitos, créditos, competência, origem e documento de referência." action={<button className="primary-btn" onClick={()=>setModal('entry')}><Plus size={15}/>Novo lançamento</button>}><Table headers={['Código','Competência','Descrição','Conta','Centro','Débito','Crédito','Status']} rows={filtered(entries).map(e=>[e.code,e.competence,e.description,e.chartAccount?.code||'—',e.costCenter?.name||'—',money(e.debitCents),money(e.creditCents),<Status value={e.status}/>])}/></Panel>}
  {tab==='reconciliation'&&<Panel title="Conciliação Contábil & Financeira" subtitle="Cruza pedidos, bancos, PIX, cartão, POS, split, taxas, repasses e recebíveis." action={<div className="fa-actions"><button className="secondary-btn" onClick={async()=>{try{const r=await autoReconcile({producerId:producerId||undefined,eventId});notify(`${r.created} pedidos conciliados automaticamente.`);load()}catch(e:any){notify(e.message)}}}><Sparkles size={15}/>Conciliação automática</button><button className="primary-btn" onClick={()=>setModal('rec')}><Plus size={15}/>Novo item</button></div>}><Table headers={['Código','Origem','Referência','Esperado','Recebido','Diferença','Status','Ação']} rows={filtered(recs).map(r=>[r.code,r.sourceType,r.sourceRef||'—',money(r.expectedCents),money(r.receivedCents),money(r.differenceCents),<Status value={r.status}/>,!['conciliado','conciliado-manual'].includes(r.status)?<button className="text-action" onClick={async()=>{try{await reconcileItem(r.id,{receivedCents:r.expectedCents,force:true,reason:'Conferência manual'});notify('Item conciliado.');load()}catch(e:any){notify(e.message)}}}>Conciliar</button>:'—'])}/></Panel>}
  {tab==='obligations'&&<Panel title="Contas a Pagar & Receber" subtitle="Compromissos, provisões, vencimentos, contrapartes e liquidação." action={<button className="primary-btn" onClick={()=>setModal('obligation')}><Plus size={15}/>Novo lançamento</button>}><Table headers={['Código','Tipo','Categoria','Descrição','Vencimento','Valor','Status','Ação']} rows={filtered(obligations).map(o=>[o.code,o.kind,o.category,o.description,new Date(o.dueDate).toLocaleDateString('pt-BR'),money(o.amountCents),<Status value={o.status}/>,o.status!=='pago'?<button className="text-action" onClick={async()=>{try{await payFinancialObligation(o.id);notify('Lançamento liquidado.');load()}catch(e:any){notify(e.message)}}}>Liquidar</button>:'—'])}/></Panel>}
  {tab==='dre'&&<DrePanel dre={dre} budgets={filtered(budgets)} onNew={()=>setModal('budget')}/>} 
  {tab==='borderos'&&<BorderoPanel rows={filtered(borderos)} onGenerate={()=>setModal('bordero')} onApprove={async id=>{try{await approveBordero(id);notify('Borderô aprovado e versionado.');load()}catch(e:any){notify(e.message)}}} onExport={()=>exportCsv('borderos',borderos)}/>} 
  {tab==='signatures'&&<SignaturePanel rows={filtered(signatures)} onNew={()=>setModal('signature')} onSign={async(rid,sid)=>{try{await updateSignerStatus(rid,sid,'assinado');notify('Assinatura registrada.');load()}catch(e:any){notify(e.message)}}}/>}
  {tab==='closing'&&<ClosingPanel rows={filtered(closings)} onNew={()=>setModal('closing')} onClose={async id=>{try{await closeFinancialClosing(id);notify('Competência fechada com auditoria.');load()}catch(e:any){notify(e.message)}}}/>}
  {tab==='reports'&&<Reports summary={summary} dre={dre} borderos={borderos} recs={recs} obligations={obligations} entries={entries} onExport={exportCsv}/>} 
  {modal&&<FinanceModal mode={modal} eventId={eventId} producerId={producerId} centers={centers} accounts={accounts} borderos={borderos} onClose={()=>setModal(null)} onSaved={async m=>{notify(m);setModal(null);await load()}}/>}
 </section>
}

function Dashboard({summary,dre,recs,obligations,borderos,signatures}:{summary:FinanceAccountingSummary|null;dre:DreSummary|null;recs:ReconciliationItem[];obligations:FinancialObligation[];borderos:BorderoDocument[];signatures:SignatureRequest[]}){const s=summary||{revenueCents:0,netRevenueCents:0,expensesCents:0,resultCents:0,reconciledCents:0,pendingCents:0,divergences:0,payablesCents:0,receivablesCents:0,borderos:0,signatures:0,costCenters:0,entries:0};return <><div className="fa-kpis"><Kpi icon={CircleDollarSign} label="Receita Bruta" value={money(s.revenueCents)}/><Kpi icon={TrendingDown} label="Despesas / Custos" value={money(s.expensesCents)}/><Kpi icon={TrendingUp} label="Resultado" value={money(s.resultCents)}/><Kpi icon={CheckCircle2} label="Conciliado" value={money(s.reconciledCents)}/><Kpi icon={AlertTriangle} label="Divergências" value={String(s.divergences)}/><Kpi icon={BadgeDollarSign} label="A Receber" value={money(s.receivablesCents)}/></div><div className="fa-grid-2"><Panel title="DRE Executiva" subtitle="Resultado econômico consolidado"><div className="fa-dre-lines"><Line l="Receita Bruta" v={money(dre?.grossRevenueCents||0)}/><Line l="(-) Deduções" v={money(dre?.deductionsCents||0)} neg/><Line l="Receita Líquida" v={money(dre?.netRevenueCents||0)} strong/><Line l="(-) Custos Operacionais" v={money(dre?.operatingCostsCents||0)} neg/><Line l="Resultado Operacional" v={money(dre?.operatingResultCents||0)} strong/><Line l="Margem" v={`${dre?.marginPercent||0}%`} strong/></div></Panel><Panel title="Saúde do Fechamento" subtitle="Pendências que impedem o encerramento"><div className="fa-health"><Health ok={s.divergences===0} label="Conciliação" detail={s.divergences?`${s.divergences} divergências`:'Sem divergências'}/><Health ok={!obligations.some(o=>o.status!=='pago'&&o.kind==='pagar')} label="Contas a pagar" detail={`${obligations.filter(o=>o.status!=='pago'&&o.kind==='pagar').length} pendentes`}/><Health ok={borderos.some(b=>['aprovado','assinado'].includes(b.status))} label="Borderô" detail={`${borderos.length} versões`}/><Health ok={signatures.some(s=>s.status==='assinado')} label="Assinaturas" detail={`${signatures.length} solicitações`}/></div></Panel></div><Panel title="Divergências recentes" subtitle="Itens que exigem conferência manual"><Table headers={['Código','Origem','Esperado','Recebido','Diferença','Status']} rows={recs.filter(r=>r.status==='divergente').slice(0,6).map(r=>[r.code,r.sourceType,money(r.expectedCents),money(r.receivedCents),money(r.differenceCents),<Status value={r.status}/>])}/></Panel></>}
function DrePanel({dre,budgets,onNew}:{dre:DreSummary|null;budgets:BudgetLine[];onNew:()=>void}){return <div className="fa-grid-2"><Panel title="DRE por Evento / Produtor" subtitle="Receita, deduções, custos e margem"><div className="fa-dre-lines"><Line l="Receita Bruta" v={money(dre?.grossRevenueCents||0)}/><Line l="(-) Deduções" v={money(dre?.deductionsCents||0)} neg/><Line l="Receita Líquida" v={money(dre?.netRevenueCents||0)} strong/><Line l="(-) Custos" v={money(dre?.operatingCostsCents||0)} neg/><Line l="Resultado" v={money(dre?.operatingResultCents||0)} strong/><Line l="Margem" v={`${dre?.marginPercent||0}%`} strong/></div></Panel><Panel title="Orçado x Realizado" subtitle="Controle por categoria e centro de custo" action={<button className="primary-btn" onClick={onNew}><Plus size={15}/>Nova linha</button>}><Table headers={['Competência','Categoria','Centro','Orçado','Realizado','Variação']} rows={budgets.map(b=>[b.competence,b.category,b.costCenter?.name||'—',money(b.plannedCents),money(b.realizedCents),money(b.plannedCents-b.realizedCents)])}/></Panel></div>}
function BorderoPanel({rows,onGenerate,onApprove,onExport}:{rows:BorderoDocument[];onGenerate:()=>void;onApprove:(id:number)=>void;onExport:()=>void}){return <Panel title="Central de Borderôs" subtitle="Resumido, completo, detalhado e relatórios por lote, setor, canal, pagamento, PDV, taxas, repasses e conciliação." action={<div className="fa-actions"><button className="secondary-btn" onClick={onExport}><Download size={15}/>Exportar lista</button><button className="primary-btn" onClick={onGenerate}><Plus size={15}/>Gerar borderô</button></div>}><Table headers={['Documento','Tipo','Versão','Evento','Gerado em','Status','Ação']} rows={rows.map(b=>[b.code,b.reportType,`v${b.version}`,b.event?.title||'—',new Date(b.generatedAt).toLocaleString('pt-BR'),<Status value={b.status}/>,b.status==='rascunho'?<button className="text-action" onClick={()=>onApprove(b.id)}>Aprovar</button>:'Oficial'])}/></Panel>}
function SignaturePanel({rows,onNew,onSign}:{rows:SignatureRequest[];onNew:()=>void;onSign:(rid:number,sid:number)=>void}){return <Panel title="Documentos & Assinatura Digital" subtitle="Camada multi-provedor pronta para Autentique, Clicksign, DocuSign ou aprovação interna." action={<button className="primary-btn" onClick={onNew}><Plus size={15}/>Nova assinatura</button>}><div className="fa-signature-grid">{rows.map(r=><article className="fa-sign-card" key={r.id}><div className="fa-card-top"><div><strong>{r.subject}</strong><small>{r.code} · {r.provider}</small></div><Status value={r.status}/></div>{r.bordero&&<p>Documento: {r.bordero.code}</p>}<div className="fa-signers">{r.signers.map(s=><div key={s.id}><span><b>{s.name}</b><small>{s.email} · {s.role||'Signatário'}</small></span>{s.status==='assinado'?<CheckCircle2 size={17}/>:r.provider==='interno'?<button className="text-action" onClick={()=>onSign(r.id,s.id)}>Assinar</button>:<Status value={s.status}/>}</div>)}</div>{r.hash&&<code>SHA-256: {r.hash.slice(0,26)}…</code>}</article>)}</div>{rows.length===0&&<Empty text="Nenhuma solicitação de assinatura criada."/>}</Panel>}
function ClosingPanel({rows,onNew,onClose}:{rows:FinancialClosing[];onNew:()=>void;onClose:(id:number)=>void}){return <Panel title="Fechamento Financeiro & Contábil" subtitle="Bloqueia competência após conciliação, aprovação do borderô e trilha de auditoria." action={<button className="primary-btn" onClick={onNew}><Plus size={15}/>Nova competência</button>}><Table headers={['Competência','Evento','Status','Fechado por','Fechado em','Ação']} rows={rows.map(c=>[c.competence,c.event?.title||'Consolidado',<Status value={c.status}/>,c.closedBy||'—',c.closedAt?new Date(c.closedAt).toLocaleString('pt-BR'):'—',c.status!=='fechado'?<button className="text-action" onClick={()=>onClose(c.id)}>Fechar competência</button>:'Bloqueado'])}/></Panel>}
function Reports({summary,dre,borderos,recs,obligations,entries,onExport}:{summary:FinanceAccountingSummary|null;dre:DreSummary|null;borderos:BorderoDocument[];recs:ReconciliationItem[];obligations:FinancialObligation[];entries:AccountingEntry[];onExport:(n:string,r:any[])=>void}){const cards=[['Borderôs resumidos',borderos.filter(b=>b.reportType==='resumido')],['Borderôs completos',borderos.filter(b=>b.reportType==='completo')],['Borderôs detalhados',borderos.filter(b=>b.reportType==='detalhado')],['Conciliação',recs],['Contas a pagar/receber',obligations],['Lançamentos contábeis',entries]] as Array<[string,any[]]>;return <><div className="fa-report-grid">{cards.map(([name,rows])=><article key={name}><FileSpreadsheet size={22}/><strong>{name}</strong><span>{rows.length} registros</span><button className="secondary-btn" onClick={()=>onExport(name.toLowerCase().replaceAll(' ','-'),rows)}><Download size={14}/>CSV</button></article>)}</div><Panel title="Resumo Executivo" subtitle="Base consolidada para PDF/Excel/BI"><div className="fa-report-summary"><Line l="Receita bruta" v={money(summary?.revenueCents||0)}/><Line l="Resultado" v={money(summary?.resultCents||0)} strong/><Line l="Margem DRE" v={`${dre?.marginPercent||0}%`}/><Line l="Divergências" v={String(summary?.divergences||0)}/><Line l="Borderôs" v={String(summary?.borderos||0)}/></div></Panel></>}

function FinanceModal({mode,eventId,producerId,centers,accounts,borderos,onClose,onSaved}:{mode:string;eventId?:number;producerId:number|null;centers:CostCenter[];accounts:ChartAccount[];borderos:BorderoDocument[];onClose:()=>void;onSaved:(m:string)=>void}){
 const [f,setF]=useState<Record<string,string>>({competence:new Date().toISOString().slice(0,7),dueDate:new Date().toISOString().slice(0,10),reportType:'completo',provider:'autentique',kind:'pagar',nature:'devedora',accountType:'despesa'}),[busy,setBusy]=useState(false);const set=(k:string,v:string)=>setF(x=>({...x,[k]:v}));const num=(k:string)=>Math.round(Number(f[k]||0)*100);async function save(){setBusy(true);try{const base={producerId:producerId||undefined,eventId};if(mode==='center')await createCostCenter({...base,code:f.code,name:f.name,description:f.description,type:f.type||'operacional'});if(mode==='account')await createChartAccount({producerId:producerId||undefined,code:f.code,name:f.name,nature:f.nature,accountType:f.accountType,level:Number(f.level||1)});if(mode==='entry')await createAccountingEntry({...base,description:f.description,competence:f.competence,debitCents:num('debit'),creditCents:num('credit'),costCenterId:f.costCenterId?Number(f.costCenterId):undefined,chartAccountId:f.chartAccountId?Number(f.chartAccountId):undefined,documentRef:f.documentRef});if(mode==='rec')await createReconciliation({...base,sourceType:f.sourceType||'banco',sourceRef:f.sourceRef,externalRef:f.externalRef,expectedCents:num('expected'),receivedCents:num('received'),reason:f.reason});if(mode==='obligation')await createFinancialObligation({...base,kind:f.kind,category:f.category,description:f.description,amountCents:num('amount'),dueDate:f.dueDate,counterparty:f.counterparty,costCenterId:f.costCenterId?Number(f.costCenterId):undefined,chartAccountId:f.chartAccountId?Number(f.chartAccountId):undefined});if(mode==='budget')await createBudgetLine({...base,competence:f.competence,category:f.category,plannedCents:num('planned'),realizedCents:num('realized'),costCenterId:f.costCenterId?Number(f.costCenterId):undefined});if(mode==='bordero'){if(!eventId)throw new Error('Selecione um evento para gerar o borderô.');await generateBordero({...base,eventId,reportType:f.reportType})}if(mode==='signature'){const signers=(f.signers||'').split(';').map(s=>s.trim()).filter(Boolean).map((s,i)=>{const [name,email,role]=s.split(',').map(v=>v.trim());return{name,email,role:role||`Signatário ${i+1}`}});if(!signers.length)throw new Error('Informe ao menos um signatário.');await createSignatureRequest({...base,borderoId:f.borderoId?Number(f.borderoId):undefined,provider:f.provider,subject:f.subject,message:f.message,signingOrder:f.signingOrder==='sim',signers})}if(mode==='closing')await createFinancialClosing({...base,competence:f.competence,notes:f.notes});onSaved('Operação salva com sucesso.')}catch(e:any){alert(e.message||'Não foi possível salvar.')}finally{setBusy(false)}}
 const title={center:'Novo Centro de Custos',account:'Nova Conta Contábil',entry:'Novo Lançamento Contábil',rec:'Novo Item de Conciliação',obligation:'Conta a Pagar / Receber',budget:'Nova Linha Orçamentária',bordero:'Gerar Borderô Oficial',signature:'Nova Solicitação de Assinatura',closing:'Nova Competência de Fechamento'}[mode]||'Novo registro'
 return <div className="fa-modal-back"><div className="fa-modal"><div className="fa-modal-head"><div><small>FASE 18.4</small><h3>{title}</h3></div><button onClick={onClose}><X/></button></div><div className="fa-form">
  {mode==='center'&&<><Field l="Código" v={f.code} on={v=>set('code',v)}/><Field l="Nome" v={f.name} on={v=>set('name',v)}/><Field l="Tipo" v={f.type||'operacional'} on={v=>set('type',v)} opts={['operacional','marketing','estrutura','comercial','administrativo']}/><Field l="Descrição" v={f.description} on={v=>set('description',v)}/></>}
  {mode==='account'&&<><Field l="Código" v={f.code} on={v=>set('code',v)}/><Field l="Nome da conta" v={f.name} on={v=>set('name',v)}/><Field l="Natureza" v={f.nature} on={v=>set('nature',v)} opts={['devedora','credora']}/><Field l="Tipo" v={f.accountType} on={v=>set('accountType',v)} opts={['ativo','passivo','receita','despesa','custo','patrimonio']}/><Field l="Nível" v={f.level||'1'} on={v=>set('level',v)} type="number"/></>}
  {mode==='entry'&&<><Field l="Descrição" v={f.description} on={v=>set('description',v)}/><Field l="Competência" v={f.competence} on={v=>set('competence',v)} type="month"/><Field l="Débito (R$)" v={f.debit} on={v=>set('debit',v)} type="number"/><Field l="Crédito (R$)" v={f.credit} on={v=>set('credit',v)} type="number"/><Field l="Centro de custo" v={f.costCenterId} on={v=>set('costCenterId',v)} opts={centers.map(c=>[String(c.id),`${c.code} · ${c.name}`])}/><Field l="Conta contábil" v={f.chartAccountId} on={v=>set('chartAccountId',v)} opts={accounts.map(a=>[String(a.id),`${a.code} · ${a.name}`])}/><Field l="Documento" v={f.documentRef} on={v=>set('documentRef',v)}/></>}
  {mode==='rec'&&<><Field l="Origem" v={f.sourceType||'banco'} on={v=>set('sourceType',v)} opts={['banco','cartao','pix','pos','split','repasse','taxa','pedido','recebivel']}/><Field l="Referência interna" v={f.sourceRef} on={v=>set('sourceRef',v)}/><Field l="Referência externa / NSU" v={f.externalRef} on={v=>set('externalRef',v)}/><Field l="Valor esperado (R$)" v={f.expected} on={v=>set('expected',v)} type="number"/><Field l="Valor recebido (R$)" v={f.received} on={v=>set('received',v)} type="number"/></>}
  {mode==='obligation'&&<><Field l="Tipo" v={f.kind} on={v=>set('kind',v)} opts={['pagar','receber']}/><Field l="Categoria" v={f.category} on={v=>set('category',v)}/><Field l="Descrição" v={f.description} on={v=>set('description',v)}/><Field l="Contraparte" v={f.counterparty} on={v=>set('counterparty',v)}/><Field l="Valor (R$)" v={f.amount} on={v=>set('amount',v)} type="number"/><Field l="Vencimento" v={f.dueDate} on={v=>set('dueDate',v)} type="date"/><Field l="Centro de custo" v={f.costCenterId} on={v=>set('costCenterId',v)} opts={centers.map(c=>[String(c.id),c.name])}/></>}
  {mode==='budget'&&<><Field l="Competência" v={f.competence} on={v=>set('competence',v)} type="month"/><Field l="Categoria" v={f.category} on={v=>set('category',v)}/><Field l="Orçado (R$)" v={f.planned} on={v=>set('planned',v)} type="number"/><Field l="Realizado (R$)" v={f.realized} on={v=>set('realized',v)} type="number"/><Field l="Centro de custo" v={f.costCenterId} on={v=>set('costCenterId',v)} opts={centers.map(c=>[String(c.id),c.name])}/></>}
  {mode==='bordero'&&<><Field l="Tipo de borderô" v={f.reportType} on={v=>set('reportType',v)} opts={reportTypes}/><div className="fa-info-box"><ShieldCheck size={18}/><span>O sistema captura um snapshot do evento, pedidos, ingressos, lotes, taxas, repasses, conciliação e obrigações para versionamento/auditoria.</span></div></>}
  {mode==='signature'&&<><Field l="Borderô" v={f.borderoId} on={v=>set('borderoId',v)} opts={borderos.map(b=>[String(b.id),`${b.code} · ${b.title}`])}/><Field l="Provedor" v={f.provider} on={v=>set('provider',v)} opts={['autentique','clicksign','docusign','interno']}/><Field l="Assunto" v={f.subject} on={v=>set('subject',v)}/><Field l="Signatários" v={f.signers} on={v=>set('signers',v)} placeholder="Nome,email,função; Outro,email,função"/><Field l="Ordem de assinatura" v={f.signingOrder||'nao'} on={v=>set('signingOrder',v)} opts={[['nao','Livre'],['sim','Sequencial']]}/><div className="fa-info-box"><FileSignature size={18}/><span>Autentique fica pronta para integração por providerDocumentId + webhook. Sem credenciais, a solicitação fica em “pronto-integracao”.</span></div></>}
  {mode==='closing'&&<><Field l="Competência" v={f.competence} on={v=>set('competence',v)} type="month"/><Field l="Observações" v={f.notes} on={v=>set('notes',v)}/><div className="fa-info-box"><LockKeyhole size={18}/><span>O fechamento bloqueia quando há divergências ou não existe borderô aprovado.</span></div></>}
 </div><div className="fa-modal-actions"><button className="secondary-btn" onClick={onClose}>Cancelar</button><button className="primary-btn" disabled={busy} onClick={save}>{busy?'Salvando...':'Confirmar'}</button></div></div></div>
}
function Field({l,v,on,type='text',opts,placeholder}:{l:string;v?:string;on:(v:string)=>void;type?:string;opts?:Array<string|[string,string]>;placeholder?:string}){return <label className="fa-field"><span>{l}</span>{opts?<select value={v||''} onChange={e=>on(e.target.value)}><option value="">Selecione</option>{opts.map((o,i)=>Array.isArray(o)?<option key={i} value={o[0]}>{o[1]}</option>:<option key={i} value={o}>{o}</option>)}</select>:<input type={type} step={type==='number'?'0.01':undefined} value={v||''} placeholder={placeholder} onChange={e=>on(e.target.value)}/>}</label>}
function Panel({title,subtitle,action,children}:{title:string;subtitle?:string;action?:any;children:any}){return <section className="fa-panel"><div className="fa-panel-head"><div><h3>{title}</h3>{subtitle&&<p>{subtitle}</p>}</div>{action}</div>{children}</section>}
function Table({headers,rows}:{headers:string[];rows:any[][]}){return <div className="fa-table-wrap"><table className="fa-table"><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table>{rows.length===0&&<Empty text="Nenhum registro encontrado."/>}</div>}
function Status({value}:{value:string}){const good=['ativo','pago','conciliado','conciliado-manual','aprovado','assinado','fechado','lancado'].includes(value);const bad=['divergente','cancelado','recusado','vencido'].includes(value);return <span className={`fa-status ${good?'good':bad?'bad':'warn'}`}>{value}</span>}
function Kpi({icon:Icon,label,value}:{icon:any;label:string;value:string}){return <article className="fa-kpi"><span><Icon size={18}/></span><small>{label}</small><strong>{value}</strong></article>}
function Line({l,v,strong,neg}:{l:string;v:string;strong?:boolean;neg?:boolean}){return <div className={`fa-line ${strong?'strong':''} ${neg?'neg':''}`}><span>{l}</span><b>{v}</b></div>}
function Health({ok,label,detail}:{ok:boolean;label:string;detail:string}){return <div className="fa-health-row">{ok?<CheckCircle2 className="ok"/>:<AlertTriangle className="no"/>}<span><b>{label}</b><small>{detail}</small></span></div>}
function Empty({text}:{text:string}){return <div className="fa-empty"><Clock3/><span>{text}</span></div>}
