import { FormEvent, useState } from 'react'
import { Eye, EyeOff, LockKeyhole, Mail, ShieldCheck } from 'lucide-react'
import type { AppUser } from '../auth/model'
type Props={onLogin:(email:string,password:string,remember:boolean)=>Promise<AppUser>}
export default function LoginPage({onLogin}:Props){
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[remember,setRemember]=useState(false),[show,setShow]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(false)
 const submit=async(e:FormEvent)=>{e.preventDefault();setLoading(true);setError('');try{await onLogin(email.trim(),password,remember)}catch(err){setError(err instanceof Error?err.message:'Falha no acesso.')}finally{setLoading(false)}}
 return <div className="login-page"><div className="login-aside"><div className="login-brand"><span>Di</span><strong>DiskIngressos</strong></div><div className="login-copy"><div className="login-shield"><ShieldCheck size={30}/></div><h1>Gestão segura para produtores e administradores.</h1><p>Autenticação validada no backend. Cada conta acessa somente os dados autorizados da sua produtora.</p><div className="security-points"><span>✓ Senhas com hash bcrypt</span><span>✓ JWT com expiração</span><span>✓ Isolamento multi-produtor na API</span><span>✓ Auditoria de acesso</span></div></div></div><main className="login-main"><form className="login-card" onSubmit={submit}><div className="login-card-head"><div className="mini-mark">Di</div><h2>Acesse sua conta</h2><p>Entre para acessar o painel DiskIngressos.</p></div><label>E-mail<div className="login-input"><Mail size={19}/><input value={email} onChange={e=>setEmail(e.target.value)} type="email" autoComplete="username" required/></div></label><label>Senha<div className="login-input"><LockKeyhole size={19}/><input value={password} onChange={e=>setPassword(e.target.value)} type={show?'text':'password'} autoComplete="current-password" required/><button type="button" onClick={()=>setShow(v=>!v)}>{show?<EyeOff size={19}/>:<Eye size={19}/>}</button></div></label><div className="login-options"><label className="remember-check"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/><span>Lembrar acesso</span></label><button type="button" className="forgot-link" onClick={()=>setError('Solicite a redefinição de senha ao administrador do sistema.')}>Esqueci minha senha</button></div>{error&&<div className="login-error">{error}</div>}<button className="login-submit" disabled={loading} type="submit">{loading?'Validando...':'Entrar no sistema'}</button><div className="demo-access"><b>Acessos após executar db:setup</b><small>Admin: admin@diskingressos.com.br / Admin@123</small><small>Produtor: vinicius@diskingressos.com.br / Produtor@123</small><small>Financeiro: financeiro@fep.com.br / Financeiro@123</small></div></form></main></div>
}
