import { useEffect, useMemo, useState } from 'react'
import { ArrowUpRight, BarChart3, Copy, Download, Link2, Megaphone, MousePointerClick, Plus, QrCode, Save, Settings2, TrendingUp, WalletCards } from 'lucide-react'
import type { EventItem } from '../data/events'
import AutomationCenterPage from './AutomationCenterPage'
import TrackingIntegrationsManager from '../components/TrackingIntegrationsManager'
import { createMarketingCampaign, createTrackingLink, getMarketingCampaigns, getResolvedTracking, getTrackingConfigs, getTrackingLinks, saveTrackingConfig, updateMarketingCampaign, type MarketingCampaign, type ResolvedTracking, type TrackingConfig, type TrackingLink } from '../services/api'

type Mode='hub'|'dashboard'|'campaigns'|'create'|'automations'|'whatsapp'|'email'|'coupons'|'links'|'affiliates'|'tracking'|'reports'
type Props={events:EventItem[];producerName:string;producerId:number|null;mode:Mode;notify:(m:string)=>void}
const dashboardCards=[{title:'Receita Gerada',value:'R$ 125.430',delta:'↑ 18,4%',icon:WalletCards},{title:'Conversões',value:'2.847',delta:'↑ 12,8%',icon:MousePointerClick},{title:'Taxa de Conversão',value:'4,82%',delta:'↑ 0,9%',icon:TrendingUp},{title:'ROI Marketing',value:'342%',delta:'↑ 22%',icon:BarChart3}]
const modules=[['Dashboard','KPIs, funil e desempenho geral.'],['Campanhas','Criação, agendamento e métricas.'],['Automações','Fluxos automáticos de comunicação.'],['WhatsApp','Campanhas e mensagens transacionais.'],['E-mail Marketing','Disparos e jornadas de e-mail.'],['Cupons e Promoções','Ofertas, vouchers e descontos.'],['Links, UTMs e QR Codes','Rastreamento de origem e conversão.'],['Afiliados e Parceiros','Performance de parceiros e comissões.'],['Pixel & Analytics','Meta, GA4, GTM e conversões.'],['Relatórios','ROI, ROAS, canais e exportações.']]
const providerLabels:Record<string,string>={meta_pixel:'Meta Pixel',ga4:'Google Analytics 4',gtm:'Google Tag Manager',google_ads:'Google Ads Conversion',whatsapp:'WhatsApp',email:'E-mail',automation_api:'APIs de Automação'}

export default function MarketingPage({events,producerName,producerId,mode,notify}:Props){
 const [eventId,setEventId]=useState<string>('all');const [period,setPeriod]=useState('30');
 const selectedEventId=eventId==='all'?undefined:Number(eventId);const eventName=useMemo(()=>eventId==='all'?'Todos os eventos':events.find(e=>String(e.id)===eventId)?.title||'Evento',[eventId,events])
 if(mode==='hub')return <section className="growth-page"><Context producerName={producerName} events={events} eventId={eventId} setEventId={setEventId} period={period} setPeriod={setPeriod}/><div className="growth-intro"><div><p className="eyebrow">MARKETING & GROWTH</p><h2>Hub Marketing</h2><p>Centralize aquisição, campanhas, automações, promoções e mensuração.</p></div></div><div className="module-card-grid">{modules.map(([title,desc])=><button key={title} className="finance-module-card marketing-card" onClick={()=>notify(`${title}: disponível no menu lateral.`)}><span className="module-card-icon"><Megaphone size={24}/></span><span><strong>{title}</strong><small>{desc}</small></span><ArrowUpRight size={18}/></button>)}</div></section>
 if(mode==='dashboard')return <Dashboard producerName={producerName} events={events} eventId={eventId} setEventId={setEventId} period={period} setPeriod={setPeriod} eventName={eventName} notify={notify}/>
 if(mode==='campaigns'||mode==='create')return <Campaigns producerId={producerId} events={events} initialEventId={selectedEventId} createOnly={mode==='create'} notify={notify}/>
 if(mode==='links')return <Links producerId={producerId} events={events} initialEventId={selectedEventId} notify={notify}/>
 if(mode==='tracking')return <Tracking producerId={producerId} events={events} initialEventId={selectedEventId} notify={notify}/>
 if(mode==='automations'||mode==='whatsapp'||mode==='email')return <AutomationCenterPage producerId={producerId} events={events} mode={mode} notify={notify}/>
 return <FeaturePage title={featureTitle(mode)} eventName={eventName} producerName={producerName} notify={notify}/>
}

function Dashboard({producerName,events,eventId,setEventId,period,setPeriod,eventName,notify}:any){return <section className="growth-page"><Context producerName={producerName} events={events} eventId={eventId} setEventId={setEventId} period={period} setPeriod={setPeriod}/><div className="growth-intro growth-actions"><div><p className="eyebrow">MARKETING & GROWTH</p><h2>Dashboard Marketing</h2><p>Acompanhe o desempenho das campanhas e vendas de {eventName.toLowerCase()}.</p></div><div className="page-actions"><button className="btn secondary" onClick={()=>notify('Relatório exportado (simulação).')}><Download size={17}/> Exportar</button><button className="btn primary" onClick={()=>notify('Use Criar Campanha no menu lateral.')}><Plus size={17}/> Criar Campanha</button></div></div><div className="growth-kpis">{dashboardCards.map(c=>{const I=c.icon;return <article className="growth-kpi" key={c.title}><div className="kpi-top"><span>{c.title}</span><I size={19}/></div><strong>{c.value}</strong><small>{c.delta} vs. período anterior</small></article>})}</div><div className="growth-grid"><article className="growth-panel"><div className="panel-head"><div><h3>Funil de conversão</h3><p>Da visita até a venda concluída</p></div></div><div className="funnel"><Funnel n="120.450" label="Visitantes" w="100%"/><Funnel n="48.320" label="Visualizações" w="82%"/><Funnel n="8.540" label="Checkout" w="63%"/><Funnel n="4.125" label="Pagamentos" w="46%"/><Funnel n="2.847" label="Vendas" w="32%"/></div></article><article className="growth-panel"><div className="panel-head"><div><h3>Conversões por canal</h3><p>Participação nas conversões</p></div></div><div className="channel-list">{[['Instagram',42],['Google',25],['WhatsApp',18],['E-mail',8],['Direto',7]].map(([n,v])=><div className="channel-row" key={String(n)}><div><span>{n}</span><b>{v}%</b></div><div className="channel-track"><i style={{width:`${v}%`}}/></div></div>)}</div></article></div></section>}

function Campaigns({producerId,events,initialEventId,createOnly,notify}:{producerId:number|null;events:EventItem[];initialEventId?:number;createOnly:boolean;notify:(m:string)=>void}){
 const [rows,setRows]=useState<MarketingCampaign[]>([]);const [loading,setLoading]=useState(true);const [eventId,setEventId]=useState<number|undefined>(initialEventId);const [form,setForm]=useState({name:'',channel:'instagram',objective:'conversao',budget:'',status:'rascunho'})
 const load=()=>{setLoading(true);getMarketingCampaigns(producerId||undefined,eventId).then(setRows).catch(e=>notify(e.message)).finally(()=>setLoading(false))};useEffect(()=>{load()},[producerId,eventId])
  const submit=async(e:React.FormEvent)=>{e.preventDefault();try{await createMarketingCampaign({name:form.name,channel:form.channel,objective:form.objective,status:form.status,budgetCents:Math.round(Number(form.budget||0)*100),producerId:producerId||undefined,eventId:eventId||undefined});setForm({...form,name:'',budget:''});notify('Campanha criada com sucesso.');load()}catch(err:any){notify(err.message)}}
  return <section className="growth-page"><div className="growth-intro"><div><p className="eyebrow">MARKETING & GROWTH</p><h2>{createOnly?'Criar Campanha':'Campanhas'}</h2><p>Campanhas persistidas na API, isoladas por produtora e evento.</p></div></div><div className="phase12-split"><form className="growth-panel phase12-form" onSubmit={submit}><h3>Nova campanha</h3><label>Evento<select value={eventId||''} onChange={e=>setEventId(e.target.value?Number(e.target.value):undefined)}><option value="">Sem evento específico</option>{events.map(ev=><option key={ev.id} value={ev.id}>{ev.title}</option>)}</select></label><label>Nome<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Ex.: Último Lote"/></label><div className="phase12-form-grid"><label>Canal<select value={form.channel} onChange={e=>setForm({...form,channel:e.target.value})}><option value="instagram">Instagram</option><option value="google">Google</option><option value="whatsapp">WhatsApp</option><option value="email">E-mail</option><option value="afiliados">Afiliados</option></select></label><label>Orçamento (R$)<input type="number" min="0" step="0.01" value={form.budget} onChange={e=>setForm({...form,budget:e.target.value})}/></label></div><button className="btn primary" type="submit"><Plus size={17}/> Criar campanha</button></form>{!createOnly&&<article className="growth-panel"><div className="panel-head"><div><h3>Campanhas cadastradas</h3><p>{loading?'Carregando...':`${rows.length} campanha(s)`}</p></div></div><div className="table-scroll"><table className="growth-table"><thead><tr><th>Campanha</th><th>Canal</th><th>Status</th><th>Evento</th><th>Receita</th><th>Conversões</th><th>Ação</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{r.name}</strong></td><td>{r.channel}</td><td><span className={`status-badge ${r.status==='ativa'?'green':'orange'}`}>{r.status}</span></td><td>{r.event?.title||'Todos'}</td><td>{money(r.revenueCents)}</td><td>{r.conversions}</td><td><button className="icon-action" onClick={async()=>{await updateMarketingCampaign(r.id,{status:r.status==='ativa'?'pausada':'ativa'});notify('Status atualizado.');load()}}>{r.status==='ativa'?'Pausar':'Ativar'}</button></td></tr>)}</tbody></table></div></article>}</div></section>
}

function Links({producerId,events,initialEventId,notify}:{producerId:number|null;events:EventItem[];initialEventId?:number;notify:(m:string)=>void}){
 const [rows,setRows]=useState<TrackingLink[]>([]);const [eventId,setEventId]=useState<number|undefined>(initialEventId);const [form,setForm]=useState({name:'',destination:'https://www.diskingressos.com.br/',source:'instagram',medium:'social',campaign:''})
 const load=()=>{getTrackingLinks(producerId||undefined,eventId).then(setRows).catch(e=>notify(e.message))};useEffect(()=>{load()},[producerId,eventId])
 const submit=async(e:React.FormEvent)=>{e.preventDefault();try{await createTrackingLink({...form,producerId:producerId||undefined,eventId:eventId||undefined});setForm({...form,name:'',campaign:''});notify('Link rastreável criado.');load()}catch(err:any){notify(err.message)}}
 return <section className="growth-page"><div className="growth-intro"><div><p className="eyebrow">TRACKING</p><h2>Links, UTMs e QR Codes</h2><p>Crie URLs rastreáveis por produtora e evento.</p></div></div><form className="growth-panel phase12-form" onSubmit={submit}><div className="phase12-form-grid"><label>Evento<select value={eventId||''} onChange={e=>setEventId(e.target.value?Number(e.target.value):undefined)}><option value="">Todos / institucional</option>{events.map(ev=><option value={ev.id} key={ev.id}>{ev.title}</option>)}</select></label><label>Nome<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label></div><label>URL de destino<input required type="url" value={form.destination} onChange={e=>setForm({...form,destination:e.target.value})}/></label><div className="phase12-form-grid three"><label>utm_source<input value={form.source} onChange={e=>setForm({...form,source:e.target.value})}/></label><label>utm_medium<input value={form.medium} onChange={e=>setForm({...form,medium:e.target.value})}/></label><label>utm_campaign<input value={form.campaign} onChange={e=>setForm({...form,campaign:e.target.value})}/></label></div><button className="btn primary" type="submit"><Link2 size={17}/> Gerar link</button></form><div className="phase12-link-grid">{rows.map(r=><article className="growth-panel tracking-link-card" key={r.id}><div className="tracking-link-title"><div><strong>{r.name}</strong><small>{r.event?.title||'Todos os eventos'}</small></div><QrCode size={30}/></div><code>{r.trackedUrl}</code><div className="tracking-link-stats"><span>{r.clicks} cliques</span><span>{r.conversions} conversões</span></div><div className="page-actions"><button className="btn secondary" onClick={()=>{navigator.clipboard?.writeText(r.trackedUrl);notify('URL copiada.')}}><Copy size={16}/> Copiar URL</button><button className="btn secondary" onClick={()=>{navigator.clipboard?.writeText(r.qrPayload);notify('Destino do QR copiado.')}}><QrCode size={16}/> QR destino</button></div></article>)}</div></section>
}

function Tracking({producerId,events,initialEventId,notify}:{producerId:number|null;events:EventItem[];initialEventId?:number;notify:(m:string)=>void}){
 return <section className="growth-page"><TrackingIntegrationsManager producerId={producerId} events={events} fixedEventId={initialEventId} notify={notify}/></section>
}

function Context({producerName,events,eventId,setEventId,period,setPeriod}:{producerName:string;events:EventItem[];eventId:string;setEventId:(v:string)=>void;period:string;setPeriod:(v:string)=>void}){return <div className="growth-context"><div><span>Produtor</span><strong>{producerName}</strong></div><label><span>Evento</span><select value={eventId} onChange={e=>setEventId(e.target.value)}><option value="all">Todos os eventos</option>{events.map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select></label><label><span>Período</span><select value={period} onChange={e=>setPeriod(e.target.value)}><option value="7">Últimos 7 dias</option><option value="30">Últimos 30 dias</option><option value="90">Últimos 90 dias</option></select></label></div>}
function Funnel({n,label,w}:{n:string;label:string;w:string}){return <div className="funnel-step" style={{width:w}}><span>{label}</span><b>{n}</b></div>}
function FeaturePage({title,eventName,producerName,notify}:{title:string;eventName:string;producerName:string;notify:(m:string)=>void}){return <section className="growth-page"><div className="growth-intro growth-actions"><div><p className="eyebrow">MARKETING & GROWTH</p><h2>{title}</h2><p>{producerName} · {eventName}</p></div><button className="btn primary" onClick={()=>notify(`${title}: próxima implementação do módulo.`)}><Plus size={17}/> Nova ação</button></div><article className="growth-panel feature-empty"><Megaphone size={34}/><h3>{title}</h3><p>Estrutura integrada ao template, permissões e contexto multi-produtor.</p><div className="feature-badges"><span>Multi-produtor</span><span>Contexto por evento</span><span>Permissões</span><span>Auditoria</span></div></article></section>}
function featureTitle(mode:Mode){const map:Record<string,string>={hub:'Hub Marketing',dashboard:'Dashboard Marketing',campaigns:'Campanhas',create:'Criar Campanha',automations:'Automações',whatsapp:'WhatsApp',email:'E-mail Marketing',coupons:'Cupons e Promoções',links:'Links, UTMs e QR Codes',affiliates:'Afiliados e Parceiros',tracking:'Pixel & Analytics',reports:'Relatórios'};return map[mode]||'Marketing'}
function money(cents:number){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(cents/100)}
