import { useEffect, useState } from 'react'
import { Mail, MessageCircle, RefreshCw, ShoppingCart, Target, TrendingUp, Send, Clock3, Link2 } from 'lucide-react'
import type { EventItem } from '../data/events'
import { getAutomationSummary, getRecoveries, markRecoveryRecovered, startRecovery, processRecoveryQueue, getRecoveryDashboard, type AutomationSummary, type RecoveryOpportunity, type RecoveryDashboard } from '../services/api'

type Mode='carts'|'flows'|'whatsapp'|'email'|'payments'|'inactive'|'postevent'|'automation'
type Props={producerId:number|null;events:EventItem[];mode:Mode;notify:(m:string)=>void}
const kindByMode:Partial<Record<Mode,string>>={carts:'carrinho',payments:'pagamento',inactive:'inativo',postevent:'pos_evento'}
export default function RecoveryCenterPage({producerId,mode,notify}:Props){
 const [rows,setRows]=useState<RecoveryOpportunity[]>([]);const [summary,setSummary]=useState<AutomationSummary|null>(null);const [dashboard,setDashboard]=useState<RecoveryDashboard|null>(null);const [busy,setBusy]=useState<number|null>(null);const kind=kindByMode[mode]
 const load=()=>Promise.all([getRecoveries(producerId||undefined,undefined,kind),getAutomationSummary(producerId||undefined),getRecoveryDashboard(producerId||undefined)]).then(([r,s,d])=>{setRows(r);setSummary(s);setDashboard(d)}).catch(e=>notify(e.message))
 useEffect(()=>{load()},[producerId,mode])
 const begin=async(r:RecoveryOpportunity)=>{try{setBusy(r.id);await startRecovery(r.id);notify('Recuperação adicionada à fila de comunicação.');await load()}catch(e:any){notify(e.message)}finally{setBusy(null)}}
 const recover=async(r:RecoveryOpportunity)=>{try{setBusy(r.id);await markRecoveryRecovered(r.id);notify('Venda recuperada e receita atribuída à campanha original.');await load()}catch(e:any){notify(e.message)}finally{setBusy(null)}}
 const process=async()=>{try{const r=await processRecoveryQueue();notify(`${r.sent} mensagem(ns) processada(s) na fila.`);await load()}catch(e:any){notify(e.message)}}
 return <section className="growth-page"><div className="growth-intro"><div><p className="eyebrow remarketing">REMARKETING AUTOMÁTICO · FASE 16.6</p><h2>{title(mode)}</h2><p>Carrinho abandonado → WhatsApp/E-mail → recuperação → receita atribuída à UTM original.</p></div><button className="primary-btn" onClick={process}><Send size={17}/> Processar fila</button></div>
 <div className="growth-kpis"><Kpi label="Oportunidades abertas" value={String(dashboard?.open??summary?.openRecoveries??0)} icon={ShoppingCart}/><Kpi label="Em recuperação" value={String(dashboard?.inRecovery||0)} icon={Clock3}/><Kpi label="Potencial" value={money(dashboard?.potentialCents??summary?.potentialCents??0)} icon={Target}/><Kpi label="Receita recuperada" value={money(dashboard?.recoveredCents??summary?.recoveredCents??0)} icon={TrendingUp}/></div>
 {dashboard?.campaigns?.length? <article className="growth-panel"><div className="panel-head"><div><h3>Receita recuperada por campanha UTM</h3><p>A recuperação mantém a origem do link que iniciou a jornada.</p></div></div><div className="recovery-campaign-grid">{dashboard.campaigns.slice(0,6).map(c=><div className="recovery-campaign" key={c.campaign}><span><Link2 size={16}/> {c.campaign}</span><strong>{money(c.revenueCents)}</strong><small>{c.recovered}/{c.opportunities} recuperadas · {c.source||'origem não informada'}</small></div>)}</div></article>:null}
 <article className="growth-panel"><div className="panel-head"><div><h3>{title(mode)}</h3><p>{rows.length} registro(s) no contexto atual</p></div></div><div className="table-scroll"><table className="growth-table"><thead><tr><th>Cliente</th><th>Evento / UTM</th><th>Tipo</th><th>Canal</th><th>Valor</th><th>Jornada</th><th>Status</th><th>Ação</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{r.customerName}</strong><small className="phase13-cell-sub">{r.email||r.phone||r.code}</small></td><td><strong>{r.event?.title||'—'}</strong><small className="phase13-cell-sub">{r.trackingLink?`${r.trackingLink.source||'utm'} / ${r.trackingLink.campaign||r.trackingLink.name}`:'Sem UTM vinculada'}</small></td><td>{kindLabel(r.kind)}</td><td><span className="phase13-channel">{r.preferredChannel==='email'?<Mail size={15}/>:<MessageCircle size={15}/>} {r.preferredChannel}</span></td><td>{money(r.amountCents)}</td><td><small>{r.attemptCount||0} tentativa(s)</small>{r.attempts?.[0]?<small className="phase13-cell-sub">Última: {r.attempts[0].status}</small>:null}</td><td><span className={`status-badge ${r.status==='recuperado'?'green':r.status==='em_recuperacao'?'blue':'orange'}`}>{r.status.replace('_',' ')}</span></td><td><div className="row-actions">{r.status==='aberto'?<button disabled={busy===r.id} className="icon-action" onClick={()=>begin(r)}><Send size={14}/> Recuperar</button>:null}{r.status==='em_recuperacao'?<button disabled={busy===r.id} className="icon-action" onClick={()=>recover(r)}><RefreshCw size={14}/> Marcar venda</button>:null}{r.status==='recuperado'?<strong className="recovered-value">{money(r.revenueCents)}</strong>:null}</div></td></tr>)}</tbody></table></div></article></section>
}
function Kpi({label,value,icon:Icon}:{label:string;value:string;icon:any}){return <article className="growth-kpi"><div className="kpi-top"><span>{label}</span><Icon size={19}/></div><strong>{value}</strong><small>Atualização via API</small></article>}
function title(m:Mode){return ({carts:'Carrinhos Abandonados',flows:'Fluxos de Recuperação',whatsapp:'WhatsApp Remarketing',email:'E-mail Remarketing',payments:'Recuperação de Pagamento',inactive:'Clientes Inativos',postevent:'Pós-Evento',automation:'Remarketing Automático'})[m]}
function kindLabel(v:string){return ({carrinho:'Carrinho',pagamento:'Pagamento',inativo:'Cliente inativo',pos_evento:'Pós-evento'})[v as 'carrinho']||v}
function money(cents:number){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(cents/100)}
