import { ArrowUpRight, Clock3, Mail, MessageCircle, Repeat2, ShoppingCart, Target, TrendingUp, Users } from 'lucide-react'
import type { EventItem } from '../data/events'
import RecoveryCenterPage from './RecoveryCenterPage'

type Mode='hub'|'dashboard'|'carts'|'audiences'|'segments'|'flows'|'whatsapp'|'email'|'payments'|'inactive'|'postevent'|'automation'|'reports'
type Props={events:EventItem[];producerName:string;producerId:number|null;mode:Mode;notify:(m:string)=>void}
const modules=[['Dashboard','Recuperação, receita e conversão.'],['Carrinhos Abandonados','Sessões interrompidas e recuperação.'],['Públicos','Audiências prontas para ativação.'],['Segmentações','Regras e grupos inteligentes.'],['Fluxos de Recuperação','Jornadas automatizadas multicanal.'],['WhatsApp Remarketing','Mensagens de recuperação.'],['E-mail Remarketing','Jornadas e campanhas de retorno.'],['Recuperação de Pagamento','PIX, cartão e pagamentos pendentes.'],['Clientes Inativos','Reativação e recorrência.'],['Pós-Evento','Relacionamento depois do evento.'],['Remarketing Automático','Gatilhos e regras contínuas.'],['Relatórios','Performance e receita recuperada.']]
export default function RemarketingPage({events,producerName,producerId,mode,notify}:Props){
 if(mode==='hub')return <section className="growth-page"><div className="growth-intro"><div><p className="eyebrow remarketing">REMARKETING</p><h2>Hub Remarketing</h2><p>Recupere oportunidades e reengaje participantes com fluxos automatizados.</p></div></div><div className="module-card-grid">{modules.map(([title,desc])=><button key={title} className="finance-module-card remarketing-card" onClick={()=>notify(`${title}: módulo disponível no menu lateral.`)}><span className="module-card-icon"><Repeat2 size={24}/></span><span><strong>{title}</strong><small>{desc}</small></span><ArrowUpRight size={18}/></button>)}</div></section>
 if(['carts','flows','whatsapp','email','payments','inactive','postevent','automation'].includes(mode))return <RecoveryCenterPage producerId={producerId} events={events} mode={mode as any} notify={notify}/>
 if(mode!=='dashboard')return <section className="growth-page"><div className="growth-intro"><div><p className="eyebrow remarketing">REMARKETING</p><h2>{title(mode)}</h2><p>{producerName} · dados limitados aos eventos autorizados ({events.length}).</p></div></div><article className="growth-panel feature-empty"><Repeat2 size={34}/><h3>{title(mode)}</h3><p>Módulo preparado no template global com isolamento por produtora e contexto por evento.</p></article></section>
 return <section className="growth-page"><div className="growth-intro"><div><p className="eyebrow remarketing">REMARKETING</p><h2>Dashboard Remarketing</h2><p>Visão consolidada das oportunidades de recuperação e reengajamento.</p></div></div><div className="growth-kpis"><Kpi icon={ShoppingCart} label="Carrinhos abandonados" value="1.248" sub="R$ 86.420 em potencial"/><Kpi icon={TrendingUp} label="Receita recuperada" value="R$ 31.580" sub="↑ 21,6% no período"/><Kpi icon={Target} label="Taxa de recuperação" value="18,7%" sub="234 vendas recuperadas"/><Kpi icon={Users} label="Públicos ativos" value="12" sub="8 automações em execução"/></div><div className="growth-grid"><article className="growth-panel"><div className="panel-head"><div><h3>Recuperação por canal</h3><p>Participação na receita recuperada</p></div></div><div className="remarketing-channel"><Channel icon={MessageCircle} name="WhatsApp" value="R$ 17.420" pct="55%"/><Channel icon={Mail} name="E-mail" value="R$ 8.840" pct="28%"/><Channel icon={Clock3} name="Recuperação de pagamento" value="R$ 5.320" pct="17%"/></div></article><article className="growth-panel"><div className="panel-head"><div><h3>Fluxos ativos</h3><p>Automações com melhor desempenho</p></div></div><div className="flow-list">{[['Carrinho 30 min','124 recuperações','Ativo'],['PIX pendente 15 min','68 recuperações','Ativo'],['Último lote','42 recuperações','Ativo'],['Pós-evento +30 dias','1.480 contatos','Ativo']].map(r=><div className="flow-row" key={r[0]}><span><b>{r[0]}</b><small>{r[1]}</small></span><i>{r[2]}</i></div>)}</div></article></div></section>
}
function Kpi({icon:Icon,label,value,sub}:{icon:any;label:string;value:string;sub:string}){return <article className="growth-kpi"><div className="kpi-top"><span>{label}</span><Icon size={19}/></div><strong>{value}</strong><small>{sub}</small></article>}
function Channel({icon:Icon,name,value,pct}:{icon:any;name:string;value:string;pct:string}){return <div className="remarketing-channel-row"><span className="channel-icon"><Icon size={20}/></span><div><b>{name}</b><small>{value}</small></div><strong>{pct}</strong></div>}
function title(mode:Mode){return ({hub:'Hub Remarketing',dashboard:'Dashboard Remarketing',carts:'Carrinhos Abandonados',audiences:'Públicos',segments:'Segmentações',flows:'Fluxos de Recuperação',whatsapp:'WhatsApp Remarketing',email:'E-mail Remarketing',payments:'Recuperação de Pagamento',inactive:'Clientes Inativos',postevent:'Pós-Evento',automation:'Remarketing Automático',reports:'Relatórios'} as Record<string,string>)[mode]||'Remarketing'}
