import { useState } from 'react'
import { LockKeyhole, TimerReset, ShieldAlert, KeyRound, ArrowLeft } from 'lucide-react'
export default function SecurityPage({notify,onNavigate}:{notify:(m:string)=>void;onNavigate?:(page:any)=>void}){const [cfg,setCfg]=useState({mfa:true,strong:true,lock:true,audit:true,minutes:30,attempts:5});const Toggle=({k,label,desc}:{k:'mfa'|'strong'|'lock'|'audit';label:string;desc:string})=><label className="security-setting"><span><strong>{label}</strong><small>{desc}</small></span><input type="checkbox" checked={cfg[k]} onChange={e=>setCfg({...cfg,[k]:e.target.checked})}/></label>;return <div className="security-page">
  <div className="flex items-center gap-2 mb-3">
    <button
      onClick={()=>onNavigate?onNavigate('admin-hub'):window.history.back()}
      className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-lg text-xs font-bold bg-[#1e293b] hover:bg-[#334155] text-slate-300 hover:text-white border border-slate-700/80 transition cursor-pointer"
    >
      <ArrowLeft size={14} className="text-[#06B6D4]"/>
      <span>Voltar ao Menu Administração</span>
    </button>
  </div>
  <div className="users-toolbar"><div><p className="eyebrow">PROTEÇÃO DA PLATAFORMA</p><h2>Configurações de Segurança</h2><p>Políticas globais para autenticação, sessões e rastreabilidade.</p></div><button className="primary-btn" onClick={()=>notify('Políticas de segurança salvas no protótipo.')}>Salvar políticas</button></div><div className="security-grid"><section className="security-card"><div className="security-card-title"><KeyRound/><div><strong>Autenticação</strong><small>Regras aplicadas a todos os usuários</small></div></div><Toggle k="strong" label="Senha forte obrigatória" desc="Mínimo de 8 caracteres, número e símbolo."/><Toggle k="mfa" label="MFA para administradores" desc="Exigir segundo fator para perfis administrativos."/></section><section className="security-card"><div className="security-card-title"><TimerReset/><div><strong>Sessões</strong><small>Tempo e tentativas de acesso</small></div></div><label className="security-number">Expirar sessão após <input type="number" min="5" max="480" value={cfg.minutes} onChange={e=>setCfg({...cfg,minutes:Number(e.target.value)})}/> minutos</label><label className="security-number">Bloquear após <input type="number" min="3" max="20" value={cfg.attempts} onChange={e=>setCfg({...cfg,attempts:Number(e.target.value)})}/> tentativas</label><Toggle k="lock" label="Bloqueio automático" desc="Suspender temporariamente contas após falhas consecutivas."/></section><section className="security-card"><div className="security-card-title"><ShieldAlert/><div><strong>Auditoria e isolamento</strong><small>Proteção multi-produtor</small></div></div><Toggle k="audit" label="Registrar operações críticas" desc="Usuário, produtora, horário, ação e resultado."/><div className="security-note"><LockKeyhole size={18}/><span>O <b>producer_id</b> deve ser obtido da sessão autenticada no backend, nunca do navegador.</span></div></section></div></div>}
