import { useEffect,useMemo,useState, type FormEvent } from 'react'
import { BarChart3, BookOpen, Clock3, Headphones, Link2, Plus, RefreshCw, ShieldCheck, TicketCheck } from 'lucide-react'
import { createSupportTicket,getSlaPolicies,getSupportIntegrations,getSupportSummary,getSupportTickets,updateSupportTicket,type SupportSummary,type SupportTicket,type SlaPolicy,type SupportIntegration } from '../services/api'
import type { EventItem } from '../data/events'

type Mode='hub'|'dashboard'|'tickets'|'new'|'sla'|'integrations'|'knowledge'|'reports'
type Props={mode:Mode;producerId:number|null;producerName:string;events:EventItem[];notify:(m:string)=>void;onNavigate?:(key:any)=>void}
const minutes=(v:number)=>v<60?`${v} min`:v<1440?`${Math.round(v/60)} h`:`${Math.round(v/1440)} dias`
export default function SupportPage({mode,producerId,producerName,events,notify,onNavigate}:Props){
 const [tickets,setTickets]=useState<SupportTicket[]>([]),[summary,setSummary]=useState<SupportSummary>({total:0,open:0,p1:0,overdue:0,resolved:0,slaCompliance:100}),[policies,setPolicies]=useState<SlaPolicy[]>([]),[integrations,setIntegrations]=useState<SupportIntegration[]>([]),[loading,setLoading]=useState(false)
 const [form,setForm]=useState({subject:'',description:'',category:'incidente',impact:'medio',urgency:'media',channel:'portal',eventId:'',requesterName:'',requesterEmail:'',requesterPhone:'',assignedTo:''})
 const load=async()=>{setLoading(true);try{const [a,b,c,d]=await Promise.all([getSupportTickets(producerId||undefined),getSupportSummary(producerId||undefined),getSlaPolicies(producerId||undefined),getSupportIntegrations(producerId||undefined)]);setTickets(a);setSummary(b);setPolicies(c);setIntegrations(d)}catch(e:any){notify(e.message||'Não foi possível carregar o SAC.')}finally{setLoading(false)}}
 useEffect(()=>{load()},[producerId])
 const open=tickets.filter(t=>!['resolvido','fechado'].includes(t.status)); const byPriority=useMemo(()=>['P1','P2','P3','P4'].map(p=>({p,n:open.filter(t=>t.priority===p).length})),[tickets])
 const create=async(e:FormEvent)=>{e.preventDefault();try{await createSupportTicket({...form,eventId:form.eventId?Number(form.eventId):null,producerId:producerId||undefined});notify('Chamado aberto com SLA calculado automaticamente.');setForm({...form,subject:'',description:'',requesterName:'',requesterEmail:'',requesterPhone:''});await load()}catch(err:any){notify(err.message||'Erro ao abrir chamado.')}}
 const changeStatus=async(t:SupportTicket,status:string)=>{try{await updateSupportTicket(t.id,{status,producerId:producerId||undefined});notify(`Chamado ${t.code} atualizado.`);await load()}catch(err:any){notify(err.message||'Falha ao atualizar chamado.')}}
 if(mode==='hub')return <div className="support-page"><Context producerName={producerName}/><section className="growth-intro"><div><p className="eyebrow">ATENDIMENTO / SAC</p><h2>Hub de Atendimento</h2><p>Central ITIL para incidentes, solicitações, SLA, integrações e experiência do participante.</p></div></section><div className="support-hub-grid">{[
  ['sac-dashboard','Dashboard SAC','Indicadores, SLA, prioridades e desempenho.',BarChart3],['sac-tickets','Chamados','Fila omnichannel e gestão do ciclo de vida.',Headphones],['sac-new','Abrir Chamado','Registro rápido com impacto, urgência e evento.',Plus],['sac-sla','SLA & ITIL','Políticas P1–P4, tempos e escalonamento.',Clock3],['sac-integrations','Integrações','WhatsApp, e-mail, vendas, financeiro e eventos.',Link2],['sac-knowledge','Base de Conhecimento','Artigos, procedimentos, erros conhecidos e FAQ.',BookOpen],['sac-reports','Relatórios','SLA, volume, backlog, FCR, CSAT e produtividade.',TicketCheck]
 ].map(([key,title,desc,Icon]:any)=><button key={key} className="support-hub-card" onClick={()=>onNavigate?.(key)}><span className="support-hub-icon"><Icon size={24}/></span><span><strong>{title}</strong><small>{desc}</small></span></button>)}</div></div>
 if(mode==='new')return <div className="support-page"><Context producerName={producerName}/><section className="growth-panel"><div className="panel-head"><h3>Abrir novo chamado</h3><p>A prioridade é calculada pela matriz ITIL de impacto × urgência e o SLA começa automaticamente.</p></div><form className="support-form" onSubmit={create}><label>Solicitante<input required value={form.requesterName} onChange={e=>setForm({...form,requesterName:e.target.value})}/></label><label>E-mail<input type="email" value={form.requesterEmail} onChange={e=>setForm({...form,requesterEmail:e.target.value})}/></label><label>Telefone<input value={form.requesterPhone} onChange={e=>setForm({...form,requesterPhone:e.target.value})}/></label><label>Evento<select value={form.eventId} onChange={e=>setForm({...form,eventId:e.target.value})}><option value="">Sem evento específico</option>{events.map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select></label><label>Tipo<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option value="incidente">Incidente</option><option value="requisicao">Requisição de serviço</option><option value="problema">Problema</option><option value="acesso">Acesso</option><option value="financeiro">Financeiro</option><option value="ingresso">Ingresso</option></select></label><label>Canal<select value={form.channel} onChange={e=>setForm({...form,channel:e.target.value})}><option>portal</option><option>whatsapp</option><option>email</option><option>telefone</option><option>presencial</option></select></label><label>Impacto<select value={form.impact} onChange={e=>setForm({...form,impact:e.target.value})}><option value="baixo">Baixo</option><option value="medio">Médio</option><option value="alto">Alto</option><option value="critico">Crítico</option></select></label><label>Urgência<select value={form.urgency} onChange={e=>setForm({...form,urgency:e.target.value})}><option value="baixa">Baixa</option><option value="media">Média</option><option value="alta">Alta</option><option value="critica">Crítica</option></select></label><label className="wide">Assunto<input required value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}/></label><label className="wide">Descrição<textarea required rows={6} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="wide"><button className="btn primary" type="submit"><Plus size={17}/>Abrir chamado</button></div></form></section></div>
 if(mode==='sla')return <div className="support-page"><Context producerName={producerName}/><section className="growth-intro"><div><p className="eyebrow">GESTÃO DE NÍVEL DE SERVIÇO</p><h2>SLA & ITIL</h2><p>Prioridade baseada em impacto × urgência, com metas de primeira resposta e resolução.</p></div></section><div className="sla-grid">{policies.map(p=><article className={`sla-card ${p.priority.toLowerCase()}`} key={p.id}><div><strong>{p.priority}</strong><span>{p.name}</span></div><dl><div><dt>Primeira resposta</dt><dd>{minutes(p.responseMinutes)}</dd></div><div><dt>Resolução</dt><dd>{minutes(p.resolutionMinutes)}</dd></div><div><dt>Calendário</dt><dd>{p.businessHours}</dd></div></dl></article>)}</div><section className="growth-panel"><div className="panel-head"><h3>Práticas ITIL incorporadas</h3><p>Fluxo base para operação do service desk.</p></div><div className="itil-grid">{['Gestão de Incidentes','Requisição de Serviço','Gestão de Problemas','Gestão de Acesso','Conhecimento / KEDB','Escalonamento funcional','Escalonamento hierárquico','Medição de SLA','Auditoria e histórico','Melhoria contínua'].map(x=><span key={x}><ShieldCheck size={16}/>{x}</span>)}</div></section></div>
 if(mode==='integrations')return <div className="support-page"><Context producerName={producerName}/><section className="growth-intro"><div><p className="eyebrow">INTEGRAÇÕES</p><h2>SAC Omnichannel</h2><p>Um chamado pode nascer ou ser enriquecido a partir dos demais módulos da plataforma.</p></div></section><div className="integration-grid">{integrations.map(i=><article className="integration-card" key={i.id}><span><Link2 size={21}/></span><div><strong>{i.name}</strong><small>{i.description}</small></div><i>{i.status}</i></article>)}</div><section className="growth-panel"><div className="panel-head"><h3>Integração interna do DiskIngressos</h3></div><div className="itil-grid">{['Eventos e lotes','Pedido e pagamento','Ingresso / QR Code','Participante','Check-in','Financeiro e repasses','Marketing / Remarketing','Usuários e permissões'].map(x=><span key={x}><RefreshCw size={15}/>{x}</span>)}</div></section></div>
 if(mode==='knowledge')return <div className="support-page"><Context producerName={producerName}/><section className="growth-panel"><div className="panel-head"><h3>Base de Conhecimento</h3><p>Estrutura ITIL para soluções reutilizáveis, FAQ, procedimentos e erros conhecidos.</p></div><div className="knowledge-grid">{['Como reenviar um ingresso','Pagamento PIX não identificado','Alterar titularidade','Solicitar estorno','Falha no check-in','Acesso do produtor','Repasse financeiro','Configuração de Pixel'].map((x,i)=><article key={x}><BookOpen size={18}/><div><strong>{x}</strong><small>{i%3===0?'Procedimento':'Artigo de suporte'} · Revisado</small></div></article>)}</div></section></div>
 if(mode==='reports')return <div className="support-page"><Context producerName={producerName}/><Kpis summary={summary}/><div className="growth-grid"><section className="growth-panel"><div className="panel-head"><h3>Backlog por prioridade</h3><p>Chamados ainda não resolvidos.</p></div><div className="priority-bars">{byPriority.map(x=><div key={x.p}><span>{x.p}</span><i><b style={{width:`${Math.min(100,x.n*18)}%`}}/></i><strong>{x.n}</strong></div>)}</div></section><section className="growth-panel"><div className="panel-head"><h3>Indicadores recomendados</h3></div><div className="metric-list"><span>FCR — resolução no primeiro contato</span><span>MTTA — tempo médio até atendimento</span><span>MTTR — tempo médio de resolução</span><span>CSAT — satisfação do atendimento</span><span>Taxa de reabertura</span><span>Backlog envelhecido</span></div></section></div></div>
 return <div className="support-page"><Context producerName={producerName}/><section className="growth-intro"><div><p className="eyebrow">SERVICE DESK</p><h2>{mode==='dashboard'?'Dashboard SAC':'Chamados'}</h2><p>{mode==='dashboard'?'Visão operacional de SLA, prioridades, backlog e atendimento.':'Fila centralizada de solicitações e incidentes.'}</p></div><div className="page-actions"><button className="btn secondary" onClick={load}><RefreshCw size={16}/>{loading?'Atualizando...':'Atualizar'}</button><button className="btn primary" onClick={()=>onNavigate?.('sac-new')}><Plus size={16}/>Abrir chamado</button></div></section><Kpis summary={summary}/><section className="growth-panel"><div className="table-scroll"><table className="growth-table support-table"><thead><tr><th>Chamado</th><th>Solicitante</th><th>Tipo</th><th>Prioridade</th><th>Status</th><th>SLA Resolução</th><th>Ações</th></tr></thead><tbody>{tickets.map(t=><tr key={t.id}><td><strong>{t.code}</strong><small className="phase13-cell-sub">{t.subject}</small></td><td>{t.requesterName}</td><td>{t.category}</td><td><span className={`priority-badge ${t.priority.toLowerCase()}`}>{t.priority}</span></td><td><span className={`status-badge ${t.status==='resolvido'||t.status==='fechado'?'green':t.status==='em-atendimento'?'orange':''}`}>{t.status}</span></td><td>{new Date(t.resolutionDueAt).toLocaleString('pt-BR')}<small className="phase13-cell-sub">{new Date(t.resolutionDueAt).getTime()<Date.now()&&!['resolvido','fechado'].includes(t.status)?'⚠ SLA vencido':'Dentro da meta'}</small></td><td><div className="phase13-row-actions">{t.status==='aberto'&&<button className="icon-action" onClick={()=>changeStatus(t,'em-atendimento')}>Atender</button>}{!['resolvido','fechado'].includes(t.status)&&<button className="icon-action" onClick={()=>changeStatus(t,'resolvido')}>Resolver</button>}</div></td></tr>)}</tbody></table>{!tickets.length&&<div className="feature-empty"><Headphones size={32}/><h3>Nenhum chamado</h3><p>Abra o primeiro chamado para iniciar a operação do SAC.</p></div>}</div></section></div>
}
function Context({producerName}:{producerName:string}){return <div className="growth-context"><div><span>Produtora</span><strong>{producerName}</strong></div><div><span>Modelo de serviço</span><strong>ITIL · Service Desk</strong></div></div>}
function Kpis({summary}:{summary:SupportSummary}){return <div className="support-kpis"><article><span>Chamados abertos</span><strong>{summary.open}</strong><small>Backlog atual</small></article><article><span>Críticos P1</span><strong>{summary.p1}</strong><small>Atendimento imediato</small></article><article><span>SLA vencido</span><strong>{summary.overdue}</strong><small>Exigem escalonamento</small></article><article><span>Conformidade SLA</span><strong>{summary.slaCompliance}%</strong><small>Meta operacional ≥ 95%</small></article></div>}
