import { useEffect, useMemo, useState } from 'react'
import type { FormEvent } from 'react'
import { Activity, CircleCheck, Eye, EyeOff, KeyRound, Plus, RefreshCw, Save, ScanLine, Trash2, X } from 'lucide-react'
import type { EventItem } from '../data/events'
import { createTrackingIntegration, deleteTrackingIntegration, getTrackingIntegrations, testTrackingIntegration, updateTrackingIntegration, type TrackingIntegration } from '../services/api'

const metaEvents=['PageView','ViewContent','AddToCart','InitiateCheckout','AddPaymentInfo','Purchase','Lead','CompleteRegistration']
type Props={producerId:number|null;events:EventItem[];fixedEventId?:number;notify:(m:string)=>void}
const blank={name:'',pixelId:'',apiToken:'',applyToAllEvents:true,eventIds:[] as number[],enabledEvents:['PageView','ViewContent','AddToCart','InitiateCheckout','Purchase']}

export default function TrackingIntegrationsManager({producerId,events,fixedEventId,notify}:Props){
 const [rows,setRows]=useState<TrackingIntegration[]>([]);const [open,setOpen]=useState(false);const [editing,setEditing]=useState<TrackingIntegration|null>(null);const [form,setForm]=useState(blank);const [showToken,setShowToken]=useState(false);const [busy,setBusy]=useState(false)
 const contextEvent=useMemo(()=>events.find(e=>e.id===fixedEventId),[events,fixedEventId])
 const load=()=>{getTrackingIntegrations(producerId||undefined,fixedEventId).then(setRows).catch(e=>notify(e.message))};useEffect(()=>{load()},[producerId,fixedEventId])
 const startNew=()=>{setEditing(null);setForm({...blank,applyToAllEvents:fixedEventId?false:true,eventIds:fixedEventId?[fixedEventId]:[]});setShowToken(false);setOpen(true)}
 const startEdit=(r:TrackingIntegration)=>{setEditing(r);setForm({name:r.name,pixelId:r.pixelId,apiToken:'',applyToAllEvents:r.applyToAllEvents,eventIds:r.events.map(x=>x.eventId),enabledEvents:r.enabledEvents});setShowToken(false);setOpen(true)}
 const toggleEvent=(id:number)=>setForm(f=>({...f,eventIds:f.eventIds.includes(id)?f.eventIds.filter(x=>x!==id):[...f.eventIds,id]}))
 const toggleMeta=(name:string)=>setForm(f=>({...f,enabledEvents:f.enabledEvents.includes(name)?f.enabledEvents.filter(x=>x!==name):[...f.enabledEvents,name]}))
 const submit=async(e:FormEvent)=>{e.preventDefault();if(!producerId){notify('Selecione uma produtora.');return}if(!form.applyToAllEvents&&!form.eventIds.length){notify('Selecione pelo menos um evento.');return}setBusy(true);try{const payload={...form,producerId,apiToken:form.apiToken||undefined};editing?await updateTrackingIntegration(editing.id,payload):await createTrackingIntegration(payload);notify(editing?'Integração atualizada.':'Novo Pixel / Token adicionado.');setOpen(false);load()}catch(err:any){notify(err.message)}finally{setBusy(false)}}
 const remove=async(r:TrackingIntegration)=>{if(!confirm(`Excluir ${r.name}?`))return;try{await deleteTrackingIntegration(r.id);notify('Integração excluída.');load()}catch(e:any){notify(e.message)}}
 const test=async(r:TrackingIntegration)=>{try{const out=await testTrackingIntegration(r.id);notify(out.message);load()}catch(e:any){notify(e.message)}}
 return <div className="multi-tracking">
  <div className="growth-intro growth-actions"><div><p className="eyebrow">PIXEL & CONVERSION API</p><h2>{fixedEventId?'Pixels do Evento':'Pixels & Tokens API'}</h2><p>{contextEvent?`Integrações ativas para ${contextEvent.title}.`:'Cadastre múltiplos Pixels e Tokens API por produtora e vincule-os aos eventos.'}</p></div><button className="btn primary" onClick={startNew}><Plus size={17}/> Adicionar Pixel / Token</button></div>
  <div className="multi-tracking-summary"><article><ScanLine size={20}/><span><b>{rows.length}</b><small>Integrações</small></span></article><article><CircleCheck size={20}/><span><b>{rows.filter(r=>r.status==='ativo').length}</b><small>Ativas</small></span></article><article><Activity size={20}/><span><b>{rows.reduce((n,r)=>n+(r._count?.deliveryLogs||0),0)}</b><small>Logs registrados</small></span></article></div>
  <div className="multi-tracking-grid">{rows.map(r=><article className="growth-panel integration-card" key={r.id}><div className="integration-card-head"><span className="integration-icon"><ScanLine size={22}/></span><div><strong>{r.name}</strong><small>Meta Pixel + Conversion API</small></div><span className={`status-badge ${r.status==='ativo'?'green':'gray'}`}>{r.status}</span></div><dl><div><dt>Pixel ID</dt><dd>{r.pixelId}</dd></div><div><dt>Token API</dt><dd>{r.apiTokenMasked}</dd></div><div><dt>Aplicação</dt><dd>{r.applyToAllEvents?'Todos os eventos':r.events.map(e=>e.event.title).join(', ')||'Nenhum evento'}</dd></div><div><dt>Último teste</dt><dd>{r.lastTestAt?new Date(r.lastTestAt).toLocaleString('pt-BR'):'Ainda não testado'} {r.lastTestStatus&&<span className={`mini-status ${r.lastTestStatus==='ok'?'ativo':'inativo'}`}>{r.lastTestStatus}</span>}</dd></div></dl><div className="integration-events"><small>Eventos enviados</small><div>{r.enabledEvents.map(x=><span key={x}>{x}</span>)}</div></div><div className="page-actions"><button className="btn secondary" onClick={()=>startEdit(r)}>Editar</button><button className="btn secondary" onClick={()=>test(r)}><RefreshCw size={15}/> Testar conexão</button><button className="icon-action danger" title="Excluir" onClick={()=>remove(r)}><Trash2 size={16}/></button></div></article>)}</div>
  {!rows.length&&<article className="growth-panel feature-empty"><ScanLine size={34}/><h3>Nenhum Pixel / Token cadastrado</h3><p>Adicione a primeira integração para esta produtora ou evento.</p><button className="btn primary" onClick={startNew}><Plus size={17}/> Adicionar integração</button></article>}
  {open&&<div className="integration-editor"><form className="growth-panel integration-editor-card" onSubmit={submit}><div className="integration-editor-head"><div><p className="eyebrow">{editing?'EDITAR INTEGRAÇÃO':'NOVA INTEGRAÇÃO'}</p><h3>{editing?editing.name:'Adicionar Pixel / Token API'}</h3></div><button type="button" className="icon-action" onClick={()=>setOpen(false)}><X size={18}/></button></div><div className="context-form-grid"><label>Nome da integração<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Ex.: Pixel Principal"/></label><label>Pixel ID<input required value={form.pixelId} onChange={e=>setForm({...form,pixelId:e.target.value})} placeholder="123456789012345"/></label></div><label className="token-field"><span>{editing?'Novo Token API (deixe vazio para manter)':'Token da API'}</span><div><input required={!editing} type={showToken?'text':'password'} value={form.apiToken} onChange={e=>setForm({...form,apiToken:e.target.value})} placeholder={editing?'•••••••••••• — manter atual':'Cole o token da Conversion API'}/><button type="button" onClick={()=>setShowToken(v=>!v)}>{showToken?<EyeOff size={17}/>:<Eye size={17}/>}</button></div><small><KeyRound size={13}/> O token será criptografado no backend e nunca será exibido novamente.</small></label><div className="integration-scope"><strong>Aplicar em</strong>{!fixedEventId&&<label><input type="radio" checked={form.applyToAllEvents} onChange={()=>setForm({...form,applyToAllEvents:true,eventIds:[]})}/> Todos os eventos da produtora</label>}<label><input type="radio" checked={!form.applyToAllEvents} onChange={()=>setForm({...form,applyToAllEvents:false,eventIds:fixedEventId?[fixedEventId]:form.eventIds})}/> {fixedEventId?'Apenas o evento atual':'Eventos selecionados'}</label></div>{!form.applyToAllEvents&&!fixedEventId&&<div className="integration-event-picker">{events.map(ev=><label key={ev.id}><input type="checkbox" checked={form.eventIds.includes(ev.id)} onChange={()=>toggleEvent(ev.id)}/><span><strong>{ev.title}</strong><small>{ev.code}</small></span></label>)}</div>}<div className="integration-meta-events"><strong>Eventos enviados para a Meta</strong><div>{metaEvents.map(name=><label key={name}><input type="checkbox" checked={form.enabledEvents.includes(name)} onChange={()=>toggleMeta(name)}/>{name}</label>)}</div></div><div className="page-actions editor-actions"><button type="button" className="btn secondary" onClick={()=>setOpen(false)}>Cancelar</button><button className="btn primary" disabled={busy}><Save size={16}/>{busy?'Salvando...':'Salvar integração'}</button></div></form></div>}
 </div>
}
